let freebaseLibrary = [
  {menuCard: 'aqua.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["mist", "flow", "oasis", "pure"],
    flavors: ["fruit", "green apple pear kiwi", "pineapple mango guava", "peach pineapple papaya", "strawberry watermelon apple"]},
  {menuCard: 'barista_brew.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["dessert", "coffee"],
    flavors: ["cinnamon glazed blueberry scone", "maple bar donut", "salted caramel macchiato"]},
  {menuCard: 'glas_basix.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruit", "menthol", "ice"],
    flavors: ["blueberry cake", "carribean punch", "banana creme pie", "fizzy lemonade"]},
  {menuCard: 'jam_monster.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["dessert", "toast"],
    flavors: ["blackberry", "blueberry", "raspberry"]},
  {menuCard: 'juice_head.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruit"],
    flavors: ["strawberry kiwi", "peach pear", "pineapple grapefruit", "watermelon lime", "blueberry lemon"]},
  {menuCard: 'kilo_sour_series.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruit", "sour"],
    flavors: ["blue raspberry", "green apple", "strawberry", "watermelon", "sours"]},
  {menuCard: 'loyalty.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruity", "menthol.", "ice"],
    flavors: ["melonade", "kiberry", "watamango", "pomnade", "berry cake"]},
  {menuCard: 'marina.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["desert", "cream"],
    flavors: ["kronuts", "strawberry milkshake", "blueberry", "fruity", "milkshake", "donut"]},
  {menuCard: 'met4.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["desert", "cream"],
    flavors: ["golden ticket", "chocolate milk", "strawberry","cream cake", "deep fried", "fairgrounds"]},
  {menuCard: 'naked.jpg',
    strength:["00mg", "03mg", "06mg", "12mg"],
    names: ["fruity"],
    flavors: ["hawaiian pog", "lava flow", "melon kiwi", "maui sun", "really berry", "peachy peach"]},
  {menuCard: 'naked_cream.jpg',
    strength:["00mg", "03mg", "06mg", "12mg"],
    names: ["cream"],
    flavors: ["mango", "azul berries", "banana", "strawberry", "unicorn"]},
  {menuCard: 'naked_menthol.jpg',
    strength:["00mg", "03mg", "06mg", "12mg"],
    names: ["menthol", "ice"],
    flavors: ["very cool", "melon", "strawberry", "pomegranate", "hawaiian pog", "lava flow", "apple cooler"]},
  {menuCard: 'one_up_vapor.jpg',
    strength:["00mg", "03mg", "06mg", "12mg"],
    names: ["fruity", "menthol", "ice"],
    flavors: ["tropical worm", "rainbow spectrum", "orgasm"]},
  {menuCard: 'pacific_northwest_one.jpg',
    strength:["00mg", "03mg", "06mg", "12mg", "18mg"],
    names: ["fruity", "desert"],
    flavors: ["arctic frost", "tobacco", "blueberry muffin", "cherry limeade", "cinnamon crunch", "fruity o's"]},
  {menuCard: 'reds_apple.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruity", "menthol", "ice"],
    flavors: ["watermelon", "apple", "mango"]},
  {menuCard: 'ripe_collection.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruity"],
    flavors: ["fiji melon", "kiwi dragon berry", "blue razzleberry pomegranate", "peach mango pineapple"]},
  {menuCard: 'river_reserve_two.jpg',
    strength:["00mg", "03mg", "06mg", "12mg", "18mg"],
    names: ["fruity", "desert", "menthol", "ice"],
    flavors: ["pbg", "raspberry crumble", "strawberry", "cream", "waffle cone", "strawnana", "swamp mama", "tiger's blood", "vanilla bandit", "vanilla graham", "wiki", "watermelon punch", "pineapple grape", "peach mango lemonade"]},
  {menuCard: 'river_reserve_one.jpg',
    strength:["00mg", "03mg", "06mg", "12mg", "18mg"],
    names: ["fruity", "desert", "menthol", "ice"],
    flavors: ["acid", "worm", "bandit", "blackberry", "waffle cone", "blue island punch", "caramel cove", "castaway", "blueberry", "eddy", "great wall", "island", "lemon drifter", "midori sour", "northwest", "old wolf"]},
  {menuCard: 'ruthless_one.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruity", "menthol", "ice"],
    flavors: ["strizzy", "slurricane", "tropic thunda", "swamp thang", "paradize", "rage"]},
  {menuCard: 'ruthless_two.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruity", "menthol", "ice"],
    flavors: ["jungle fever", "ez duz it", "grape drank", "antidote", "skir skirr"]},
  {menuCard: 'pacific_northwest_two.jpg',
    strength:["00mg", "03mg", "06mg", "12mg", "18mg"],
    names: ["fruity", "dessert"],
    flavors: ["mad batter", "nw4", "peach frost", "peaches", "spearmint", "vanilla nut latte"]},
  {menuCard: 'shijin.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruity", "desert"],
    flavors: ["dragon cloud", "phoenix tears", "tortoise on", "ice", "rocks", "tiger's milk"]},
  {menuCard: 'silverback.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruity", "menthol", "ice"],
    flavors: ["booboo", "jenny", "lola", "sandy"]},
  {menuCard: 'transistor.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruity"],
    flavors: ["lem'n berry", "lsd", "lemon sour drop", "tango melon", "nazzo"]},
  {menuCard: 'air_factory.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["fruity"],
    flavors: ["mystery", "blue razz", "blue raspberry", "berry rush", "wild apple", "melon lush", "kookie krunch"]},
  {menuCard: 'vapetasia.jpg',
    strength:["00mg", "03mg", "06mg"],
    names: ["cream"],
    flavors: ["killer kustard", "strawberry"]},
];
let fourOhFour = [{menuCard: '404.jpg'}] //image for null search returns
