let library = [
	{brand: 'river', shelfName: "", product: "logo", blurb: "Available in 00, 03, 06, 12, and 18mg."},
	{brand: 'river', shelfName: 'Bandit', product: 'bandit', blurb: 'Tobacco with blackberry custard.'},
	{brand: 'river', shelfName: 'Blackberry Waffle Cone', product: 'blackberrywaffle', blurb: 'Blackberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone.'},
	{brand: 'river', shelfName: 'Blackberry Cream', product: 'blackberrycream', blurb: 'Whipped cream with blackberries.'},
	{brand: 'river', shelfName: 'Blue Island Punch', product: 'blueislandpunch', blurb: 'Blue raspberry fruit punch.'},
	{brand: 'river', shelfName: 'Caramel Cove', product: 'caramelcove', blurb: 'Caramel, hazelnut, and marshmallows.'},
	{brand: 'river', shelfName: 'Castaway', product: 'castaway', blurb: 'Coconut, watermelon, and mango.'},
	{brand: 'river', shelfName: 'Eddy', product: 'eddy', blurb: 'Mango pomegranate lemonade.'},
	{brand: 'river', shelfName: 'Great Wall', product: 'greatwall', blurb: 'Graham crackers and caramel adorned with shaved almonds, Kentucky bourbon and a splash of coconut cream.'},
	{brand: 'river', shelfName: 'Lemon Cream', product: 'lemoncream', blurb: 'Whipped cream with tart lemon.'},
	{brand: 'river', shelfName: 'Midori Sour', product: 'midori', blurb: 'Honeydew, lemonlime, and cherry.'},
	{brand: 'river', shelfName: 'Peach Mango Lemonade Menthol', product: 'peachmangolemonadementhol', blurb: ' '},
	{brand: 'river', shelfName: 'Pineapple Grape Menthol', product: 'pineapplegrapementhol', blurb: ' '},
	{brand: 'river', shelfName: 'Raspberry Splash', product: 'raspberrysplash', blurb: 'Raspberry and lemon.'},
	{brand: 'river', shelfName: 'Strawnana Cream', product: 'strawnanacream', blurb: 'Whipped cream with strawberry and banana.'},
	{brand: 'river', shelfName: 'Swamp Mama', product: 'swampmama', blurb: 'Strawberries mixed with sweet vanilla custard.'},
	{brand: 'river', shelfName: 'Strawberry Cream', product: 'strawberrycream', blurb: "Whipped cream with strawberries."},
	{brand: 'river', shelfName: "Tiger's Blood", product: 'tigersblood', blurb: 'Strawberry and coconut.'},
	{brand: 'river', shelfName: 'Vanilla Bandit', product: 'vanbandit', blurb: 'Tobacco with vanilla custard.'},
	{brand: 'river', shelfName: 'Vanilla Graham', product: 'vangraham', blurb: 'Vanilla graham cracker with a brown sugar dusting.'},
	{brand: 'river', shelfName: 'Vanilla Waffle Cone', product: 'vanwafflecone', blurb: 'A scoop of vanilla ice cream atop a vanilla waffle cone.'},
	{brand: 'river', shelfName: 'Watermelon Menthol', product: 'watermelonpunchmenthol', blurb: 'Watermelon fruit punch with menthol.'},
	{brand: 'river', shelfName: 'Wiki', product: 'wiki', blurb: 'Watermelon and kiwi.'},
	{brand: "naked", shelfName: "", product: "logo", blurb: ""},
	{brand: 'naked', shelfName: 'Hawaiian P.O.G.', product: 'pog', blurb: 'Passion fruit, orange, and guava.'},
	{brand: 'naked', shelfName: 'Lava Flow', product: 'lavaflow', blurb: 'Strawberry, pineapple, and coconut.'},
	{brand: 'naked', shelfName: 'Really Berry', product: 'reallyberry', blurb: 'Blue raspberry with a hint of lemon.'},
	{brand: 'naked', shelfName: 'Melon Menthol', product: 'melonmenthol', blurb: 'Honeydew, pineapple, and cantaloupe menthol.'},
	{brand: 'naked', shelfName: 'Strawberry Pom', product: 'strawberrypom', blurb: 'Strawberry pomegranate menthol.'},
	{brand: 'naked', shelfName: 'Berry Menthol', product: 'berrymenthol', blurb: 'Blue raspberry menthol.'},
	//{brand: 'kilo', shelfName: ' ', product: 'logo', blurb: ' '},
	//{brand: 'kilo', shelfName: 'Watermelon Sours', product: 'watermelonsour', blurb: 'Watermelon sour straws.'},
	//{brand: 'kilo', shelfName: 'Blue Raspberry Sours', product: 'blueraspberrysour', blurb: 'Blue raspberry sour straws.'},
	//{brand: 'kilo', shelfName: 'Strawberry Sours', product: 'strawberrysour', blurb: 'Strawberry sour straws.'},
	//{brand: 'kilo', shelfName: 'Peach Pineapple Sours', product: 'peachpineapplesour', blurb: 'Peach and pineapple sour straws.'}
];