let inventory = [
	
	



{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: `${blurbs["airfactory"]["bluerazz"]}`},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: `${blurbs["airfactory"]["bluerazzice"]}`},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: `${blurbs["airfactory"]["creamycrunch"]}`},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: `${blurbs["airfactory"]["menthol"]}`},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: `${blurbs["airfactory"]["mint"]}`},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: `${blurbs["airfactory"]["mixedberry"]}`},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: `${blurbs["airfactory"]["tropicfreeze"]}`},
{brand: "boss", shelfName: " ", product: "logo", blurb: " "},
{brand: "boss", shelfName: "Bossy Pants", product: "bossypants", blurb: `${blurbs["boss"]["bossypants"]}`},
{brand: "boss", shelfName: "Midnight Run", product: "midnightrun", blurb: `${blurbs["boss"]["midnightrun"]}`},
{brand: "boss", shelfName: "Poe", product: "poe", blurb: `${blurbs["boss"]["poe"]}`},
{brand: "boss", shelfName: "Poe Iced", product: "poeiced", blurb: `${blurbs["boss"]["poeiced"]}`},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple", product: "grapeapple", blurb: `${blurbs["cloudnurdz"]["grapeapple"]}`},
{brand: "cloudnurdz", shelfName: "Grape Apple Iced", product: "grapeappleiced", blurb: `${blurbs["cloudnurdz"]["grapeappleiced"]}`},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: `${blurbs["cloudnurdz"]["grapestrawberry"]}`},
{brand: "cloudnurdz", shelfName: "Grape Strawberry Iced", product: "grapestrawberryiced", blurb: `${blurbs["cloudnurdz"]["grapestrawberryiced"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: `${blurbs["cloudnurdz"]["peachbluerazz"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz Iced", product: "peachbluerazziced", blurb: `${blurbs["cloudnurdz"]["peachbluerazziced"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: `${blurbs["cloudnurdz"]["strawberrylemon"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon Iced", product: "strawberrylemoniced", blurb: `${blurbs["cloudnurdz"]["strawberrylemoniced"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: `${blurbs["cloudnurdz"]["watermelonapple"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple Iced", product: "watermelonappleiced", blurb: `${blurbs["cloudnurdz"]["watermelonappleiced"]}`},
{brand: "coastalclouds", shelfName: " ", product: "logo", blurb: " "},
{brand: "coastalclouds", shelfName: "Apple Peach Strawberry", product: "applepeachstrawberry", blurb: `${blurbs["coastalclouds"]["applepeachstrawberry"]}`},
{brand: "coastalclouds", shelfName: "Blood Orange Mango Snow Cone", product: "bloodorangemangosnowcone", blurb: `${blurbs["coastalclouds"]["bloodorangemangosnowcone"]}`},
{brand: "coastalclouds", shelfName: "Blueberry Banana Muffin", product: "blueberrybananamuffin", blurb: `${blurbs["coastalclouds"]["blueberrybananamuffin"]}`},
{brand: "coastalclouds", shelfName: "Blueberry Limeade", product: "blueberrylimeade", blurb: `${blurbs["coastalclouds"]["blueberrylimeade"]}`},
{brand: "coastalclouds", shelfName: "Guava Punch", product: "guavapunch", blurb: `${blurbs["coastalclouds"]["guavapunch"]}`},
{brand: "coastalclouds", shelfName: "Iced Apple Peach Strawberry", product: "icedapplepeachstrawberry", blurb: `${blurbs["coastalclouds"]["icedapplepeachstrawberry"]}`},
{brand: "coastalclouds", shelfName: "Iced Blood Orange Mango Snow Cone", product: "icedbloodorangemangosnowcone", blurb: `${blurbs["coastalclouds"]["icedbloodorangemangosnowcone"]}`},
{brand: "coastalclouds", shelfName: "Iced Mango Berries", product: "icedmangoberries", blurb: `${blurbs["coastalclouds"]["icedmangoberries"]}`},
{brand: "coastalclouds", shelfName: "Iced Passion Fruit Orange Guava", product: "icedpassionfruitorangeguava", blurb: `${blurbs["coastalclouds"]["icedpassionfruitorangeguava"]}`},
{brand: "coastalclouds", shelfName: "Lemon Meringue Pie", product: "lemonmeringuepie", blurb: `${blurbs["coastalclouds"]["lemonmeringuepie"]}`},
{brand: "coastalclouds", shelfName: "Mango Berries", product: "mangoberries", blurb: `${blurbs["coastalclouds"]["mangoberries"]}`},
{brand: "coastalclouds", shelfName: "Passion Fruit Orange Guava", product: "passionfruitorangeguava", blurb: `${blurbs["coastalclouds"]["passionfruitorangeguava"]}`},
{brand: "coastalclouds", shelfName: "Peach Tea", product: "peachtea", blurb: `${blurbs["coastalclouds"]["peachtea"]}`},
{brand: "coastalclouds", shelfName: "Sugared Nectarine", product: "sugarednectarine", blurb: `${blurbs["coastalclouds"]["sugarednectarine"]}`},
{brand: "humble", shelfName: " ", product: "logo", blurb: " "},
{brand: "humble", shelfName: "Blue Raspberry", product: "blueraspberry", blurb: `${blurbs["humble"]["blueraspberry"]}`},
{brand: "humble", shelfName: "Blue Raspberry Menthol", product: "blueraspberrymenthol", blurb: `${blurbs["humble"]["blueraspberrymenthol"]}`},
{brand: "humble", shelfName: "Mango Passion Fruit", product: "mangopassionfruit", blurb: `${blurbs["humble"]["mangopassionfruit"]}`},
{brand: "humble", shelfName: "Toffee Vanilla Custard", product: "toffeevanillacustard", blurb: `${blurbs["humble"]["toffeevanillacustard"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: `${blurbs["juicehead"]["blueberrylemon"]}`},
{brand: "juicehead", shelfName: "Blueberry Lemon Freeze", product: "blueberrylemonfreeze", blurb: `${blurbs["juicehead"]["blueberrylemonfreeze"]}`},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: `${blurbs["juicehead"]["guavapeach"]}`},
{brand: "juicehead", shelfName: "Guava Peach Ice", product: "guavapeachice", blurb: `${blurbs["juicehead"]["guavapeachice"]}`},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: `${blurbs["juicehead"]["peachpear"]}`},
{brand: "juicehead", shelfName: "Peach Pear Freeze", product: "peachpearfreeze", blurb: `${blurbs["juicehead"]["peachpearfreeze"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit Freeze", product: "pineapplegrapefruitfreeze", blurb: `${blurbs["juicehead"]["pineapplegrapefruitfreeze"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi Freeze", product: "strawberrykiwifreeze", blurb: `${blurbs["juicehead"]["strawberrykiwifreeze"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: `${blurbs["juicehead"]["watermelonlime"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: `${blurbs["juicehead"]["watermelonlimefreeze"]}`},
{brand: "loyalty", shelfName: " ", product: "logo", blurb: " "},
{brand: "loyalty", shelfName: "PomNAde", product: "pomnade", blurb: `${blurbs["loyalty"]["pomnade"]}`},
{brand: "loyalty", shelfName: "PomNAde Ice", product: "pomnadeice", blurb: `${blurbs["loyalty"]["pomnadeice"]}`},
{brand: "mamasan", shelfName: " ", product: "logo", blurb: " "},
{brand: "mamasan", shelfName: "ASAP", product: "asap", blurb: `${blurbs["mamasan"]["asap"]}`},
{brand: "mamasan", shelfName: "Guava Pop", product: "guavapop", blurb: `${blurbs["mamasan"]["guavapop"]}`},
{brand: "mamasan", shelfName: "Mama Melon", product: "mamamelon", blurb: `${blurbs["mamasan"]["mamamelon"]}`},
{brand: "mamasan", shelfName: "Purple Cheesecake", product: "purplecheesecake", blurb: `${blurbs["mamasan"]["purplecheesecake"]}`},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: `${blurbs["naked"]["americanpatriot"]}`},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: `${blurbs["naked"]["cubanblend"]}`},
{brand: "naked", shelfName: "Euro Gold", product: "eurogold", blurb: `${blurbs["naked"]["eurogold"]}`},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: `${blurbs["naked"]["hawaiianpog"]}`},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: `${blurbs["naked"]["lavaflow"]}`},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: `${blurbs["naked"]["reallyberryveryberry"]}`},
{brand: "naked", shelfName: "Menthol Brain Freeze", product: "mentholbrainfreeze", blurb: `${blurbs["naked"]["mentholbrainfreeze"]}`},
{brand: "naked", shelfName: "Menthol Polar Breeze", product: "mentholpolarbreeze", blurb: `${blurbs["naked"]["mentholpolarbreeze"]}`},
{brand: "naked", shelfName: "Menthol Very Cool", product: "mentholverycool", blurb: `${blurbs["naked"]["mentholverycool"]}`},
{brand: "ofe", shelfName: " ", product: "logo", blurb: " "},
{brand: "ofe", shelfName: "Classic Gold", product: "classicgold", blurb: `${blurbs["ofe"]["classicgold"]}`},
{brand: "ofe", shelfName: "Original Bold", product: "originalbold", blurb: `${blurbs["ofe"]["originalbold"]}`},
{brand: "ofe", shelfName: "Turkish Blend", product: "turkishblend", blurb: `${blurbs["ofe"]["turkishblend"]}`},
{brand: "reds", shelfName: " ", product: "logo", blurb: " "},
{brand: "reds", shelfName: "Apple", product: "apple", blurb: `${blurbs["reds"]["apple"]}`},
{brand: "reds", shelfName: "Apple Iced", product: "appleiced", blurb: `${blurbs["reds"]["appleiced"]}`},
{brand: "reds", shelfName: "Berries", product: "berries", blurb: `${blurbs["reds"]["berries"]}`},
{brand: "reds", shelfName: "Berries Iced", product: "berriesiced", blurb: `${blurbs["reds"]["berriesiced"]}`},
{brand: "reds", shelfName: "Grape", product: "grape", blurb: `${blurbs["reds"]["grape"]}`},
{brand: "reds", shelfName: "Guava", product: "guava", blurb: `${blurbs["reds"]["guava"]}`},
{brand: "reds", shelfName: "Guava Iced", product: "guavaiced", blurb: `${blurbs["reds"]["guavaiced"]}`},
{brand: "reds", shelfName: "Mango", product: "mango", blurb: `${blurbs["reds"]["mango"]}`},
{brand: "reds", shelfName: "Mango Iced", product: "mangoiced", blurb: `${blurbs["reds"]["mangoiced"]}`},
{brand: "reds", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["reds"]["strawberry"]}`},
{brand: "reds", shelfName: "Strawberry Iced", product: "strawberryiced", blurb: `${blurbs["reds"]["strawberryiced"]}`},
{brand: "reds", shelfName: "Watermelon", product: "watermelon", blurb: `${blurbs["reds"]["watermelon"]}`},
{brand: "reds", shelfName: "Watermelon Iced", product: "watermeloniced", blurb: `${blurbs["reds"]["watermeloniced"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: `${blurbs["riverreserve"]["blackberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: `${blurbs["riverreserve"]["blueislandpunch"]}`},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: `${blurbs["riverreserve"]["boldtobacco"]}`},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: `${blurbs["riverreserve"]["caramelappledrifter"]}`},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: `${blurbs["riverreserve"]["caramelcove"]}`},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: `${blurbs["riverreserve"]["castaway"]}`},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: `${blurbs["riverreserve"]["clearwatercreek"]}`},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: `${blurbs["riverreserve"]["eddy"]}`},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: `${blurbs["riverreserve"]["islandpunch"]}`},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: `${blurbs["riverreserve"]["midorisour"]}`},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: `${blurbs["riverreserve"]["oldwolf"]}`},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: `${blurbs["riverreserve"]["peachmangolemonade"]}`},
{brand: "riverreserve", shelfName: "Pebbles Cheesecake", product: "pebblescheesecake", blurb: `${blurbs["riverreserve"]["pebblescheesecake"]}`},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: `${blurbs["riverreserve"]["pineapplegrapementhol"]}`},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: `${blurbs["riverreserve"]["raspberrycrumble"]}`},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: `${blurbs["riverreserve"]["raspberrylemonitalianice"]}`},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: `${blurbs["riverreserve"]["rivercolada"]}`},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: `${blurbs["riverreserve"]["smoothsweettobacco"]}`},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: `${blurbs["riverreserve"]["strawberrydrifter"]}`},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: `${blurbs["riverreserve"]["strawberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: `${blurbs["riverreserve"]["strawnanadrifter"]}`},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: `${blurbs["riverreserve"]["vanillagraham"]}`},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: `${blurbs["riverreserve"]["vanillawafflecone"]}`},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: `${blurbs["riverreserve"]["watermelonpunchmenthol"]}`},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: `${blurbs["ruthless"]["ezduzit"]}`},
{brand: "ruthless", shelfName: "Ez Duz It On Ice", product: "ezduzitonice", blurb: `${blurbs["ruthless"]["ezduzitonice"]}`},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: `${blurbs["ruthless"]["grapedrank"]}`},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: `${blurbs["ruthless"]["grapedrankonice"]}`},
{brand: "ruthless", shelfName: "Skir Skirr On Ice", product: "skirskirronice", blurb: `${blurbs["ruthless"]["skirskirronice"]}`},
{brand: "ruzepremium", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruzepremium", shelfName: "Patriot", product: "patriot", blurb: `${blurbs["ruzepremium"]["patriot"]}`},
{brand: "ruzepremium", shelfName: "Perfect Pear", product: "perfectpear", blurb: `${blurbs["ruzepremium"]["perfectpear"]}`},
{brand: "ruzepremium", shelfName: "Whipped", product: "whipped", blurb: `${blurbs["ruzepremium"]["whipped"]}`},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Blue Cotton Candy", product: "bluecottoncandy", blurb: `${blurbs["sadboy"]["bluecottoncandy"]}`},
{brand: "sadboy", shelfName: "Butter Cookie", product: "buttercookie", blurb: `${blurbs["sadboy"]["buttercookie"]}`},
{brand: "sadboy", shelfName: "Pink Cotton Candy", product: "pinkcottoncandy", blurb: `${blurbs["sadboy"]["pinkcottoncandy"]}`},
{brand: "sadboy", shelfName: "Shamrock Cookie", product: "shamrockcookie", blurb: `${blurbs["sadboy"]["shamrockcookie"]}`},
{brand: "sadboy", shelfName: "Unicorn Tears", product: "unicorntears", blurb: `${blurbs["sadboy"]["unicorntears"]}`},
{brand: "vapetasia", shelfName: " ", product: "logo", blurb: " "},
{brand: "vapetasia", shelfName: "Killer Kustard", product: "killerkustard", blurb: `${blurbs["vapetasia"]["killerkustard"]}`},
{brand: "vapetasia", shelfName: "Milk of the Poppy", product: "milkofthepoppy", blurb: `${blurbs["vapetasia"]["milkofthepoppy"]}`},
{brand: "vapetasia", shelfName: "Rainbow Road", product: "rainbowroad", blurb: `${blurbs["vapetasia"]["rainbowroad"]}`},
{brand: "vapetasia", shelfName: "Strawberry Killer Kustard", product: "strawberrykillerkustard", blurb: `${blurbs["vapetasia"]["strawberrykillerkustard"]}`},




];

let saltInventory = [
	
	
{brand: "boss", shelfName: " ", product: "logo", blurb: " "},
{brand: "boss", shelfName: "Bossy Pants", product: "bossypants", blurb: "undefined"},
{brand: "boss", shelfName: "Poe", product: "poe", blurb: "undefined"},
{brand: "humble", shelfName: " ", product: "logo", blurb: " "},
{brand: "humble", shelfName: "Blue Raspberry Menthol", product: "blueraspberrymenthol", blurb: "undefined"},
{brand: "humble", shelfName: "Strawberry Banana", product: "strawberrybanana", blurb: "undefined"},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Apple Tobacco", product: "appletobacco", blurb: "undefined"},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Royal Tobacco", product: "royaltobacco", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Summer Berry", product: "summerberry", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Tangie", product: "tangie", blurb: "undefined"},
{brand: "riverreserve", shelfName: "water Creek", product: "watercreek", blurb: "undefined"},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Mango Blood", product: "mangoblood", blurb: "undefined"},
{brand: "sadboy", shelfName: "Mango Ice", product: "mangoice", blurb: "undefined"},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Berry Bash", product: "berrybash", blurb: "Mixed berries."},
{brand: "solace", shelfName: "Blue Raspberry Lemonade Ice", product: "blueraspberrylemonadeice", blurb: "undefined"},
{brand: "solace", shelfName: "Blues Mango", product: "bluesmango", blurb: "Mango with a hint of... blue raspberry."},
{brand: "solace", shelfName: "Juiced Apple", product: "juicedapple", blurb: " "},
{brand: "solace", shelfName: "Mint", product: "mint", blurb: "undefined"},
{brand: "solace", shelfName: "Sea Blueberry", product: "seablueberry", blurb: " "},
{brand: "solace", shelfName: "Seedless Watermelon", product: "seedlesswatermelon", blurb: "There actually are seeds, be careful."},
{brand: "solace", shelfName: "Strawberry Kiwi Ice", product: "strawberrykiwiice", blurb: "Strawberry kiwi with menthol."},
{brand: "solace", shelfName: "Tropic Strawberry", product: "tropicstrawberry", blurb: " "},


];

let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
