var saltLibrary = [
  {menuCard: 'glas_basix_salts.jpg',
    strength:["30mg", "50mg"],
    names: ["fruit", "menthol", "dessert"],
    flavors: ["juicy apple", "mango tango", "cool melon", "fizzy lemonade", "banana cream pie", "blue magic", "crunch berry"]},
  {menuCard: 'juice_head_salts.jpg',
    strength:["25mg", "50mg"],
    names: ["fruit"],
    flavors: ["strawberry kiwi", "peach pear", "pineapple grapefruit", "watermelon lime", "blueberry lemon"]},
  {menuCard: 'salt_factory.jpg',
    strength:["35mg", "50mg"],
    names: ["fruit"],
    flavors: ["blue razz", "mystery", "mint", "melon lush"]},
  {menuCard: 'met4_salts.jpg',
    strength:["24mg", "48mg"],
    names: ["dessert"],
    flavors: ["golden ticket", "strawberry milk", "fairgrounds", "deep fried cream cake"]},
  {menuCard: 'naked_salts.jpg',
    strength:["35mg", "50mg"],
    names: ["fruit", "menthol", "tobacco"],
    flavors: ["hawaiian pog", "lava flow", "really berry", "melon kiwi", "strawberry pom", "melon", "berry", "polar breze", "brain freeze", "very cool", "american patriot", "mint"]},
  {menuCard: 'reds_salts.jpg',
    strength:["30mg", "50mg"],
    names: ["fruit", "menthol"],
    flavors: ["apple", "watermelon", "mango", "grape", "berries", "guava"]},
  {menuCard: 'river_reserve_salts.jpg',
    strength:["25mg", "40mg"],
    names: ["fruit", "cream", "dessert", "menthol"],
    flavors: ["blue island punch", "lemon drifter", "royal tobacco", "summer berry", "tangle", "vanilla waffle cone", "winter berry"]},
  {menuCard: 'shijin_salts.jpg',
    strength:["50mg"],
    names: ["fruit", "dessert"],
    flavors: ["dragon", "phoenix", "tortoise", "tiger"]},
  {menuCard: 'svrf_salts.jpg',
    strength:["24mg", "48mg"],
    names: ["fruit", "cream"],
    flavors: ["raspberry dragon fruit iced tea", "papaya mango cataloupe", "coconut and cream"]},
];
let fourOhFour = [{menuCard: '404.jpg'}]