let inventory = [
	
	
{brand: "cyber", shelfName: " ", product: "logo", blurb: " "},
{brand: "cyber", shelfName: "Cafe Royale", product: "caferoyale", blurb: "undefined"},
{brand: "fivepawns", shelfName: " ", product: "logo", blurb: " "},
{brand: "fivepawns", shelfName: "Bowdens Mate", product: "bowdensmate", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Castle Long", product: "castlelong", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Gambit", product: "gambit", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Grandmaster", product: "grandmaster", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Queenside", product: "queenside", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Tobacco Series Kingside Tobacco", product: "tobaccoserieskingsidetobacco", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Tobacco Series Royal Tobacco", product: "tobaccoseriesroyaltobacco", blurb: "undefined"},
{brand: "humble", shelfName: " ", product: "logo", blurb: " "},
{brand: "humble", shelfName: "Hop Scotch", product: "hopscotch", blurb: "undefined"},
{brand: "humble", shelfName: "Humble Crumble", product: "humblecrumble", blurb: "undefined"},
{brand: "humble", shelfName: "Ice Sweater Puppets", product: "icesweaterpuppets", blurb: "undefined"},
{brand: "humble", shelfName: "Unicorn Treats", product: "unicorntreats", blurb: "undefined"},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Banana", product: "banana", blurb: "25% Toast, 25% Butter, 50% Banana."},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: "25% Toast, 25% Butter, 50% Blackberry Jam."},
{brand: "jammonster", shelfName: "Blueberry", product: "blueberry", blurb: "25% Toast, 25% Butter, 50% Blueberry Jam."},
{brand: "jammonster", shelfName: "Blueberry Raspberry Lemon", product: "blueberryraspberrylemon", blurb: " "},
{brand: "jammonster", shelfName: "Mango Peach Guava", product: "mangopeachguava", blurb: " "},
{brand: "jammonster", shelfName: "Mixed Berry", product: "mixedberry", blurb: "25% Toast, 25% Butter, 50% Strawberry, Blueberry, and Raspberry Jam. How exciting."},
{brand: "jammonster", shelfName: "PB Jam Monster Strawberry", product: "pbjammonsterstrawberry", blurb: "25% Toast, 25% Peanut Butter, 50% Strawberry Jam."},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: "25% Toast, 25% Butter, 50% Raspberry Jam."},
{brand: "jammonster", shelfName: "Strawberry", product: "strawberry", blurb: "25% Toast, 25% Butter, 50% Strawberry Jam."},
{brand: "jammonster", shelfName: "Strawberry Custard", product: "strawberrycustard", blurb: "undefined"},
{brand: "jammonster", shelfName: "Strawberry Kiwi Pomegranate", product: "strawberrykiwipomegranate", blurb: " "},
{brand: "jammonster", shelfName: "Strawmelon Apple ICE", product: "strawmelonappleice", blurb: "Strawberry watermelon menthol."},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit Freeze", product: "pineapplegrapefruitfreeze", blurb: "undefined"},
{brand: "microbrew", shelfName: " ", product: "logo", blurb: " "},
{brand: "microbrew", shelfName: "Grumpy Old Bastard", product: "grumpyoldbastard", blurb: "undefined"},
{brand: "microbrew", shelfName: "One Eyed Turtle", product: "oneeyedturtle", blurb: "undefined"},
{brand: "microbrew", shelfName: "The Goat Herder", product: "thegoatherder", blurb: "undefined"},
{brand: "microbrew", shelfName: "The Secret Handshake", product: "thesecrethandshake", blurb: "undefined"},
{brand: "northwestfinest", shelfName: " ", product: "logo", blurb: " "},
{brand: "northwestfinest", shelfName: "Rockin Seas", product: "rockinseas", blurb: "undefined"},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: "An icy cold hit to the back of your throat."},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Huckleberry", product: "huckleberry", blurb: "undefined"},
{brand: "pachamama", shelfName: "Passion Fruit", product: "passionfruit", blurb: "undefined"},
{brand: "pachamama", shelfName: "Peach", product: "peach", blurb: "undefined"},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: "Tobacco with blackberry custard."},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: "Blackberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: "Caramel apple custard."},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: "Caramel, hazelnut, and marshmallows."},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: "Coconut, watermelon, and mango."},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: "Nothin! Just VG, PG, and nicotine."},
{brand: "riverreserve", shelfName: "Drifter", product: "drifter", blurb: "Whipped cream with blueberries."},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: "Mango pomegranate lemonade."},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: "Graham crackers and caramel adorned with shaved almonds, Kentucky bourbon and a splash of coconut cream."},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: "Whipped cream with tart lemon."},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: "Honeydew, lemonlime, and cherry."},
{brand: "riverreserve", shelfName: "Mild Tobacco", product: "mildtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Natural Tobacco", product: "naturaltobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: "Just like those little rootbeer barrel candies."},
{brand: "riverreserve", shelfName: "PBG", product: "pbg", blurb: "Peanut butter, banana, graham cracker."},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: " "},
{brand: "riverreserve", shelfName: "Pebbles Cheesecake", product: "pebblescheesecake", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: " "},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: "Raspberry and lemon."},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: "Tobacco with a hint of vanilla cream."},
{brand: "riverreserve", shelfName: "Strawberry Bandit", product: "strawberrybandit", blurb: "Strawberry custard and tobacco."},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: "Whipped cream with strawberries."},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: "Strawberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: "Whipped cream with strawberry and banana."},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: "Strawberries mixed with sweet vanilla custard."},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: "Strawberry and coconut."},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: "Tobacco with vanilla custard."},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: "Vanilla graham cracker with a brown sugar dusting."},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: "A scoop of vanilla ice cream atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: "Watermelon fruit punch with menthol."},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: "Watermelon and kiwi."},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Blueberry Custard", product: "blueberrycustard", blurb: "undefined"},
{brand: "ruthless", shelfName: "Pudding Custard", product: "puddingcustard", blurb: "undefined"},
{brand: "ruthless", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: "undefined"},
{brand: "ruthless", shelfName: "Antidote", product: "antidote", blurb: "Peach, mango, and blue raspberry."},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: "Strawberry watermelon."},
{brand: "ruthless", shelfName: "Ez Duz It On Ice", product: "ezduzitonice", blurb: "Strawberry watermelon and menthol."},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: "Grape soda."},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: "Grape soda with menthol."},
{brand: "ruthless", shelfName: "Jungle Fever", product: "junglefever", blurb: "Pineapple, mango, citrus."},
{brand: "ruthless", shelfName: "Slurricane", product: "slurricane", blurb: "Peach, papaya, and guava."},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: "Raspberry, kiwi, and strawberry."},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: "Sour candy apple."},
{brand: "ruthless", shelfName: "Swamp Thang On Ice", product: "swampthangonice", blurb: "undefined"},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: "Guava and mixed berries."},
{brand: "ruthless", shelfName: "Loaded Cookie Butter", product: "loadedcookiebutter", blurb: "undefined"},
{brand: "ruthless", shelfName: "Loaded Cran Apple", product: "loadedcranapple", blurb: "undefined"},
{brand: "ruthless", shelfName: "Loaded Glazed Donuts", product: "loadedglazeddonuts", blurb: "undefined"},
{brand: "ruthless", shelfName: "Loaded Raspberry Eclair", product: "loadedraspberryeclair", blurb: "undefined"},
{brand: "ruthless", shelfName: "Loaded Strawberry Jelly Donut", product: "loadedstrawberryjellydonut", blurb: "undefined"},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: "undefined"},
{brand: "svrf", shelfName: "Blue Gummy", product: "bluegummy", blurb: "undefined"},
{brand: "svrf", shelfName: "Fairground", product: "fairground", blurb: "Deep fried cream cake."},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: "undefined"},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: "undefined"},
{brand: "svrf", shelfName: "Stimulating", product: "stimulating", blurb: "undefined"},
{brand: "svrf", shelfName: "Boba Dewwy", product: "bobadewwy", blurb: "undefined"},
{brand: "svrf", shelfName: "Boba Jazzy", product: "bobajazzy", blurb: "undefined"},
{brand: "svrf", shelfName: "Boba Manggo", product: "bobamanggo", blurb: "undefined"},


];

let saltInventory = [

	
{brand: "californiagrown", shelfName: " ", product: "logo", blurb: " "},
{brand: "californiagrown", shelfName: "Grizzly Apple cool", product: "grizzlyapplecool", blurb: "undefined"},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Melon Colada", product: "meloncolada", blurb: "Melon, pineapple, and coconut cream."},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: "25% Toast, 25% Butter, 50% Raspberry Jam."},
{brand: "jammonster", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: "Plain vanilla custard."},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: "Pink lemonade with menthol."},
{brand: "lemontwist", shelfName: "Pink Punch Lemonade", product: "pinkpunchlemonade", blurb: "Pink punch lemonade."},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: "Watermelon and lemonade."},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: "Watermelon and lemonade."},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Fuji", product: "fuji", blurb: "undefined"},
{brand: "pachamama", shelfName: "Icy Mango", product: "icymango", blurb: "undefined"},
{brand: "pachamama", shelfName: "Strawberry Watermelon", product: "strawberrywatermelon", blurb: "undefined"},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Savage Patch", product: "savagepatch", blurb: "undefined"},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Smooth Tobacco", product: "smoothtobacco", blurb: "undefined"},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: "undefined"},
{brand: "svrf", shelfName: "Fairgrounds", product: "fairgrounds", blurb: "Deep fried cream cake."},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: "Strawberry milk."},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: "undefined"},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Blue Jam Cookie", product: "bluejamcookie", blurb: "undefined"},
{brand: "sadboy", shelfName: "Custard Cookie", product: "custardcookie", blurb: "undefined"},
{brand: "sadboy", shelfName: "Mango Blood", product: "mangoblood", blurb: "undefined"},
{brand: "sadboy", shelfName: "Punch Berry Blood", product: "punchberryblood", blurb: "Sour raspberry lemonade punch."},
{brand: "sadboy", shelfName: "Punch Berry Ice", product: "punchberryice", blurb: "Sour raspberry lemonade punch, with menthol."},
{brand: "sadboy", shelfName: "Straw Jam Cookie", product: "strawjamcookie", blurb: "undefined"},
{brand: "sadboy", shelfName: "Strawberry Ice", product: "strawberryice", blurb: "Strawberry candy with menthol."},
{brand: "shijinvapor", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijinvapor", shelfName: "Phoenix", product: "phoenix", blurb: "Guava lychee."},
{brand: "shijinvapor", shelfName: "Tortoise", product: "tortoise", blurb: "Green apple, blue raspberry."},
{brand: "shijinvapor", shelfName: "Tortoise Ice", product: "tortoiseice", blurb: "undefined"},
{brand: "skwezed", shelfName: " ", product: "logo", blurb: " "},
{brand: "skwezed", shelfName: "Lychee", product: "lychee", blurb: " "},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Banana Dragonberry", product: "bananadragonberry", blurb: "Dragonfruit and banana."},
{brand: "solace", shelfName: "Blues Mango", product: "bluesmango", blurb: "Mango with a hint of... blue raspberry."},
{brand: "solace", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: "undefined"},
{brand: "solace", shelfName: "Grape", product: "grape", blurb: " "},
{brand: "solace", shelfName: "Mint", product: "mint", blurb: "undefined"},
{brand: "solace", shelfName: "Pineapple", product: "pineapple", blurb: " "},
{brand: "solace", shelfName: "Strawberry Kiwi Ice", product: "strawberrykiwiice", blurb: "Strawberry kiwi with menthol."},
{brand: "vapetasia", shelfName: " ", product: "logo", blurb: " "},
{brand: "vapetasia", shelfName: "Killer Kustard", product: "killerkustard", blurb: "Vanilla custard."},
{brand: "yogi", shelfName: " ", product: "logo", blurb: " "},
{brand: "yogi", shelfName: "Blueberry Granola", product: "blueberrygranola", blurb: "undefined"},
{brand: "yogi", shelfName: "Strawberry Granola", product: "strawberrygranola", blurb: "undefined"},

	
];

let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
