
let inventory = [
{brand: "cyber", shelfName: " ", product: "logo", blurb: " "},
{brand: "cyber", shelfName: "Cafe Royale", product: "caferoyale", blurb: `${blurbs["cyber"]["caferoyale"]}`},
{brand: "humble", shelfName: " ", product: "logo", blurb: " "},
{brand: "humble", shelfName: "Hop Scotch", product: "hopscotch", blurb: `${blurbs["humble"]["hopscotch"]}`},
{brand: "humble", shelfName: "Humble Crumble", product: "humblecrumble", blurb: `${blurbs["humble"]["humblecrumble"]}`},
{brand: "humble", shelfName: "Ice Sweater Puppets", product: "icesweaterpuppets", blurb: `${blurbs["humble"]["icesweaterpuppets"]}`},
{brand: "humble", shelfName: "Unicorn Treats", product: "unicorntreats", blurb: `${blurbs["humble"]["unicorntreats"]}`},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Banana", product: "banana", blurb: `${blurbs["jammonster"]["banana"]}`},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: `${blurbs["jammonster"]["blackberry"]}`},
{brand: "jammonster", shelfName: "Blueberry", product: "blueberry", blurb: `${blurbs["jammonster"]["blueberry"]}`},
{brand: "jammonster", shelfName: "Blueberry Raspberry Lemon", product: "blueberryraspberrylemon", blurb: `${blurbs["jammonster"]["blueberryraspberrylemon"]}`},
{brand: "jammonster", shelfName: "Mango Peach Guava", product: "mangopeachguava", blurb: `${blurbs["jammonster"]["mangopeachguava"]}`},
{brand: "jammonster", shelfName: "Mixed Berry", product: "mixedberry", blurb: `${blurbs["jammonster"]["mixedberry"]}`},
{brand: "jammonster", shelfName: "PB Jam Monster Strawberry", product: "pbjammonsterstrawberry", blurb: `${blurbs["jammonster"]["pbjammonsterstrawberry"]}`},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: `${blurbs["jammonster"]["raspberry"]}`},
{brand: "jammonster", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["jammonster"]["strawberry"]}`},
{brand: "jammonster", shelfName: "Strawberry Custard", product: "strawberrycustard", blurb: `${blurbs["jammonster"]["strawberrycustard"]}`},
{brand: "jammonster", shelfName: "Strawberry Kiwi Pomegranate", product: "strawberrykiwipomegranate", blurb: `${blurbs["jammonster"]["strawberrykiwipomegranate"]}`},
{brand: "jammonster", shelfName: "Strawmelon Apple ICE", product: "strawmelonappleice", blurb: `${blurbs["jammonster"]["strawmelonappleice"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit Freeze", product: "pineapplegrapefruitfreeze", blurb: `${blurbs["juicehead"]["pineapplegrapefruitfreeze"]}`},
{brand: "microbrew", shelfName: " ", product: "logo", blurb: " "},
{brand: "microbrew", shelfName: "Grumpy Old Bastard", product: "grumpyoldbastard", blurb: `${blurbs["microbrew"]["grumpyoldbastard"]}`},
{brand: "microbrew", shelfName: "One Eyed Turtle", product: "oneeyedturtle", blurb: `${blurbs["microbrew"]["oneeyedturtle"]}`},
{brand: "microbrew", shelfName: "The Goat Herder", product: "thegoatherder", blurb: `${blurbs["microbrew"]["thegoatherder"]}`},
{brand: "microbrew", shelfName: "The Secret Handshake", product: "thesecrethandshake", blurb: `${blurbs["microbrew"]["thesecrethandshake"]}`},
{brand: "northwestfinest", shelfName: " ", product: "logo", blurb: " "},
{brand: "northwestfinest", shelfName: "Rockin Seas", product: "rockinseas", blurb: `${blurbs["northwestfinest"]["rockinseas"]}`},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: `${blurbs["pnw"]["arcticfrost"]}`},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Huckleberry Pear Acai", product: "huckleberrypearacai", blurb: `${blurbs["pachamama"]["huckleberrypearacai"]}`},
{brand: "pachamama", shelfName: "Passion Fruit Raspberry Yuzu", product: "passionfruitraspberryyuzu", blurb: `${blurbs["pachamama"]["passionfruitraspberryyuzu"]}`},
{brand: "pachamama", shelfName: "Peach Papaya Coconut Cream", product: "peachpapayacoconutcream", blurb: `${blurbs["pachamama"]["peachpapayacoconutcream"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: `${blurbs["riverreserve"]["bandit"]}`},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: `${blurbs["riverreserve"]["blackberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: `${blurbs["riverreserve"]["boldtobacco"]}`},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: `${blurbs["riverreserve"]["caramelappledrifter"]}`},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: `${blurbs["riverreserve"]["caramelcove"]}`},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: `${blurbs["riverreserve"]["castaway"]}`},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: `${blurbs["riverreserve"]["clearwatercreek"]}`},
{brand: "riverreserve", shelfName: "Drifter", product: "drifter", blurb: `${blurbs["riverreserve"]["drifter"]}`},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: `${blurbs["riverreserve"]["eddy"]}`},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: `${blurbs["riverreserve"]["greatwall"]}`},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: `${blurbs["riverreserve"]["lemondrifter"]}`},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: `${blurbs["riverreserve"]["midorisour"]}`},
{brand: "riverreserve", shelfName: "Mild Tobacco", product: "mildtobacco", blurb: `${blurbs["riverreserve"]["mildtobacco"]}`},
{brand: "riverreserve", shelfName: "Natural Tobacco", product: "naturaltobacco", blurb: `${blurbs["riverreserve"]["naturaltobacco"]}`},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: `${blurbs["riverreserve"]["oldwolf"]}`},
{brand: "riverreserve", shelfName: "PBG", product: "pbg", blurb: `${blurbs["riverreserve"]["pbg"]}`},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: `${blurbs["riverreserve"]["peachmangolemonade"]}`},
{brand: "riverreserve", shelfName: "Pebbles Cheesecake", product: "pebblescheesecake", blurb: `${blurbs["riverreserve"]["pebblescheesecake"]}`},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: `${blurbs["riverreserve"]["pineapplegrapementhol"]}`},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: `${blurbs["riverreserve"]["raspberrycrumble"]}`},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: `${blurbs["riverreserve"]["raspberrylemonitalianice"]}`},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: `${blurbs["riverreserve"]["smoothsweettobacco"]}`},
{brand: "riverreserve", shelfName: "Strawberry Bandit", product: "strawberrybandit", blurb: `${blurbs["riverreserve"]["strawberrybandit"]}`},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: `${blurbs["riverreserve"]["strawberrydrifter"]}`},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: `${blurbs["riverreserve"]["strawberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: `${blurbs["riverreserve"]["strawnanadrifter"]}`},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: `${blurbs["riverreserve"]["swampmama"]}`},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: `${blurbs["riverreserve"]["tigersblood"]}`},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: `${blurbs["riverreserve"]["vanillabandit"]}`},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: `${blurbs["riverreserve"]["vanillagraham"]}`},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: `${blurbs["riverreserve"]["vanillawafflecone"]}`},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: `${blurbs["riverreserve"]["watermelonpunchmenthol"]}`},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: `${blurbs["riverreserve"]["wiki"]}`},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Blueberry Custard", product: "blueberrycustard", blurb: `${blurbs["ruthless"]["blueberrycustard"]}`},
{brand: "ruthless", shelfName: "Pudding Custard", product: "puddingcustard", blurb: `${blurbs["ruthless"]["puddingcustard"]}`},
{brand: "ruthless", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: `${blurbs["ruthless"]["vanillacustard"]}`},
{brand: "ruthless", shelfName: "Antidote", product: "antidote", blurb: `${blurbs["ruthless"]["antidote"]}`},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: `${blurbs["ruthless"]["ezduzit"]}`},
{brand: "ruthless", shelfName: "Ez Duz It On Ice", product: "ezduzitonice", blurb: `${blurbs["ruthless"]["ezduzitonice"]}`},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: `${blurbs["ruthless"]["grapedrank"]}`},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: `${blurbs["ruthless"]["grapedrankonice"]}`},
{brand: "ruthless", shelfName: "Jungle Fever", product: "junglefever", blurb: `${blurbs["ruthless"]["junglefever"]}`},
{brand: "ruthless", shelfName: "Slurricane", product: "slurricane", blurb: `${blurbs["ruthless"]["slurricane"]}`},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: `${blurbs["ruthless"]["strizzy"]}`},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: `${blurbs["ruthless"]["swampthang"]}`},
{brand: "ruthless", shelfName: "Swamp Thang On Ice", product: "swampthangonice", blurb: `${blurbs["ruthless"]["swampthangonice"]}`},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: `${blurbs["ruthless"]["tropicthunda"]}`},
{brand: "ruthless", shelfName: "Loaded Cookie Butter", product: "loadedcookiebutter", blurb: `${blurbs["ruthless"]["loadedcookiebutter"]}`},
{brand: "ruthless", shelfName: "Loaded Cran Apple", product: "loadedcranapple", blurb: `${blurbs["ruthless"]["loadedcranapple"]}`},
{brand: "ruthless", shelfName: "Loaded Glazed Donuts", product: "loadedglazeddonuts", blurb: `${blurbs["ruthless"]["loadedglazeddonuts"]}`},
{brand: "ruthless", shelfName: "Loaded Raspberry Eclair", product: "loadedraspberryeclair", blurb: `${blurbs["ruthless"]["loadedraspberryeclair"]}`},
{brand: "ruthless", shelfName: "Loaded Strawberry Jelly Donut", product: "loadedstrawberryjellydonut", blurb: `${blurbs["ruthless"]["loadedstrawberryjellydonut"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: `${blurbs["svrf"]["balanced"]}`},
{brand: "svrf", shelfName: "Blue Gummy", product: "bluegummy", blurb: `${blurbs["svrf"]["bluegummy"]}`},
{brand: "svrf", shelfName: "Fairground", product: "fairground", blurb: `${blurbs["svrf"]["fairground"]}`},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: `${blurbs["svrf"]["refreshing"]}`},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: `${blurbs["svrf"]["satisfying"]}`},
{brand: "svrf", shelfName: "Stimulating", product: "stimulating", blurb: `${blurbs["svrf"]["stimulating"]}`},
{brand: "svrf", shelfName: "Boba Dewwy", product: "bobadewwy", blurb: `${blurbs["svrf"]["bobadewwy"]}`},
{brand: "svrf", shelfName: "Boba Jazzy", product: "bobajazzy", blurb: `${blurbs["svrf"]["bobajazzy"]}`},
{brand: "svrf", shelfName: "Boba Manggo", product: "bobamanggo", blurb: `${blurbs["svrf"]["bobamanggo"]}`},
];
let saltInventory = [
{brand: "humble", shelfName: " ", product: "logo", blurb: " "},
{brand: "humble", shelfName: "Crumble", product: "crumble", blurb: `${blurbs["humble"]["crumble"]}`},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "PB Strawberry", product: "pbstrawberry", blurb: `${blurbs["jammonster"]["pbstrawberry"]}`},
{brand: "jammonster", shelfName: "Melon Colada", product: "meloncolada", blurb: `${blurbs["jammonster"]["meloncolada"]}`},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: `${blurbs["jammonster"]["raspberry"]}`},
{brand: "jammonster", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: `${blurbs["jammonster"]["vanillacustard"]}`},
{brand: "californiagrown", shelfName: " ", product: "logo", blurb: " "},
{brand: "californiagrown", shelfName: "Grizzly Apple cool", product: "grizzlyapplecool", blurb: `${blurbs["californiagrown"]["grizzlyapplecool"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: `${blurbs["lemontwist"]["icedpinkpunchlemonade"]}`},
{brand: "lemontwist", shelfName: "Pink Punch Lemonade", product: "pinkpunchlemonade", blurb: `${blurbs["lemontwist"]["pinkpunchlemonade"]}`},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: `${blurbs["lemontwist"]["watermelonmadness"]}`},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: `${blurbs["lemontwist"]["watermelonmadness"]}`},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Fuji", product: "fuji", blurb: `${blurbs["pachamama"]["fuji"]}`},
{brand: "pachamama", shelfName: "Icy Mango", product: "icymango", blurb: `${blurbs["pachamama"]["icymango"]}`},
{brand: "pachamama", shelfName: "Strawberry Watermelon", product: "strawberrywatermelon", blurb: `${blurbs["pachamama"]["strawberrywatermelon"]}`},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Savage Patch", product: "savagepatch", blurb: `${blurbs["podjuice"]["savagepatch"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Smooth Tobacco", product: "smoothtobacco", blurb: `${blurbs["riverreserve"]["smoothtobacco"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: `${blurbs["svrf"]["balanced"]}`},
{brand: "svrf", shelfName: "Fairgrounds", product: "fairgrounds", blurb: `${blurbs["svrf"]["fairgrounds"]}`},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: `${blurbs["svrf"]["pacificsangha"]}`},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: `${blurbs["svrf"]["refreshing"]}`},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Blue Jam Cookie", product: "bluejamcookie", blurb: `${blurbs["sadboy"]["bluejamcookie"]}`},
{brand: "sadboy", shelfName: "Custard Cookie", product: "custardcookie", blurb: `${blurbs["sadboy"]["custardcookie"]}`},
{brand: "sadboy", shelfName: "Mango Blood", product: "mangoblood", blurb: `${blurbs["sadboy"]["mangoblood"]}`},
{brand: "sadboy", shelfName: "Punch Berry Blood", product: "punchberryblood", blurb: `${blurbs["sadboy"]["punchberryblood"]}`},
{brand: "sadboy", shelfName: "Punch Berry Ice", product: "punchberryice", blurb: `${blurbs["sadboy"]["punchberryice"]}`},
{brand: "sadboy", shelfName: "Straw Jam Cookie", product: "strawjamcookie", blurb: `${blurbs["sadboy"]["strawjamcookie"]}`},
{brand: "sadboy", shelfName: "Strawberry Ice", product: "strawberryice", blurb: `${blurbs["sadboy"]["strawberryice"]}`},
{brand: "shijinvapor", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijinvapor", shelfName: "Phoenix", product: "phoenix", blurb: `${blurbs["shijinvapor"]["phoenix"]}`},
{brand: "shijinvapor", shelfName: "Tortoise", product: "tortoise", blurb: `${blurbs["shijinvapor"]["tortoise"]}`},
{brand: "shijinvapor", shelfName: "Tortoise Ice", product: "tortoiseice", blurb: `${blurbs["shijinvapor"]["tortoiseice"]}`},
{brand: "skwezed", shelfName: " ", product: "logo", blurb: " "},
{brand: "skwezed", shelfName: "Lychee", product: "lychee", blurb: `${blurbs["skwezed"]["lychee"]}`},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Banana Dragonberry", product: "bananadragonberry", blurb: `${blurbs["solace"]["bananadragonberry"]}`},
{brand: "solace", shelfName: "Blues Mango", product: "bluesmango", blurb: `${blurbs["solace"]["bluesmango"]}`},
{brand: "solace", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: `${blurbs["solace"]["boldtobacco"]}`},
{brand: "solace", shelfName: "Grape", product: "grape", blurb: `${blurbs["solace"]["grape"]}`},
{brand: "solace", shelfName: "Mint", product: "mint", blurb: `${blurbs["solace"]["mint"]}`},
{brand: "solace", shelfName: "Pineapple", product: "pineapple", blurb: `${blurbs["solace"]["pineapple"]}`},
{brand: "solace", shelfName: "Strawberry Kiwi Ice", product: "strawberrykiwiice", blurb: `${blurbs["solace"]["strawberrykiwiice"]}`},
{brand: "vapetasia", shelfName: " ", product: "logo", blurb: " "},
{brand: "vapetasia", shelfName: "Killer Kustard", product: "killerkustard", blurb: `${blurbs["vapetasia"]["killerkustard"]}`},
{brand: "yogi", shelfName: " ", product: "logo", blurb: " "},
{brand: "yogi", shelfName: "Blueberry Granola", product: "blueberrygranola", blurb: `${blurbs["yogi"]["blueberrygranola"]}`},
{brand: "yogi", shelfName: "Strawberry Granola", product: "strawberrygranola", blurb: `${blurbs["yogi"]["strawberrygranola"]}`},
];


let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
