let inventory = [
	




{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: "Strawberry and blueberry."},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: "Blue raspberry taffy"},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: "Also available in menthol."},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: "Nutmeg, cinnamon, glaze, and pastry."},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: "Smooth vanilla custard."},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: "Mango taffy candy"},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: "Mango taffy candy, featuring menthol."},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: "Watermelon and honeydew taffy."},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: "Watermelon and honeydew taffy featuing menthol."},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: "A pool of 'mysterious berries.'"},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: "Kiwi, strawberry, menthol."},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple", product: "grapeapple", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple Iced", product: "grapeappleiced", blurb: "With menthol."},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Strawberry Iced", product: "grapestrawberryiced", blurb: "With menthol."},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz Iced", product: "peachbluerazziced", blurb: "With menthol."},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: " "},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon Iced", product: "strawberrylemoniced", blurb: "With menthol."},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: " "},
{brand: "cloudnurdz", shelfName: "Watermelon Apple Iced", product: "watermelonappleiced", blurb: "With menthol."},
{brand: "cyber", shelfName: " ", product: "logo", blurb: " "},
{brand: "cyber", shelfName: "Banana Nut Bread", product: "banananutbread", blurb: "undefined"},
{brand: "cyber", shelfName: "Blue Ox", product: "blueox", blurb: "undefined"},
{brand: "cyber", shelfName: "Cafe Royale", product: "caferoyale", blurb: "undefined"},
{brand: "cyber", shelfName: "Cereal Vapor", product: "cerealvapor", blurb: "undefined"},
{brand: "cyber", shelfName: "Cipher Jax", product: "cipherjax", blurb: "undefined"},
{brand: "cyber", shelfName: "Clouds of Cream", product: "cloudsofcream", blurb: "undefined"},
{brand: "cyber", shelfName: "Cyborg Plasma", product: "cyborgplasma", blurb: "undefined"},
{brand: "cyber", shelfName: "Droid Dropz", product: "droiddropz", blurb: "undefined"},
{brand: "cyber", shelfName: "Elysian Fields", product: "elysianfields", blurb: "undefined"},
{brand: "cyber", shelfName: "Klone Berries", product: "kloneberries", blurb: "undefined"},
{brand: "cyber", shelfName: "Red Tide", product: "redtide", blurb: "undefined"},
{brand: "cyber", shelfName: "Supernova", product: "supernova", blurb: "undefined"},
{brand: "cyber", shelfName: "Vader", product: "vader", blurb: "undefined"},
{brand: "cyber", shelfName: "Cipher Jax", product: "cipherjax", blurb: "undefined"},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: "Pink lemonade with menthol."},
{brand: "lemontwist", shelfName: "Peach Blossom", product: "peachblossom", blurb: "undefined"},
{brand: "lemontwist", shelfName: "Pink Punch", product: "pinkpunch", blurb: "undefined"},
{brand: "lemontwist", shelfName: "Purple Grape", product: "purplegrape", blurb: "undefined"},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: "Bold tobacco with a hint of something sweet."},
{brand: "naked", shelfName: "Euro Gold", product: "eurogold", blurb: "Natural tobacco with vanilla custard."},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: "Passion fruit, orange, and guava."},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: "Strawberry, pineapple, and coconut."},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: "Blue raspberry with a hint of lemon."},
{brand: "naked", shelfName: "Menthol Polar Breeze", product: "mentholpolarbreeze", blurb: "undefined"},
{brand: "naked", shelfName: "Menthol Very Cool", product: "mentholverycool", blurb: "undefined"},
{brand: "northwestfinest", shelfName: " ", product: "logo", blurb: " "},
{brand: "northwestfinest", shelfName: "Arctic Seas", product: "arcticseas", blurb: "undefined"},
{brand: "northwestfinest", shelfName: "Rockin Seas", product: "rockinseas", blurb: "undefined"},
{brand: "northwestfinest", shelfName: "Sour Seas", product: "sourseas", blurb: "undefined"},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: "An icy cold hit to the back of your throat."},
{brand: "pnw", shelfName: "Arctic Tobacco", product: "arctictobacco", blurb: "Bold tobacco and menthol."},
{brand: "pnw", shelfName: "Blueberry Muffin", product: "blueberrymuffin", blurb: "Blueberries and vanilla muffin."},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: " "},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: "Just like the cereal"},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: "Sweet fruity cereal and milk."},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: "Soft vanilla cake batter."},
{brand: "pnw", shelfName: "NW", product: "nw", blurb: "undefined"},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: "Peaches and menthol"},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: "Also available in menthol."},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: "Menthol and mint leaf."},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: "Soft vanilla, hazelnut and coffee."},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Acid Worm", product: "acidworm", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: "Tobacco with blackberry custard."},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: "Blackberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: "Blue raspberry fruit punch."},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: "Caramel apple custard."},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: "Caramel, hazelnut, and marshmallows."},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: "Coconut, watermelon, and mango."},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: "Mango pomegranate lemonade."},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: "Graham crackers and caramel adorned with shaved almonds, Kentucky bourbon and a splash of coconut cream."},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: "Fruit punch!"},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: "Whipped cream with tart lemon."},
{brand: "riverreserve", shelfName: "Marshmallow Custard", product: "marshmallowcustard", blurb: "Marshmallow custard."},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: "Just like those little rootbeer barrel candies."},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: " "},
{brand: "riverreserve", shelfName: "Pebbles Cheesecake", product: "pebblescheesecake", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: " "},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: "Raspberry and lemon."},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: "Pineapple coconut rum."},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: "Strawberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: "Whipped cream with strawberry and banana."},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: "Strawberries mixed with sweet vanilla custard."},
{brand: "riverreserve", shelfName: "Sweet Cream Butterscotch", product: "sweetcreambutterscotch", blurb: " "},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: "Strawberry and coconut."},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: "Tobacco with vanilla custard."},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: "Vanilla graham cracker with a brown sugar dusting."},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: "A scoop of vanilla ice cream atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: "Watermelon fruit punch with menthol."},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: "Watermelon and kiwi."},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Blueberry Custard", product: "blueberrycustard", blurb: "undefined"},
{brand: "ruthless", shelfName: "Pudding Custard", product: "puddingcustard", blurb: "undefined"},
{brand: "ruthless", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: "undefined"},
{brand: "ruthless", shelfName: "Antidote On Ice", product: "antidoteonice", blurb: "Peach, mango, blue raspberry menthol."},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: "Strawberry watermelon."},
{brand: "ruthless", shelfName: "Ez Duz It On Ice", product: "ezduzitonice", blurb: "Strawberry watermelon and menthol."},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: "Grape soda."},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: "Grape soda with menthol."},
{brand: "ruthless", shelfName: "Jungle Fever", product: "junglefever", blurb: "Pineapple, mango, citrus."},
{brand: "ruthless", shelfName: "Paradize", product: "paradize", blurb: "Passion fruit, pear, and peaches."},
{brand: "ruthless", shelfName: "Rage", product: "rage", blurb: "Apple mango."},
{brand: "ruthless", shelfName: "Skir Skirr On Ice", product: "skirskirronice", blurb: "Honeydew melon, green apple, menthol."},
{brand: "ruthless", shelfName: "Slurricane", product: "slurricane", blurb: "Peach, papaya, and guava."},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: "Raspberry, kiwi, and strawberry."},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: "Sour candy apple."},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: "Guava and mixed berries."},
{brand: "ruthless", shelfName: "Rewind Flake", product: "rewindflake", blurb: "undefined"},
{brand: "ruthless", shelfName: "Rewind Jacked", product: "rewindjacked", blurb: "undefined"},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon Cloud", product: "dragoncloud", blurb: "Cinnamon, sugar, vanilla ice cream, all on a savory pastry."},
{brand: "shijin", shelfName: "Frozen Limeade", product: "frozenlimeade", blurb: "undefined"},
{brand: "shijin", shelfName: "Phoenix Tears", product: "phoenixtears", blurb: "Sugar cookie with vanilla custard."},
{brand: "shijin", shelfName: "Tigers Milk", product: "tigersmilk", blurb: "Mangoes and peaches."},
{brand: "shijin", shelfName: "Tortoise Blood", product: "tortoiseblood", blurb: "Green apple, blue raspberry."},
{brand: "shijin", shelfName: "Tortoise on Ice", product: "tortoiseonice", blurb: "Green apple, blue raspberry with menthol."},
{brand: "silverback", shelfName: " ", product: "logo", blurb: " "},
{brand: "silverback", shelfName: "BooBoo", product: "booboo", blurb: "Grape and blueberry."},
{brand: "silverback", shelfName: "Harambe", product: "harambe", blurb: "Cinnamon and cream liqueur."},
{brand: "silverback", shelfName: "Jenny", product: "jenny", blurb: "Strawberry, bubblegum, mint."},
{brand: "silverback", shelfName: "Lola", product: "lola", blurb: "Strawberry, banana, dragonfruit."},
{brand: "silverback", shelfName: "Sandy", product: "sandy", blurb: "Strawberry watermelon."},
{brand: "stashreprise", shelfName: " ", product: "logo", blurb: " "},
{brand: "stashreprise", shelfName: "Bliss", product: "bliss", blurb: "undefined"},
{brand: "stashreprise", shelfName: "Blue Sky", product: "bluesky", blurb: "undefined"},
{brand: "stashreprise", shelfName: "Chilly Water", product: "chillywater", blurb: "undefined"},
{brand: "stashreprise", shelfName: "Farmhouse", product: "farmhouse", blurb: "undefined"},
{brand: "stashreprise", shelfName: "Fluffhead", product: "fluffhead", blurb: "undefined"},
{brand: "stashreprise", shelfName: "Funkin Gonuts", product: "funkingonuts", blurb: "undefined"},
{brand: "stashreprise", shelfName: "Golden Road", product: "goldenroad", blurb: "undefined"},
{brand: "stashreprise", shelfName: "Sleeping Monkey", product: "sleepingmonkey", blurb: "undefined"},
{brand: "stashreprise", shelfName: "Soulshine", product: "soulshine", blurb: "undefined"},
{brand: "stashreprise", shelfName: "Vacation", product: "vacation", blurb: "undefined"},

];

let saltInventory = [
	

{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: "Strawberry and blueberry."},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: "Blue raspberry taffy"},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: "Also available in menthol."},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: "Nutmeg, cinnamon, glaze, and pastry."},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: "Smooth vanilla custard."},
{brand: "airfactory", shelfName: "Custard Tobacco", product: "custardtobacco", blurb: "Smooth vanilla custard with tobacco."},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: "Mango taffy candy"},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: "Mango taffy candy, featuring menthol."},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: "Watermelon and honeydew taffy."},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: "Watermelon and honeydew taffy featuing menthol."},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: "Probably closer to mint, but that's okay."},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: "Mintier than menthol."},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: "A pool of 'mysterious berries.'"},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "airfactory", shelfName: "Tobacco", product: "tobacco", blurb: "undefined"},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: "Kiwi, strawberry, menthol."},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Watermelon Burst", product: "watermelonburst", blurb: "undefined"},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Royal Tobacco", product: "royaltobacco", blurb: "undefined"},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Antidote on Ice", product: "antidoteonice", blurb: "Peach, mango, blue raspberry menthol."},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: "Strawberry watermelon."},
{brand: "ruthless", shelfName: "Ez Duz It on Ice", product: "ezduzitonice", blurb: "Strawberry watermelon and menthol."},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: "Grape soda."},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: "Grape soda with menthol."},
{brand: "ruthless", shelfName: "Paradise", product: "paradise", blurb: "Passion fruit, pear, and peaches."},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: "Raspberry, kiwi, and strawberry."},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: "Guava and mixed berries."},

];

let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
