
let inventory = [
{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: `${blurbs["airfactory"]["berryrush"]}`},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: `${blurbs["airfactory"]["bluerazz"]}`},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: `${blurbs["airfactory"]["bluerazzice"]}`},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: `${blurbs["airfactory"]["creamycrunch"]}`},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: `${blurbs["airfactory"]["custard"]}`},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: `${blurbs["airfactory"]["mango"]}`},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: `${blurbs["airfactory"]["mangoice"]}`},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: `${blurbs["airfactory"]["melonlush"]}`},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: `${blurbs["airfactory"]["melonlushice"]}`},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: `${blurbs["airfactory"]["mixedberry"]}`},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["airfactory"]["strawberrykiwi"]}`},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: `${blurbs["airfactory"]["tropicfreeze"]}`},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple", product: "grapeapple", blurb: `${blurbs["cloudnurdz"]["grapeapple"]}`},
{brand: "cloudnurdz", shelfName: "Grape Apple Iced", product: "grapeappleiced", blurb: `${blurbs["cloudnurdz"]["grapeappleiced"]}`},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: `${blurbs["cloudnurdz"]["grapestrawberry"]}`},
{brand: "cloudnurdz", shelfName: "Grape Strawberry Iced", product: "grapestrawberryiced", blurb: `${blurbs["cloudnurdz"]["grapestrawberryiced"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: `${blurbs["cloudnurdz"]["peachbluerazz"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz Iced", product: "peachbluerazziced", blurb: `${blurbs["cloudnurdz"]["peachbluerazziced"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: `${blurbs["cloudnurdz"]["strawberrylemon"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon Iced", product: "strawberrylemoniced", blurb: `${blurbs["cloudnurdz"]["strawberrylemoniced"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: `${blurbs["cloudnurdz"]["watermelonapple"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple Iced", product: "watermelonappleiced", blurb: `${blurbs["cloudnurdz"]["watermelonappleiced"]}`},
{brand: "cyber", shelfName: " ", product: "logo", blurb: " "},
{brand: "cyber", shelfName: "Banana Nut Bread", product: "banananutbread", blurb: `${blurbs["cyber"]["banananutbread"]}`},
{brand: "cyber", shelfName: "Blue Ox", product: "blueox", blurb: `${blurbs["cyber"]["blueox"]}`},
{brand: "cyber", shelfName: "Cafe Royale", product: "caferoyale", blurb: `${blurbs["cyber"]["caferoyale"]}`},
{brand: "cyber", shelfName: "Cereal Vapor", product: "cerealvapor", blurb: `${blurbs["cyber"]["cerealvapor"]}`},
{brand: "cyber", shelfName: "Cipher Jax", product: "cipherjax", blurb: `${blurbs["cyber"]["cipherjax"]}`},
{brand: "cyber", shelfName: "Clouds of Cream", product: "cloudsofcream", blurb: `${blurbs["cyber"]["cloudsofcream"]}`},
{brand: "cyber", shelfName: "Cyborg Plasma", product: "cyborgplasma", blurb: `${blurbs["cyber"]["cyborgplasma"]}`},
{brand: "cyber", shelfName: "Droid Dropz", product: "droiddropz", blurb: `${blurbs["cyber"]["droiddropz"]}`},
{brand: "cyber", shelfName: "Elysian Fields", product: "elysianfields", blurb: `${blurbs["cyber"]["elysianfields"]}`},
{brand: "cyber", shelfName: "Klone Berries", product: "kloneberries", blurb: `${blurbs["cyber"]["kloneberries"]}`},
{brand: "cyber", shelfName: "Red Tide", product: "redtide", blurb: `${blurbs["cyber"]["redtide"]}`},
{brand: "cyber", shelfName: "Supernova", product: "supernova", blurb: `${blurbs["cyber"]["supernova"]}`},
{brand: "cyber", shelfName: "Vader", product: "vader", blurb: `${blurbs["cyber"]["vader"]}`},
{brand: "cyber", shelfName: "Cipher Jax", product: "cipherjax", blurb: `${blurbs["cyber"]["cipherjax"]}`},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: `${blurbs["lemontwist"]["icedpinkpunchlemonade"]}`},
{brand: "lemontwist", shelfName: "Peach Blossom", product: "peachblossom", blurb: `${blurbs["lemontwist"]["peachblossom"]}`},
{brand: "lemontwist", shelfName: "Pink Punch", product: "pinkpunch", blurb: `${blurbs["lemontwist"]["pinkpunch"]}`},
{brand: "lemontwist", shelfName: "Purple Grape", product: "purplegrape", blurb: `${blurbs["lemontwist"]["purplegrape"]}`},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: `${blurbs["naked"]["americanpatriot"]}`},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: `${blurbs["naked"]["cubanblend"]}`},
{brand: "naked", shelfName: "Euro Gold", product: "eurogold", blurb: `${blurbs["naked"]["eurogold"]}`},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: `${blurbs["naked"]["hawaiianpog"]}`},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: `${blurbs["naked"]["lavaflow"]}`},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: `${blurbs["naked"]["reallyberryveryberry"]}`},
{brand: "naked", shelfName: "Menthol Polar Breeze", product: "mentholpolarbreeze", blurb: `${blurbs["naked"]["mentholpolarbreeze"]}`},
{brand: "naked", shelfName: "Menthol Very Cool", product: "mentholverycool", blurb: `${blurbs["naked"]["mentholverycool"]}`},
{brand: "northwestfinest", shelfName: " ", product: "logo", blurb: " "},
{brand: "northwestfinest", shelfName: "Arctic Seas", product: "arcticseas", blurb: `${blurbs["northwestfinest"]["arcticseas"]}`},
{brand: "northwestfinest", shelfName: "Rockin Seas", product: "rockinseas", blurb: `${blurbs["northwestfinest"]["rockinseas"]}`},
{brand: "northwestfinest", shelfName: "Sour Seas", product: "sourseas", blurb: `${blurbs["northwestfinest"]["sourseas"]}`},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: `${blurbs["pnw"]["arcticfrost"]}`},
{brand: "pnw", shelfName: "Arctic Tobacco", product: "arctictobacco", blurb: `${blurbs["pnw"]["arctictobacco"]}`},
{brand: "pnw", shelfName: "Blueberry Muffin", product: "blueberrymuffin", blurb: `${blurbs["pnw"]["blueberrymuffin"]}`},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: `${blurbs["pnw"]["cherrylimeade"]}`},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: `${blurbs["pnw"]["cinnamoncrunch"]}`},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: `${blurbs["pnw"]["fruityos"]}`},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: `${blurbs["pnw"]["madbatter"]}`},
{brand: "pnw", shelfName: "NW", product: "nw", blurb: `${blurbs["pnw"]["nw"]}`},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: `${blurbs["pnw"]["peachfrost"]}`},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: `${blurbs["pnw"]["peaches"]}`},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: `${blurbs["pnw"]["spearmint"]}`},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: `${blurbs["pnw"]["vanillanutlatte"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Acid Worm", product: "acidworm", blurb: `${blurbs["riverreserve"]["acidworm"]}`},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: `${blurbs["riverreserve"]["bandit"]}`},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: `${blurbs["riverreserve"]["blackberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: `${blurbs["riverreserve"]["blueislandpunch"]}`},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: `${blurbs["riverreserve"]["caramelappledrifter"]}`},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: `${blurbs["riverreserve"]["caramelcove"]}`},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: `${blurbs["riverreserve"]["castaway"]}`},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: `${blurbs["riverreserve"]["eddy"]}`},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: `${blurbs["riverreserve"]["greatwall"]}`},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: `${blurbs["riverreserve"]["islandpunch"]}`},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: `${blurbs["riverreserve"]["lemondrifter"]}`},
{brand: "riverreserve", shelfName: "Marshmallow Custard", product: "marshmallowcustard", blurb: `${blurbs["riverreserve"]["marshmallowcustard"]}`},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: `${blurbs["riverreserve"]["oldwolf"]}`},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: `${blurbs["riverreserve"]["peachmangolemonade"]}`},
{brand: "riverreserve", shelfName: "Pebbles Cheesecake", product: "pebblescheesecake", blurb: `${blurbs["riverreserve"]["pebblescheesecake"]}`},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: `${blurbs["riverreserve"]["pineapplegrapementhol"]}`},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: `${blurbs["riverreserve"]["raspberrycrumble"]}`},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: `${blurbs["riverreserve"]["raspberrylemonitalianice"]}`},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: `${blurbs["riverreserve"]["rivercolada"]}`},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: `${blurbs["riverreserve"]["strawberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: `${blurbs["riverreserve"]["strawnanadrifter"]}`},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: `${blurbs["riverreserve"]["swampmama"]}`},
{brand: "riverreserve", shelfName: "Sweet Cream Butterscotch", product: "sweetcreambutterscotch", blurb: `${blurbs["riverreserve"]["sweetcreambutterscotch"]}`},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: `${blurbs["riverreserve"]["tigersblood"]}`},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: `${blurbs["riverreserve"]["vanillabandit"]}`},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: `${blurbs["riverreserve"]["vanillagraham"]}`},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: `${blurbs["riverreserve"]["vanillawafflecone"]}`},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: `${blurbs["riverreserve"]["watermelonpunchmenthol"]}`},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: `${blurbs["riverreserve"]["wiki"]}`},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Blueberry Custard", product: "blueberrycustard", blurb: `${blurbs["ruthless"]["blueberrycustard"]}`},
{brand: "ruthless", shelfName: "Pudding Custard", product: "puddingcustard", blurb: `${blurbs["ruthless"]["puddingcustard"]}`},
{brand: "ruthless", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: `${blurbs["ruthless"]["vanillacustard"]}`},
{brand: "ruthless", shelfName: "Antidote On Ice", product: "antidoteonice", blurb: `${blurbs["ruthless"]["antidoteonice"]}`},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: `${blurbs["ruthless"]["ezduzit"]}`},
{brand: "ruthless", shelfName: "Ez Duz It On Ice", product: "ezduzitonice", blurb: `${blurbs["ruthless"]["ezduzitonice"]}`},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: `${blurbs["ruthless"]["grapedrank"]}`},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: `${blurbs["ruthless"]["grapedrankonice"]}`},
{brand: "ruthless", shelfName: "Jungle Fever", product: "junglefever", blurb: `${blurbs["ruthless"]["junglefever"]}`},
{brand: "ruthless", shelfName: "Paradize", product: "paradize", blurb: `${blurbs["ruthless"]["paradize"]}`},
{brand: "ruthless", shelfName: "Rage", product: "rage", blurb: `${blurbs["ruthless"]["rage"]}`},
{brand: "ruthless", shelfName: "Skir Skirr On Ice", product: "skirskirronice", blurb: `${blurbs["ruthless"]["skirskirronice"]}`},
{brand: "ruthless", shelfName: "Slurricane", product: "slurricane", blurb: `${blurbs["ruthless"]["slurricane"]}`},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: `${blurbs["ruthless"]["strizzy"]}`},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: `${blurbs["ruthless"]["swampthang"]}`},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: `${blurbs["ruthless"]["tropicthunda"]}`},
{brand: "ruthless", shelfName: "Rewind Flake", product: "rewindflake", blurb: `${blurbs["ruthless"]["rewindflake"]}`},
{brand: "ruthless", shelfName: "Rewind Jacked", product: "rewindjacked", blurb: `${blurbs["ruthless"]["rewindjacked"]}`},
{brand: "silverback", shelfName: " ", product: "logo", blurb: " "},
{brand: "silverback", shelfName: "BooBoo", product: "booboo", blurb: `${blurbs["silverback"]["booboo"]}`},
{brand: "silverback", shelfName: "Harambe", product: "harambe", blurb: `${blurbs["silverback"]["harambe"]}`},
{brand: "silverback", shelfName: "Jenny", product: "jenny", blurb: `${blurbs["silverback"]["jenny"]}`},
{brand: "silverback", shelfName: "Lola", product: "lola", blurb: `${blurbs["silverback"]["lola"]}`},
{brand: "silverback", shelfName: "Sandy", product: "sandy", blurb: `${blurbs["silverback"]["sandy"]}`},
{brand: "stashreprise", shelfName: " ", product: "logo", blurb: " "},
{brand: "stashreprise", shelfName: "Bliss", product: "bliss", blurb: `${blurbs["stashreprise"]["bliss"]}`},
{brand: "stashreprise", shelfName: "Blue Sky", product: "bluesky", blurb: `${blurbs["stashreprise"]["bluesky"]}`},
{brand: "stashreprise", shelfName: "Chilly Water", product: "chillywater", blurb: `${blurbs["stashreprise"]["chillywater"]}`},
{brand: "stashreprise", shelfName: "Farmhouse", product: "farmhouse", blurb: `${blurbs["stashreprise"]["farmhouse"]}`},
{brand: "stashreprise", shelfName: "Fluffhead", product: "fluffhead", blurb: `${blurbs["stashreprise"]["fluffhead"]}`},
{brand: "stashreprise", shelfName: "Funkin Gonuts", product: "funkingonuts", blurb: `${blurbs["stashreprise"]["funkingonuts"]}`},
{brand: "stashreprise", shelfName: "Golden Road", product: "goldenroad", blurb: `${blurbs["stashreprise"]["goldenroad"]}`},
{brand: "stashreprise", shelfName: "Sleeping Monkey", product: "sleepingmonkey", blurb: `${blurbs["stashreprise"]["sleepingmonkey"]}`},
{brand: "stashreprise", shelfName: "Soulshine", product: "soulshine", blurb: `${blurbs["stashreprise"]["soulshine"]}`},
{brand: "stashreprise", shelfName: "Vacation", product: "vacation", blurb: `${blurbs["stashreprise"]["vacation"]}`},
];
let saltInventory = [
{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: `${blurbs["airfactory"]["berryrush"]}`},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: `${blurbs["airfactory"]["bluerazz"]}`},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: `${blurbs["airfactory"]["bluerazzice"]}`},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: `${blurbs["airfactory"]["creamycrunch"]}`},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: `${blurbs["airfactory"]["custard"]}`},
{brand: "airfactory", shelfName: "Custard Tobacco", product: "custardtobacco", blurb: `${blurbs["airfactory"]["custardtobacco"]}`},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: `${blurbs["airfactory"]["mango"]}`},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: `${blurbs["airfactory"]["mangoice"]}`},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: `${blurbs["airfactory"]["melonlush"]}`},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: `${blurbs["airfactory"]["melonlushice"]}`},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: `${blurbs["airfactory"]["menthol"]}`},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: `${blurbs["airfactory"]["mint"]}`},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: `${blurbs["airfactory"]["mixedberry"]}`},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["airfactory"]["strawberrykiwi"]}`},
{brand: "airfactory", shelfName: "Tobacco", product: "tobacco", blurb: `${blurbs["airfactory"]["tobacco"]}`},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: `${blurbs["airfactory"]["tropicfreeze"]}`},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Watermelon Burst", product: "watermelonburst", blurb: `${blurbs["podjuice"]["watermelonburst"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Royal Tobacco", product: "royaltobacco", blurb: `${blurbs["riverreserve"]["royaltobacco"]}`},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Antidote on Ice", product: "antidoteonice", blurb: `${blurbs["ruthless"]["antidoteonice"]}`},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: `${blurbs["ruthless"]["ezduzit"]}`},
{brand: "ruthless", shelfName: "Ez Duz It on Ice", product: "ezduzitonice", blurb: `${blurbs["ruthless"]["ezduzitonice"]}`},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: `${blurbs["ruthless"]["grapedrank"]}`},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: `${blurbs["ruthless"]["grapedrankonice"]}`},
{brand: "ruthless", shelfName: "Paradise", product: "paradise", blurb: `${blurbs["ruthless"]["paradise"]}`},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: `${blurbs["ruthless"]["strizzy"]}`},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: `${blurbs["ruthless"]["tropicthunda"]}`},
];


let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
