
let inventory = [
{brand: "baristabrewco", shelfName: " ", product: "logo", blurb: " "},
{brand: "baristabrewco", shelfName: "Cinnamon Glazed Blueberry Scone", product: "cinnamonglazedblueberryscone", blurb: `${blurbs["baristabrewco"]["cinnamonglazedblueberryscone"]}`},
{brand: "baristabrewco", shelfName: "Maple Bar Donut", product: "maplebardonut", blurb: `${blurbs["baristabrewco"]["maplebardonut"]}`},
{brand: "baristabrewco", shelfName: "Salted Caramel Macchiato", product: "saltedcaramelmacchiato", blurb: `${blurbs["baristabrewco"]["saltedcaramelmacchiato"]}`},
{brand: "baristabrewco", shelfName: "Smores Mocha Breeze", product: "smoresmochabreeze", blurb: `${blurbs["baristabrewco"]["smoresmochabreeze"]}`},
{brand: "californiagrown", shelfName: " ", product: "logo", blurb: " "},
{brand: "californiagrown", shelfName: "Grizzly Apple", product: "grizzlyapple", blurb: `${blurbs["californiagrown"]["grizzlyapple"]}`},
{brand: "californiagrown", shelfName: "Grizzly Apple cool", product: "grizzlyapplecool", blurb: `${blurbs["californiagrown"]["grizzlyapplecool"]}`},
{brand: "californiagrown", shelfName: "Napa Nectar", product: "napanectar", blurb: `${blurbs["californiagrown"]["napanectar"]}`},
{brand: "californiagrown", shelfName: "Napa Nectar cool", product: "napanectarcool", blurb: `${blurbs["californiagrown"]["napanectarcool"]}`},
{brand: "californiagrown", shelfName: "Wavy Watermelon", product: "wavywatermelon", blurb: `${blurbs["californiagrown"]["wavywatermelon"]}`},
{brand: "californiagrown", shelfName: "Wavy Watermelon cool", product: "wavywatermeloncool", blurb: `${blurbs["californiagrown"]["wavywatermeloncool"]}`},
{brand: "crisp", shelfName: " ", product: "logo", blurb: " "},
{brand: "crisp", shelfName: "Cider", product: "cider", blurb: `${blurbs["crisp"]["cider"]}`},
{brand: "crisp", shelfName: "Menthol", product: "menthol", blurb: `${blurbs["crisp"]["menthol"]}`},
{brand: "crisp", shelfName: "Original Red", product: "originalred", blurb: `${blurbs["crisp"]["originalred"]}`},
{brand: "drexdrips", shelfName: " ", product: "logo", blurb: " "},
{brand: "drexdrips", shelfName: "Real Talk", product: "realtalk", blurb: `${blurbs["drexdrips"]["realtalk"]}`},
{brand: "element", shelfName: " ", product: "logo", blurb: " "},
{brand: "element", shelfName: "Fresh Squeeze", product: "freshsqueeze", blurb: `${blurbs["element"]["freshsqueeze"]}`},
{brand: "element", shelfName: "Pink Grapefruit", product: "pinkgrapefruit", blurb: `${blurbs["element"]["pinkgrapefruit"]}`},
{brand: "element", shelfName: "Pink lemonade", product: "pinklemonade", blurb: `${blurbs["element"]["pinklemonade"]}`},
{brand: "freshpressed", shelfName: " ", product: "logo", blurb: " "},
{brand: "freshpressed", shelfName: "Fruit Finale", product: "fruitfinale", blurb: `${blurbs["freshpressed"]["fruitfinale"]}`},
{brand: "freshpressed", shelfName: "HoneyComb Berry", product: "honeycombberry", blurb: `${blurbs["freshpressed"]["honeycombberry"]}`},
{brand: "freshpressed", shelfName: "Lava Luau", product: "lavaluau", blurb: `${blurbs["freshpressed"]["lavaluau"]}`},
{brand: "freshpressed", shelfName: "Pressed Pink Melon", product: "pressedpinkmelon", blurb: `${blurbs["freshpressed"]["pressedpinkmelon"]}`},
{brand: "freshpressed", shelfName: "Sugar Tantrum", product: "sugartantrum", blurb: `${blurbs["freshpressed"]["sugartantrum"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: `${blurbs["juicehead"]["blueberrylemon"]}`},
{brand: "juicehead", shelfName: "Blueberry Lemon Freeze", product: "blueberrylemonfreeze", blurb: `${blurbs["juicehead"]["blueberrylemonfreeze"]}`},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: `${blurbs["juicehead"]["guavapeach"]}`},
{brand: "juicehead", shelfName: "Guava Peach Ice", product: "guavapeachice", blurb: `${blurbs["juicehead"]["guavapeachice"]}`},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: `${blurbs["juicehead"]["peachpear"]}`},
{brand: "juicehead", shelfName: "Peach Pear Freeze", product: "peachpearfreeze", blurb: `${blurbs["juicehead"]["peachpearfreeze"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit Freeze", product: "pineapplegrapefruitfreeze", blurb: `${blurbs["juicehead"]["pineapplegrapefruitfreeze"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi Freeze", product: "strawberrykiwifreeze", blurb: `${blurbs["juicehead"]["strawberrykiwifreeze"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: `${blurbs["juicehead"]["watermelonlime"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: `${blurbs["juicehead"]["watermelonlimefreeze"]}`},
{brand: "loyalty", shelfName: " ", product: "logo", blurb: " "},
{brand: "loyalty", shelfName: "Double Shot", product: "doubleshot", blurb: `${blurbs["loyalty"]["doubleshot"]}`},
{brand: "loyalty", shelfName: "Ki Berry", product: "kiberry", blurb: `${blurbs["loyalty"]["kiberry"]}`},
{brand: "loyalty", shelfName: "Melon Ade Ice", product: "melonadeice", blurb: `${blurbs["loyalty"]["melonadeice"]}`},
{brand: "loyalty", shelfName: "PomNAde Ice", product: "pomnadeice", blurb: `${blurbs["loyalty"]["pomnadeice"]}`},
{brand: "loyalty", shelfName: "Wata Mango", product: "watamango", blurb: `${blurbs["loyalty"]["watamango"]}`},
{brand: "mamasan", shelfName: " ", product: "logo", blurb: " "},
{brand: "mamasan", shelfName: "ASAP", product: "asap", blurb: `${blurbs["mamasan"]["asap"]}`},
{brand: "mamasan", shelfName: "Bruce Leechee", product: "bruceleechee", blurb: `${blurbs["mamasan"]["bruceleechee"]}`},
{brand: "mamasan", shelfName: "Guava Pop", product: "guavapop", blurb: `${blurbs["mamasan"]["guavapop"]}`},
{brand: "mamasan", shelfName: "Mama Melon", product: "mamamelon", blurb: `${blurbs["mamasan"]["mamamelon"]}`},
{brand: "mamasan", shelfName: "Purple Cheesecake", product: "purplecheesecake", blurb: `${blurbs["mamasan"]["purplecheesecake"]}`},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: `${blurbs["naked"]["americanpatriot"]}`},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: `${blurbs["naked"]["cubanblend"]}`},
{brand: "naked", shelfName: "Euro Gold", product: "eurogold", blurb: `${blurbs["naked"]["eurogold"]}`},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: `${blurbs["naked"]["reallyberryveryberry"]}`},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: `${blurbs["pnw"]["arcticfrost"]}`},
{brand: "pnw", shelfName: "Arctic Tobacco", product: "arctictobacco", blurb: `${blurbs["pnw"]["arctictobacco"]}`},
{brand: "pnw", shelfName: "Blueberry Muffin", product: "blueberrymuffin", blurb: `${blurbs["pnw"]["blueberrymuffin"]}`},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: `${blurbs["pnw"]["cherrylimeade"]}`},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: `${blurbs["pnw"]["cinnamoncrunch"]}`},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: `${blurbs["pnw"]["fruityos"]}`},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: `${blurbs["pnw"]["madbatter"]}`},
{brand: "pnw", shelfName: "NW", product: "nw", blurb: `${blurbs["pnw"]["nw"]}`},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: `${blurbs["pnw"]["peachfrost"]}`},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: `${blurbs["pnw"]["peaches"]}`},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: `${blurbs["pnw"]["spearmint"]}`},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: `${blurbs["pnw"]["vanillanutlatte"]}`},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Blood Orange Banana Gooseberry", product: "bloodorangebananagooseberry", blurb: `${blurbs["pachamama"]["bloodorangebananagooseberry"]}`},
{brand: "pachamama", shelfName: "Fuji Apple Strawberry Nectarine", product: "fujiapplestrawberrynectarine", blurb: `${blurbs["pachamama"]["fujiapplestrawberrynectarine"]}`},
{brand: "pachamama", shelfName: "Honeydew Berry Kiwi", product: "honeydewberrykiwi", blurb: `${blurbs["pachamama"]["honeydewberrykiwi"]}`},
{brand: "pachamama", shelfName: "Huckleberry Pear Acai", product: "huckleberrypearacai", blurb: `${blurbs["pachamama"]["huckleberrypearacai"]}`},
{brand: "pachamama", shelfName: "Mango Pitaya Pineapple", product: "mangopitayapineapple", blurb: `${blurbs["pachamama"]["mangopitayapineapple"]}`},
{brand: "pachamama", shelfName: "Passion Fruit Raspberry Yuzu", product: "passionfruitraspberryyuzu", blurb: `${blurbs["pachamama"]["passionfruitraspberryyuzu"]}`},
{brand: "pachamama", shelfName: "Peach Papaya Coconut Cream", product: "peachpapayacoconutcream", blurb: `${blurbs["pachamama"]["peachpapayacoconutcream"]}`},
{brand: "pachamama", shelfName: "Strawberry Guava Jackfruit", product: "strawberryguavajackfruit", blurb: `${blurbs["pachamama"]["strawberryguavajackfruit"]}`},
{brand: "racks", shelfName: " ", product: "logo", blurb: " "},
{brand: "racks", shelfName: "Peach Mojito", product: "peachmojito", blurb: `${blurbs["racks"]["peachmojito"]}`},
{brand: "racks", shelfName: "Watermelon Mojito", product: "watermelonmojito", blurb: `${blurbs["racks"]["watermelonmojito"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Acid Worm", product: "acidworm", blurb: `${blurbs["riverreserve"]["acidworm"]}`},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: `${blurbs["riverreserve"]["bandit"]}`},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: `${blurbs["riverreserve"]["blackberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: `${blurbs["riverreserve"]["blueislandpunch"]}`},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: `${blurbs["riverreserve"]["boldtobacco"]}`},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: `${blurbs["riverreserve"]["caramelappledrifter"]}`},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: `${blurbs["riverreserve"]["caramelcove"]}`},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: `${blurbs["riverreserve"]["castaway"]}`},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: `${blurbs["riverreserve"]["clearwatercreek"]}`},
{brand: "riverreserve", shelfName: "Drifter", product: "drifter", blurb: `${blurbs["riverreserve"]["drifter"]}`},
{brand: "riverreserve", shelfName: "Drifter X", product: "drifterx", blurb: `${blurbs["riverreserve"]["drifterx"]}`},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: `${blurbs["riverreserve"]["eddy"]}`},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: `${blurbs["riverreserve"]["greatwall"]}`},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: `${blurbs["riverreserve"]["islandpunch"]}`},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: `${blurbs["riverreserve"]["lemondrifter"]}`},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: `${blurbs["riverreserve"]["midorisour"]}`},
{brand: "riverreserve", shelfName: "Mild Tobacco", product: "mildtobacco", blurb: `${blurbs["riverreserve"]["mildtobacco"]}`},
{brand: "riverreserve", shelfName: "Natural Tobacco", product: "naturaltobacco", blurb: `${blurbs["riverreserve"]["naturaltobacco"]}`},
{brand: "riverreserve", shelfName: "Northwest", product: "northwest", blurb: `${blurbs["riverreserve"]["northwest"]}`},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: `${blurbs["riverreserve"]["oldwolf"]}`},
{brand: "riverreserve", shelfName: "PBG", product: "pbg", blurb: `${blurbs["riverreserve"]["pbg"]}`},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: `${blurbs["riverreserve"]["peachmangolemonade"]}`},
{brand: "riverreserve", shelfName: "Pebbles Cheesecake", product: "pebblescheesecake", blurb: `${blurbs["riverreserve"]["pebblescheesecake"]}`},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: `${blurbs["riverreserve"]["pineapplegrapementhol"]}`},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: `${blurbs["riverreserve"]["raspberrycrumble"]}`},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: `${blurbs["riverreserve"]["raspberrylemonitalianice"]}`},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: `${blurbs["riverreserve"]["rivercolada"]}`},
{brand: "riverreserve", shelfName: "River Maiden", product: "rivermaiden", blurb: `${blurbs["riverreserve"]["rivermaiden"]}`},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: `${blurbs["riverreserve"]["smoothsweettobacco"]}`},
{brand: "riverreserve", shelfName: "Strawberry Bandit", product: "strawberrybandit", blurb: `${blurbs["riverreserve"]["strawberrybandit"]}`},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: `${blurbs["riverreserve"]["strawberrydrifter"]}`},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: `${blurbs["riverreserve"]["strawberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: `${blurbs["riverreserve"]["strawnanadrifter"]}`},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: `${blurbs["riverreserve"]["swampmama"]}`},
{brand: "riverreserve", shelfName: "Sweet Cream Butterscotch", product: "sweetcreambutterscotch", blurb: `${blurbs["riverreserve"]["sweetcreambutterscotch"]}`},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: `${blurbs["riverreserve"]["tigersblood"]}`},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: `${blurbs["riverreserve"]["vanillabandit"]}`},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: `${blurbs["riverreserve"]["vanillagraham"]}`},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: `${blurbs["riverreserve"]["vanillawafflecone"]}`},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: `${blurbs["riverreserve"]["watermelonpunchmenthol"]}`},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: `${blurbs["riverreserve"]["wiki"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balance Iced", product: "balanceiced", blurb: `${blurbs["svrf"]["balanceiced"]}`},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: `${blurbs["svrf"]["balanced"]}`},
{brand: "svrf", shelfName: "Fairground", product: "fairground", blurb: `${blurbs["svrf"]["fairground"]}`},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: `${blurbs["svrf"]["goldenticket"]}`},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: `${blurbs["svrf"]["pacificsangha"]}`},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: `${blurbs["svrf"]["refreshing"]}`},
{brand: "svrf", shelfName: "Revive Iced", product: "reviveiced", blurb: `${blurbs["svrf"]["reviveiced"]}`},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: `${blurbs["svrf"]["satisfying"]}`},
{brand: "svrf", shelfName: "Stimulating", product: "stimulating", blurb: `${blurbs["svrf"]["stimulating"]}`},
{brand: "svrf", shelfName: "Boba Dewwy", product: "bobadewwy", blurb: `${blurbs["svrf"]["bobadewwy"]}`},
{brand: "svrf", shelfName: "Boba Jazzy", product: "bobajazzy", blurb: `${blurbs["svrf"]["bobajazzy"]}`},
{brand: "svrf", shelfName: "Boba Manggo", product: "bobamanggo", blurb: `${blurbs["svrf"]["bobamanggo"]}`},
{brand: "vaporvandals", shelfName: " ", product: "logo", blurb: " "},
{brand: "vaporvandals", shelfName: "Crew", product: "crew", blurb: `${blurbs["vaporvandals"]["crew"]}`},
{brand: "vaporvandals", shelfName: "Outlaw", product: "outlaw", blurb: `${blurbs["vaporvandals"]["outlaw"]}`},
{brand: "vaporvandals", shelfName: "Purp", product: "purp", blurb: `${blurbs["vaporvandals"]["purp"]}`},
{brand: "vaporvandals", shelfName: "Skinny Dip", product: "skinnydip", blurb: `${blurbs["vaporvandals"]["skinnydip"]}`},
{brand: "vaporvandals", shelfName: "Toast", product: "toast", blurb: `${blurbs["vaporvandals"]["toast"]}`},
{brand: "yogi", shelfName: " ", product: "logo", blurb: " "},
{brand: "yogi", shelfName: "Apple Cinnamon Granola Bar", product: "applecinnamongranolabar", blurb: `${blurbs["yogi"]["applecinnamongranolabar"]}`},
{brand: "yogi", shelfName: "Blueberry Granola", product: "blueberrygranola", blurb: `${blurbs["yogi"]["blueberrygranola"]}`},
{brand: "yogi", shelfName: "Granola", product: "granola", blurb: `${blurbs["yogi"]["granola"]}`},
{brand: "yogi", shelfName: "Java Granola Bar", product: "javagranolabar", blurb: `${blurbs["yogi"]["javagranolabar"]}`},
{brand: "yogi", shelfName: "Lemon Granola Bar", product: "lemongranolabar", blurb: `${blurbs["yogi"]["lemongranolabar"]}`},
{brand: "yogi", shelfName: "Peanut Butter Banana Granola", product: "peanutbutterbananagranola", blurb: `${blurbs["yogi"]["peanutbutterbananagranola"]}`},
{brand: "yogi", shelfName: "Strawberry Granola", product: "strawberrygranola", blurb: `${blurbs["yogi"]["strawberrygranola"]}`},
{brand: "yogi", shelfName: "Vanilla Tobacco Granola Bar", product: "vanillatobaccogranolabar", blurb: `${blurbs["yogi"]["vanillatobaccogranolabar"]}`},
];
let saltInventory = [
{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: `${blurbs["airfactory"]["berryrush"]}`},
{brand: "airfactory", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: `${blurbs["airfactory"]["boldtobacco"]}`},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: `${blurbs["airfactory"]["creamycrunch"]}`},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: `${blurbs["airfactory"]["custard"]}`},
{brand: "airfactory", shelfName: "Custard Tobacco", product: "custardtobacco", blurb: `${blurbs["airfactory"]["custardtobacco"]}`},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: `${blurbs["airfactory"]["melonlush"]}`},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: `${blurbs["airfactory"]["menthol"]}`},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: `${blurbs["airfactory"]["mixedberry"]}`},
{brand: "drexdrips", shelfName: " ", product: "logo", blurb: " "},
{brand: "drexdrips", shelfName: "Berry Ice", product: "berryice", blurb: `${blurbs["drexdrips"]["berryice"]}`},
{brand: "drexdrips", shelfName: "Chill Melon", product: "chillmelon", blurb: `${blurbs["drexdrips"]["chillmelon"]}`},
{brand: "drexdrips", shelfName: "No Filter", product: "nofilter", blurb: `${blurbs["drexdrips"]["nofilter"]}`},
{brand: "drexdrips", shelfName: "On Point", product: "onpoint", blurb: `${blurbs["drexdrips"]["onpoint"]}`},
{brand: "drexdrips", shelfName: "Real Talk", product: "realtalk", blurb: `${blurbs["drexdrips"]["realtalk"]}`},
{brand: "drexdrips", shelfName: "Straw Breeze", product: "strawbreeze", blurb: `${blurbs["drexdrips"]["strawbreeze"]}`},
{brand: "drexdrips", shelfName: "That Ish", product: "thatish", blurb: `${blurbs["drexdrips"]["thatish"]}`},
{brand: "drexdrips", shelfName: "Tropi Cool", product: "tropicool", blurb: `${blurbs["drexdrips"]["tropicool"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: `${blurbs["juicehead"]["blueberrylemon"]}`},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: `${blurbs["juicehead"]["guavapeach"]}`},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: `${blurbs["juicehead"]["peachpear"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: `${blurbs["juicehead"]["watermelonlime"]}`},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Apple Tobacco", product: "appletobacco", blurb: `${blurbs["pachamama"]["appletobacco"]}`},
{brand: "pachamama", shelfName: "Fuji", product: "fuji", blurb: `${blurbs["pachamama"]["fuji"]}`},
{brand: "pachamama", shelfName: "Icy Mango", product: "icymango", blurb: `${blurbs["pachamama"]["icymango"]}`},
{brand: "pachamama", shelfName: "Sorbet", product: "sorbet", blurb: `${blurbs["pachamama"]["sorbet"]}`},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Belts Burst", product: "beltsburst", blurb: `${blurbs["podjuice"]["beltsburst"]}`},
{brand: "podjuice", shelfName: "Blue Razz Burst", product: "bluerazzburst", blurb: `${blurbs["podjuice"]["bluerazzburst"]}`},
{brand: "podjuice", shelfName: "Cotton Burst", product: "cottonburst", blurb: `${blurbs["podjuice"]["cottonburst"]}`},
{brand: "podjuice", shelfName: "Hawaiian Pod", product: "hawaiianpod", blurb: `${blurbs["podjuice"]["hawaiianpod"]}`},
{brand: "podjuice", shelfName: "Jewel Fuji Nektar", product: "jewelfujinektar", blurb: `${blurbs["podjuice"]["jewelfujinektar"]}`},
{brand: "podjuice", shelfName: "Jewel Mango LE", product: "jewelmangole", blurb: `${blurbs["podjuice"]["jewelmangole"]}`},
{brand: "podjuice", shelfName: "Jewel Mint Diamond", product: "jewelmintdiamond", blurb: `${blurbs["podjuice"]["jewelmintdiamond"]}`},
{brand: "podjuice", shelfName: "Jewel Tobacco", product: "jeweltobacco", blurb: `${blurbs["podjuice"]["jeweltobacco"]}`},
{brand: "podjuice", shelfName: "Juicy Apple", product: "juicyapple", blurb: `${blurbs["podjuice"]["juicyapple"]}`},
{brand: "podjuice", shelfName: "Loops", product: "loops", blurb: `${blurbs["podjuice"]["loops"]}`},
{brand: "podjuice", shelfName: "Melon Breeze", product: "melonbreeze", blurb: `${blurbs["podjuice"]["melonbreeze"]}`},
{brand: "podjuice", shelfName: "Peach Burst", product: "peachburst", blurb: `${blurbs["podjuice"]["peachburst"]}`},
{brand: "podjuice", shelfName: "Pink Burst", product: "pinkburst", blurb: `${blurbs["podjuice"]["pinkburst"]}`},
{brand: "podjuice", shelfName: "Savage Patch", product: "savagepatch", blurb: `${blurbs["podjuice"]["savagepatch"]}`},
{brand: "podjuice", shelfName: "Strawberry Dream", product: "strawberrydream", blurb: `${blurbs["podjuice"]["strawberrydream"]}`},
{brand: "podjuice", shelfName: "Strawberry Lemonade", product: "strawberrylemonade", blurb: `${blurbs["podjuice"]["strawberrylemonade"]}`},
{brand: "podjuice", shelfName: "Watermelon Blast", product: "watermelonblast", blurb: `${blurbs["podjuice"]["watermelonblast"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: `${blurbs["riverreserve"]["blueislandpunch"]}`},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: `${blurbs["riverreserve"]["lemondrifter"]}`},
{brand: "riverreserve", shelfName: "Saltwater Creek", product: "saltwatercreek", blurb: `${blurbs["riverreserve"]["saltwatercreek"]}`},
{brand: "riverreserve", shelfName: "Tangie", product: "tangie", blurb: `${blurbs["riverreserve"]["tangie"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: `${blurbs["svrf"]["balanced"]}`},
{brand: "svrf", shelfName: "Fairgrounds", product: "fairgrounds", blurb: `${blurbs["svrf"]["fairgrounds"]}`},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: `${blurbs["svrf"]["goldenticket"]}`},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: `${blurbs["svrf"]["pacificsangha"]}`},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: `${blurbs["svrf"]["refreshing"]}`},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: `${blurbs["svrf"]["satisfying"]}`},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon", product: "dragon", blurb: `${blurbs["shijin"]["dragon"]}`},
{brand: "shijin", shelfName: "Phoenix", product: "phoenix", blurb: `${blurbs["shijin"]["phoenix"]}`},
{brand: "shijin", shelfName: "Tiger", product: "tiger", blurb: `${blurbs["shijin"]["tiger"]}`},
{brand: "shijin", shelfName: "Tortoise", product: "tortoise", blurb: `${blurbs["shijin"]["tortoise"]}`},
{brand: "shijin", shelfName: "Tortoise Ice", product: "tortoiseice", blurb: `${blurbs["shijin"]["tortoiseice"]}`},
{brand: "shijin", shelfName: "Tortoise On Ice", product: "tortoiseonice", blurb: `${blurbs["shijin"]["tortoiseonice"]}`},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Banana Dragonberry", product: "bananadragonberry", blurb: `${blurbs["solace"]["bananadragonberry"]}`},
{brand: "solace", shelfName: "Blue Raspberry Lemonade Ice", product: "blueraspberrylemonadeice", blurb: `${blurbs["solace"]["blueraspberrylemonadeice"]}`},
{brand: "solace", shelfName: "Blues Lemonade", product: "blueslemonade", blurb: `${blurbs["solace"]["blueslemonade"]}`},
{brand: "solace", shelfName: "Dragonthol", product: "dragonthol", blurb: `${blurbs["solace"]["dragonthol"]}`},
{brand: "solace", shelfName: "Grape", product: "grape", blurb: `${blurbs["solace"]["grape"]}`},
{brand: "solace", shelfName: "Lemon Lime Fusion", product: "lemonlimefusion", blurb: `${blurbs["solace"]["lemonlimefusion"]}`},
{brand: "solace", shelfName: "Sea Salt Blueberry", product: "seasaltblueberry", blurb: `${blurbs["solace"]["seasaltblueberry"]}`},
{brand: "solace", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["solace"]["strawberry"]}`},
{brand: "solace", shelfName: "Strawberry Kiwi Ice", product: "strawberrykiwiice", blurb: `${blurbs["solace"]["strawberrykiwiice"]}`},
{brand: "yogi", shelfName: " ", product: "logo", blurb: " "},
{brand: "yogi", shelfName: "Apple Cinnamon Granola Bar", product: "applecinnamongranolabar", blurb: `${blurbs["yogi"]["applecinnamongranolabar"]}`},
{brand: "yogi", shelfName: "Blueberry Granola", product: "blueberrygranola", blurb: `${blurbs["yogi"]["blueberrygranola"]}`},
{brand: "yogi", shelfName: "Granola", product: "granola", blurb: `${blurbs["yogi"]["granola"]}`},
{brand: "yogi", shelfName: "Java Granola Bar", product: "javagranolabar", blurb: `${blurbs["yogi"]["javagranolabar"]}`},
{brand: "yogi", shelfName: "Lemon Granola Bar", product: "lemongranolabar", blurb: `${blurbs["yogi"]["lemongranolabar"]}`},
{brand: "yogi", shelfName: "Peanut Butter Banana Granola", product: "peanutbutterbananagranola", blurb: `${blurbs["yogi"]["peanutbutterbananagranola"]}`},
{brand: "yogi", shelfName: "Strawberry Granola", product: "strawberrygranola", blurb: `${blurbs["yogi"]["strawberrygranola"]}`},
{brand: "yogi", shelfName: "Vanilla Tobacco Granola Bar", product: "vanillatobaccogranolabar", blurb: `${blurbs["yogi"]["vanillatobaccogranolabar"]}`},
];


let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
