let inventory = [
	


{brand: "baristabrewco", shelfName: " ", product: "logo", blurb: " "},
{brand: "baristabrewco", shelfName: "Cinnamon Glazed Blueberry Scone", product: "cinnamonglazedblueberryscone", blurb: "undefined"},
{brand: "baristabrewco", shelfName: "Maple Bar Donut", product: "maplebardonut", blurb: "undefined"},
{brand: "baristabrewco", shelfName: "Salted Caramel Macchiato", product: "saltedcaramelmacchiato", blurb: "undefined"},
{brand: "baristabrewco", shelfName: "Smores Mocha Breeze", product: "smoresmochabreeze", blurb: "undefined"},
{brand: "californiagrown", shelfName: " ", product: "logo", blurb: " "},
{brand: "californiagrown", shelfName: "Grizzly Apple", product: "grizzlyapple", blurb: "undefined"},
{brand: "californiagrown", shelfName: "Grizzly Apple cool", product: "grizzlyapplecool", blurb: "undefined"},
{brand: "californiagrown", shelfName: "Napa Nectar", product: "napanectar", blurb: "undefined"},
{brand: "californiagrown", shelfName: "Napa Nectar cool", product: "napanectarcool", blurb: "undefined"},
{brand: "californiagrown", shelfName: "Wavy Watermelon", product: "wavywatermelon", blurb: "undefined"},
{brand: "californiagrown", shelfName: "Wavy Watermelon cool", product: "wavywatermeloncool", blurb: "undefined"},
{brand: "crisp", shelfName: " ", product: "logo", blurb: " "},
{brand: "crisp", shelfName: "Cider", product: "cider", blurb: "undefined"},
{brand: "crisp", shelfName: "Menthol", product: "menthol", blurb: "undefined"},
{brand: "crisp", shelfName: "Original Red", product: "originalred", blurb: "undefined"},
{brand: "drexdrips", shelfName: " ", product: "logo", blurb: " "},
{brand: "drexdrips", shelfName: "Real Talk", product: "realtalk", blurb: "undefined"},
{brand: "element", shelfName: " ", product: "logo", blurb: " "},
{brand: "element", shelfName: "Fresh Squeeze", product: "freshsqueeze", blurb: "undefined"},
{brand: "element", shelfName: "Pink Grapefruit", product: "pinkgrapefruit", blurb: "undefined"},
{brand: "element", shelfName: "Pink lemonade", product: "pinklemonade", blurb: "undefined"},
{brand: "fivepawns", shelfName: " ", product: "logo", blurb: " "},
{brand: "fivepawns", shelfName: "Black Flag Risen", product: "blackflagrisen", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Bowdens Mate", product: "bowdensmate", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Castle Long", product: "castlelong", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Gambit", product: "gambit", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Grandmaster", product: "grandmaster", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Queenside", product: "queenside", blurb: "undefined"},
{brand: "fivepawns", shelfName: "Symmetry Six", product: "symmetrysix", blurb: "undefined"},
{brand: "freshpressed", shelfName: " ", product: "logo", blurb: " "},
{brand: "freshpressed", shelfName: "Fruit Finale", product: "fruitfinale", blurb: "undefined"},
{brand: "freshpressed", shelfName: "HoneyComb Berry", product: "honeycombberry", blurb: "undefined"},
{brand: "freshpressed", shelfName: "Lava Luau", product: "lavaluau", blurb: "undefined"},
{brand: "freshpressed", shelfName: "Pressed Pink Melon", product: "pressedpinkmelon", blurb: "undefined"},
{brand: "freshpressed", shelfName: "Sugar Tantrum", product: "sugartantrum", blurb: "undefined"},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon Freeze", product: "blueberrylemonfreeze", blurb: "With menthol."},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: " "},
{brand: "juicehead", shelfName: "Guava Peach Ice", product: "guavapeachice", blurb: "undefined"},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Peach Pear Freeze", product: "peachpearfreeze", blurb: "undefined"},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit Freeze", product: "pineapplegrapefruitfreeze", blurb: "undefined"},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi Freeze", product: "strawberrykiwifreeze", blurb: "undefined"},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: "With menthol."},
{brand: "loyalty", shelfName: " ", product: "logo", blurb: " "},
{brand: "loyalty", shelfName: "Double Shot", product: "doubleshot", blurb: "undefined"},
{brand: "loyalty", shelfName: "Ki Berry", product: "kiberry", blurb: "Kiwi strawberry."},
{brand: "loyalty", shelfName: "Melon Ade Ice", product: "melonadeice", blurb: "undefined"},
{brand: "loyalty", shelfName: "PomNAde Ice", product: "pomnadeice", blurb: "With menthol"},
{brand: "loyalty", shelfName: "Wata Mango", product: "watamango", blurb: "Watermelon mango."},
{brand: "mamasan", shelfName: " ", product: "logo", blurb: " "},
{brand: "mamasan", shelfName: "ASAP", product: "asap", blurb: "undefined"},
{brand: "mamasan", shelfName: "Bruce Leechee", product: "bruceleechee", blurb: "undefined"},
{brand: "mamasan", shelfName: "Guava Pop", product: "guavapop", blurb: "undefined"},
{brand: "mamasan", shelfName: "Mama Melon", product: "mamamelon", blurb: "undefined"},
{brand: "mamasan", shelfName: "Purple Cheesecake", product: "purplecheesecake", blurb: "undefined"},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: "Bold tobacco with a hint of something sweet."},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: "Plain and natural tobacco, middle of the road."},
{brand: "naked", shelfName: "Euro Gold", product: "eurogold", blurb: "Natural tobacco with vanilla custard."},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: "Blue raspberry with a hint of lemon."},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: "An icy cold hit to the back of your throat."},
{brand: "pnw", shelfName: "Arctic Tobacco", product: "arctictobacco", blurb: "Bold tobacco and menthol."},
{brand: "pnw", shelfName: "Blueberry Muffin", product: "blueberrymuffin", blurb: "Blueberries and vanilla muffin."},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: " "},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: "Just like the cereal"},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: "Sweet fruity cereal and milk."},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: "Soft vanilla cake batter."},
{brand: "pnw", shelfName: "NW", product: "nw", blurb: "undefined"},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: "Peaches and menthol"},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: "Also available in menthol."},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: "Menthol and mint leaf."},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: "Soft vanilla, hazelnut and coffee."},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Blood Orange Banana Gooseberry", product: "bloodorangebananagooseberry", blurb: "Ripe gooseberries are like sour grapes."},
{brand: "pachamama", shelfName: "Fuji Apple Strawberry Nectarine", product: "fujiapplestrawberrynectarine", blurb: " "},
{brand: "pachamama", shelfName: "Honeydew Berry Kiwi", product: "honeydewberrykiwi", blurb: "Honeydew, strawberry, kiwi."},
{brand: "pachamama", shelfName: "Huckleberry Pear Acai", product: "huckleberrypearacai", blurb: " "},
{brand: "pachamama", shelfName: "Mango Pitaya Pineapple", product: "mangopitayapineapple", blurb: "undefined"},
{brand: "pachamama", shelfName: "Passion Fruit Raspberry Yuzu", product: "passionfruitraspberryyuzu", blurb: "Yuzu is a citrus fruit."},
{brand: "pachamama", shelfName: "Peach Papaya Coconut Cream", product: "peachpapayacoconutcream", blurb: ""},
{brand: "pachamama", shelfName: "Strawberry Guava Jackfruit", product: "strawberryguavajackfruit", blurb: "Jackfruit is often compared to mango or pineapple."},
{brand: "racks", shelfName: " ", product: "logo", blurb: " "},
{brand: "racks", shelfName: "Peach Mojito", product: "peachmojito", blurb: "undefined"},
{brand: "racks", shelfName: "Watermelon Mojito", product: "watermelonmojito", blurb: "undefined"},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Acid Worm", product: "acidworm", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: "Tobacco with blackberry custard."},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: "Blackberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: "Blue raspberry fruit punch."},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: "Caramel apple custard."},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: "Caramel, hazelnut, and marshmallows."},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: "Coconut, watermelon, and mango."},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: "Nothin! Just VG, PG, and nicotine."},
{brand: "riverreserve", shelfName: "Drifter", product: "drifter", blurb: "Whipped cream with blueberries."},
{brand: "riverreserve", shelfName: "Drifter X", product: "drifterx", blurb: "Whipped cream with blackberries."},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: "Mango pomegranate lemonade."},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: "Graham crackers and caramel adorned with shaved almonds, Kentucky bourbon and a splash of coconut cream."},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: "Fruit punch!"},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: "Whipped cream with tart lemon."},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: "Honeydew, lemonlime, and cherry."},
{brand: "riverreserve", shelfName: "Mild Tobacco", product: "mildtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Natural Tobacco", product: "naturaltobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Northwest", product: "northwest", blurb: "Vanilla, hazelnut, tobacco."},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: "Just like those little rootbeer barrel candies."},
{brand: "riverreserve", shelfName: "PBG", product: "pbg", blurb: "Peanut butter, banana, graham cracker."},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: " "},
{brand: "riverreserve", shelfName: "Pebbles Cheesecake", product: "pebblescheesecake", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: " "},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: "Raspberry and lemon."},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: "Pineapple coconut rum."},
{brand: "riverreserve", shelfName: "River Maiden", product: "rivermaiden", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: "Tobacco with a hint of vanilla cream."},
{brand: "riverreserve", shelfName: "Strawberry Bandit", product: "strawberrybandit", blurb: "Strawberry custard and tobacco."},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: "Whipped cream with strawberries."},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: "Strawberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: "Whipped cream with strawberry and banana."},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: "Strawberries mixed with sweet vanilla custard."},
{brand: "riverreserve", shelfName: "Sweet Cream Butterscotch", product: "sweetcreambutterscotch", blurb: " "},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: "Strawberry and coconut."},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: "Tobacco with vanilla custard."},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: "Vanilla graham cracker with a brown sugar dusting."},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: "A scoop of vanilla ice cream atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: "Watermelon fruit punch with menthol."},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: "Watermelon and kiwi."},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balance Iced", product: "balanceiced", blurb: "undefined"},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: "undefined"},
{brand: "svrf", shelfName: "Fairground", product: "fairground", blurb: "Deep fried cream cake."},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: "Chocolate milk."},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: "Strawberry milk."},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: "undefined"},
{brand: "svrf", shelfName: "Revive Iced", product: "reviveiced", blurb: "undefined"},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: "undefined"},
{brand: "svrf", shelfName: "Stimulating", product: "stimulating", blurb: "undefined"},
{brand: "svrf", shelfName: "Boba Dewwy", product: "bobadewwy", blurb: "undefined"},
{brand: "svrf", shelfName: "Boba Jazzy", product: "bobajazzy", blurb: "undefined"},
{brand: "svrf", shelfName: "Boba Manggo", product: "bobamanggo", blurb: "undefined"},
{brand: "vaporvandals", shelfName: " ", product: "logo", blurb: " "},
{brand: "vaporvandals", shelfName: "Crew", product: "crew", blurb: "undefined"},
{brand: "vaporvandals", shelfName: "Outlaw", product: "outlaw", blurb: "undefined"},
{brand: "vaporvandals", shelfName: "Purp", product: "purp", blurb: "undefined"},
{brand: "vaporvandals", shelfName: "Skinny Dip", product: "skinnydip", blurb: "undefined"},
{brand: "vaporvandals", shelfName: "Toast", product: "toast", blurb: "undefined"},
{brand: "yogi", shelfName: " ", product: "logo", blurb: " "},
{brand: "yogi", shelfName: "Apple Cinnamon Granola Bar", product: "applecinnamongranolabar", blurb: "undefined"},
{brand: "yogi", shelfName: "Blueberry Granola", product: "blueberrygranola", blurb: "undefined"},
{brand: "yogi", shelfName: "Granola", product: "granola", blurb: "undefined"},
{brand: "yogi", shelfName: "Java Granola Bar", product: "javagranolabar", blurb: "undefined"},
{brand: "yogi", shelfName: "Lemon Granola Bar", product: "lemongranolabar", blurb: "undefined"},
{brand: "yogi", shelfName: "Peanut Butter Banana Granola", product: "peanutbutterbananagranola", blurb: "undefined"},
{brand: "yogi", shelfName: "Strawberry Granola", product: "strawberrygranola", blurb: "undefined"},
{brand: "yogi", shelfName: "Vanilla Tobacco Granola Bar", product: "vanillatobaccogranolabar", blurb: "undefined"},


];

let saltInventory = [


{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: "Strawberry and blueberry."},
{brand: "airfactory", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: "undefined"},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: "Nutmeg, cinnamon, glaze, and pastry."},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: "Smooth vanilla custard."},
{brand: "airfactory", shelfName: "Custard Tobacco", product: "custardtobacco", blurb: "Smooth vanilla custard with tobacco."},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: "Watermelon and honeydew taffy."},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: "Probably closer to mint, but that's okay."},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: "A pool of 'mysterious berries.'"},
{brand: "drexdrips", shelfName: " ", product: "logo", blurb: " "},
{brand: "drexdrips", shelfName: "Berry Ice", product: "berryice", blurb: "undefined"},
{brand: "drexdrips", shelfName: "Chill Melon", product: "chillmelon", blurb: "undefined"},
{brand: "drexdrips", shelfName: "No Filter", product: "nofilter", blurb: "undefined"},
{brand: "drexdrips", shelfName: "On Point", product: "onpoint", blurb: "undefined"},
{brand: "drexdrips", shelfName: "Real Talk", product: "realtalk", blurb: "undefined"},
{brand: "drexdrips", shelfName: "Straw Breeze", product: "strawbreeze", blurb: "undefined"},
{brand: "drexdrips", shelfName: "That Ish", product: "thatish", blurb: "undefined"},
{brand: "drexdrips", shelfName: "Tropi Cool", product: "tropicool", blurb: "undefined"},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: " "},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Apple Tobacco", product: "appletobacco", blurb: "undefined"},
{brand: "pachamama", shelfName: "Fuji", product: "fuji", blurb: "undefined"},
{brand: "pachamama", shelfName: "Icy Mango", product: "icymango", blurb: "undefined"},
{brand: "pachamama", shelfName: "Sorbet", product: "sorbet", blurb: "undefined"},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Belts Burst", product: "beltsburst", blurb: "undefined"},
{brand: "podjuice", shelfName: "Blue Razz Burst", product: "bluerazzburst", blurb: "undefined"},
{brand: "podjuice", shelfName: "Cotton Burst", product: "cottonburst", blurb: "undefined"},
{brand: "podjuice", shelfName: "Hawaiian Pod", product: "hawaiianpod", blurb: "undefined"},
{brand: "podjuice", shelfName: "Jewel Fuji Nektar", product: "jewelfujinektar", blurb: "undefined"},
{brand: "podjuice", shelfName: "Jewel Mango LE", product: "jewelmangole", blurb: "undefined"},
{brand: "podjuice", shelfName: "Jewel Mint", product: "jewelmint", blurb: "Just plain mint, little to no menthol."},
{brand: "podjuice", shelfName: "Jewel Mint Diamond", product: "jewelmintdiamond", blurb: "undefined"},
{brand: "podjuice", shelfName: "Jewel Tobacco", product: "jeweltobacco", blurb: "undefined"},
{brand: "podjuice", shelfName: "Juicy Apple", product: "juicyapple", blurb: "undefined"},
{brand: "podjuice", shelfName: "Loops", product: "loops", blurb: "undefined"},
{brand: "podjuice", shelfName: "Melon Breeze", product: "melonbreeze", blurb: "undefined"},
{brand: "podjuice", shelfName: "Peach Burst", product: "peachburst", blurb: "undefined"},
{brand: "podjuice", shelfName: "Pink Burst", product: "pinkburst", blurb: "undefined"},
{brand: "podjuice", shelfName: "Savage Patch", product: "savagepatch", blurb: "undefined"},
{brand: "podjuice", shelfName: "Strawberry Dream", product: "strawberrydream", blurb: "undefined"},
{brand: "podjuice", shelfName: "Strawberry Lemonade", product: "strawberrylemonade", blurb: "undefined"},
{brand: "podjuice", shelfName: "Watermelon Blast", product: "watermelonblast", blurb: "undefined"},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: "Blue raspberry fruit punch."},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: "Whipped cream with tart lemon."},
{brand: "riverreserve", shelfName: "Tangie", product: "tangie", blurb: "undefined"},
{brand: "riverreserve", shelfName: "water Creek", product: "watercreek", blurb: "undefined"},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: "undefined"},
{brand: "svrf", shelfName: "Fairgrounds", product: "fairgrounds", blurb: "Deep fried cream cake."},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: "Chocolate milk."},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: "Strawberry milk."},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: "undefined"},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: "undefined"},
{brand: "shijinvapor", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijinvapor", shelfName: "Dragon", product: "dragon", blurb: "Lemon tart."},
{brand: "shijinvapor", shelfName: "Phoenix", product: "phoenix", blurb: "Guava lychee."},
{brand: "shijinvapor", shelfName: "Tiger", product: "tiger", blurb: "Peach mango slushy."},
{brand: "shijinvapor", shelfName: "Tortoise", product: "tortoise", blurb: "Green apple, blue raspberry."},
{brand: "shijinvapor", shelfName: "Tortoise Ice", product: "tortoiseice", blurb: "undefined"},
{brand: "shijinvapor", shelfName: "Tortoise On Ice", product: "tortoiseonice", blurb: "Green apple, blue raspberry with menthol."},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Banana Dragonberry", product: "bananadragonberry", blurb: "Dragonfruit and banana."},
{brand: "solace", shelfName: "Blue Raspberry Lemonade Ice", product: "blueraspberrylemonadeice", blurb: "undefined"},
{brand: "solace", shelfName: "Blues Lemonade", product: "blueslemonade", blurb: "Lemonade with a hint of blue raspberry."},
{brand: "solace", shelfName: "Dragonthol", product: "dragonthol", blurb: "Dragonfruit and menthol."},
{brand: "solace", shelfName: "Grape", product: "grape", blurb: " "},
{brand: "solace", shelfName: "Lemon Lime Fusion", product: "lemonlimefusion", blurb: " "},
{brand: "solace", shelfName: "Sea Blueberry", product: "seablueberry", blurb: " "},
{brand: "solace", shelfName: "Strawberry", product: "strawberry", blurb: "Strawberry kiwi with menthol."},
{brand: "solace", shelfName: "Strawberry Kiwi Ice", product: "strawberrykiwiice", blurb: "Strawberry kiwi with menthol."},
{brand: "yogi", shelfName: " ", product: "logo", blurb: " "},
{brand: "yogi", shelfName: "Apple Cinnamon Granola Bar", product: "applecinnamongranolabar", blurb: "undefined"},
{brand: "yogi", shelfName: "Blueberry Granola", product: "blueberrygranola", blurb: "undefined"},
{brand: "yogi", shelfName: "Granola", product: "granola", blurb: "undefined"},
{brand: "yogi", shelfName: "Java Granola Bar", product: "javagranolabar", blurb: "undefined"},
{brand: "yogi", shelfName: "Lemon Granola Bar", product: "lemongranolabar", blurb: "undefined"},
{brand: "yogi", shelfName: "Peanut Butter Banana Granola", product: "peanutbutterbananagranola", blurb: "undefined"},
{brand: "yogi", shelfName: "Strawberry Granola", product: "strawberrygranola", blurb: "undefined"},
{brand: "yogi", shelfName: "Vanilla Tobacco Granola Bar", product: "vanillatobaccogranolabar", blurb: "undefined"},



];

let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
