
let inventory = [
{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: `${blurbs["airfactory"]["berryrush"]}`},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: `${blurbs["airfactory"]["bluerazz"]}`},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: `${blurbs["airfactory"]["bluerazzice"]}`},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: `${blurbs["airfactory"]["creamycrunch"]}`},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: `${blurbs["airfactory"]["mango"]}`},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: `${blurbs["airfactory"]["mangoice"]}`},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: `${blurbs["airfactory"]["melonlush"]}`},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: `${blurbs["airfactory"]["melonlushice"]}`},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: `${blurbs["airfactory"]["menthol"]}`},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: `${blurbs["airfactory"]["mint"]}`},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: `${blurbs["airfactory"]["mixedberry"]}`},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["airfactory"]["strawberrykiwi"]}`},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: `${blurbs["airfactory"]["tropicfreeze"]}`},
{brand: "aqua", shelfName: " ", product: "logo", blurb: " "},
{brand: "aqua", shelfName: "Flow", product: "flow", blurb: `${blurbs["aqua"]["flow"]}`},
{brand: "aqua", shelfName: "Oasis", product: "oasis", blurb: `${blurbs["aqua"]["oasis"]}`},
{brand: "californiagrown", shelfName: " ", product: "logo", blurb: " "},
{brand: "californiagrown", shelfName: "Grizzly Apple", product: "grizzlyapple", blurb: `${blurbs["californiagrown"]["grizzlyapple"]}`},
{brand: "californiagrown", shelfName: "Grizzly Apple cool", product: "grizzlyapplecool", blurb: `${blurbs["californiagrown"]["grizzlyapplecool"]}`},
{brand: "californiagrown", shelfName: "Napa Nectar", product: "napanectar", blurb: `${blurbs["californiagrown"]["napanectar"]}`},
{brand: "californiagrown", shelfName: "Napa Nectar cool", product: "napanectarcool", blurb: `${blurbs["californiagrown"]["napanectarcool"]}`},
{brand: "californiagrown", shelfName: "Wavy Watermelon", product: "wavywatermelon", blurb: `${blurbs["californiagrown"]["wavywatermelon"]}`},
{brand: "californiagrown", shelfName: "Wavy Watermelon cool", product: "wavywatermeloncool", blurb: `${blurbs["californiagrown"]["wavywatermeloncool"]}`},
{brand: "choices", shelfName: " ", product: "logo", blurb: " "},
{brand: "choices", shelfName: "Ballin", product: "ballin", blurb: `${blurbs["choices"]["ballin"]}`},
{brand: "choices", shelfName: "Hood Rich", product: "hoodrich", blurb: `${blurbs["choices"]["hoodrich"]}`},
{brand: "choices", shelfName: "Six Figures", product: "sixfigures", blurb: `${blurbs["choices"]["sixfigures"]}`},
{brand: "choices", shelfName: "Skrilla", product: "skrilla", blurb: `${blurbs["choices"]["skrilla"]}`},
{brand: "choices", shelfName: "Stackin Chips", product: "stackinchips", blurb: `${blurbs["choices"]["stackinchips"]}`},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple", product: "grapeapple", blurb: `${blurbs["cloudnurdz"]["grapeapple"]}`},
{brand: "cloudnurdz", shelfName: "Grape Apple Iced", product: "grapeappleiced", blurb: `${blurbs["cloudnurdz"]["grapeappleiced"]}`},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: `${blurbs["cloudnurdz"]["grapestrawberry"]}`},
{brand: "cloudnurdz", shelfName: "Grape Strawberry Iced", product: "grapestrawberryiced", blurb: `${blurbs["cloudnurdz"]["grapestrawberryiced"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: `${blurbs["cloudnurdz"]["peachbluerazz"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz Iced", product: "peachbluerazziced", blurb: `${blurbs["cloudnurdz"]["peachbluerazziced"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: `${blurbs["cloudnurdz"]["strawberrylemon"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon Iced", product: "strawberrylemoniced", blurb: `${blurbs["cloudnurdz"]["strawberrylemoniced"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: `${blurbs["cloudnurdz"]["watermelonapple"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple Iced", product: "watermelonappleiced", blurb: `${blurbs["cloudnurdz"]["watermelonappleiced"]}`},
{brand: "coastalclouds", shelfName: " ", product: "logo", blurb: " "},
{brand: "coastalclouds", shelfName: "Apple Peach Strawberry", product: "applepeachstrawberry", blurb: `${blurbs["coastalclouds"]["applepeachstrawberry"]}`},
{brand: "coastalclouds", shelfName: "Blood Orange Mango Snow Cone", product: "bloodorangemangosnowcone", blurb: `${blurbs["coastalclouds"]["bloodorangemangosnowcone"]}`},
{brand: "coastalclouds", shelfName: "Blueberry Banana Muffin", product: "blueberrybananamuffin", blurb: `${blurbs["coastalclouds"]["blueberrybananamuffin"]}`},
{brand: "coastalclouds", shelfName: "Blueberry Limeade", product: "blueberrylimeade", blurb: `${blurbs["coastalclouds"]["blueberrylimeade"]}`},
{brand: "coastalclouds", shelfName: "Guava Punch", product: "guavapunch", blurb: `${blurbs["coastalclouds"]["guavapunch"]}`},
{brand: "coastalclouds", shelfName: "Iced Apple Peach Strawberry", product: "icedapplepeachstrawberry", blurb: `${blurbs["coastalclouds"]["icedapplepeachstrawberry"]}`},
{brand: "coastalclouds", shelfName: "Iced Blood Orange Mango Snow Cone", product: "icedbloodorangemangosnowcone", blurb: `${blurbs["coastalclouds"]["icedbloodorangemangosnowcone"]}`},
{brand: "coastalclouds", shelfName: "Iced Grape Berries", product: "icedgrapeberries", blurb: `${blurbs["coastalclouds"]["icedgrapeberries"]}`},
{brand: "coastalclouds", shelfName: "Iced Mango Berries", product: "icedmangoberries", blurb: `${blurbs["coastalclouds"]["icedmangoberries"]}`},
{brand: "coastalclouds", shelfName: "Iced Melon Berries", product: "icedmelonberries", blurb: `${blurbs["coastalclouds"]["icedmelonberries"]}`},
{brand: "coastalclouds", shelfName: "Iced Passion Fruit Orange Guava", product: "icedpassionfruitorangeguava", blurb: `${blurbs["coastalclouds"]["icedpassionfruitorangeguava"]}`},
{brand: "coastalclouds", shelfName: "Mango Berries", product: "mangoberries", blurb: `${blurbs["coastalclouds"]["mangoberries"]}`},
{brand: "coastalclouds", shelfName: "Maple Butter", product: "maplebutter", blurb: `${blurbs["coastalclouds"]["maplebutter"]}`},
{brand: "coastalclouds", shelfName: "Melon Berries", product: "melonberries", blurb: `${blurbs["coastalclouds"]["melonberries"]}`},
{brand: "coastalclouds", shelfName: "Peach Tea", product: "peachtea", blurb: `${blurbs["coastalclouds"]["peachtea"]}`},
{brand: "coastalclouds", shelfName: "Pink Lemonade", product: "pinklemonade", blurb: `${blurbs["coastalclouds"]["pinklemonade"]}`},
{brand: "coastalclouds", shelfName: "Sugared Nectarine", product: "sugarednectarine", blurb: `${blurbs["coastalclouds"]["sugarednectarine"]}`},
{brand: "fruitia", shelfName: " ", product: "logo", blurb: " "},
{brand: "fruitia", shelfName: "Apple Kiwi Crush", product: "applekiwicrush", blurb: `${blurbs["fruitia"]["applekiwicrush"]}`},
{brand: "fruitia", shelfName: "Blood Orange Cactus Cooler", product: "bloodorangecactuscooler", blurb: `${blurbs["fruitia"]["bloodorangecactuscooler"]}`},
{brand: "fruitia", shelfName: "Passion Fruit Guava Punch", product: "passionfruitguavapunch", blurb: `${blurbs["fruitia"]["passionfruitguavapunch"]}`},
{brand: "fruitia", shelfName: "Pineapple Citrus Twist", product: "pineapplecitrustwist", blurb: `${blurbs["fruitia"]["pineapplecitrustwist"]}`},
{brand: "fruitia", shelfName: "Smooth Banana Ice", product: "smoothbananaice", blurb: `${blurbs["fruitia"]["smoothbananaice"]}`},
{brand: "fruitia", shelfName: "Strawberry Coconut Refreshers", product: "strawberrycoconutrefreshers", blurb: `${blurbs["fruitia"]["strawberrycoconutrefreshers"]}`},
{brand: "fruitia", shelfName: "Sweet Peach Soda", product: "sweetpeachsoda", blurb: `${blurbs["fruitia"]["sweetpeachsoda"]}`},
{brand: "hidrip", shelfName: " ", product: "logo", blurb: " "},
{brand: "hidrip", shelfName: "Dew Berry Iced", product: "dewberryiced", blurb: `${blurbs["hidrip"]["dewberryiced"]}`},
{brand: "hidrip", shelfName: "Island Orange", product: "islandorange", blurb: `${blurbs["hidrip"]["islandorange"]}`},
{brand: "hidrip", shelfName: "Island Orange Iced", product: "islandorangeiced", blurb: `${blurbs["hidrip"]["islandorangeiced"]}`},
{brand: "hidrip", shelfName: "Melon Patch", product: "melonpatch", blurb: `${blurbs["hidrip"]["melonpatch"]}`},
{brand: "hidrip", shelfName: "Melon Patch Iced", product: "melonpatchiced", blurb: `${blurbs["hidrip"]["melonpatchiced"]}`},
{brand: "hidrip", shelfName: "Nectarine Lychee", product: "nectarinelychee", blurb: `${blurbs["hidrip"]["nectarinelychee"]}`},
{brand: "hidrip", shelfName: "Nectarine Lychee Ice", product: "nectarinelycheeice", blurb: `${blurbs["hidrip"]["nectarinelycheeice"]}`},
{brand: "hidrip", shelfName: "Peachy Mango", product: "peachymango", blurb: `${blurbs["hidrip"]["peachymango"]}`},
{brand: "hidrip", shelfName: "Peachy Mango Iced", product: "peachymangoiced", blurb: `${blurbs["hidrip"]["peachymangoiced"]}`},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: `${blurbs["jammonster"]["blackberry"]}`},
{brand: "jammonster", shelfName: "Grape", product: "grape", blurb: `${blurbs["jammonster"]["grape"]}`},
{brand: "jammonster", shelfName: "Mangerine Guava ICE", product: "mangerineguavaice", blurb: `${blurbs["jammonster"]["mangerineguavaice"]}`},
{brand: "jammonster", shelfName: "Melon Colada ICE", product: "meloncoladaice", blurb: `${blurbs["jammonster"]["meloncoladaice"]}`},
{brand: "jammonster", shelfName: "PB Jam Monster Grape", product: "pbjammonstergrape", blurb: `${blurbs["jammonster"]["pbjammonstergrape"]}`},
{brand: "jammonster", shelfName: "PB Jam Monster Strawberry", product: "pbjammonsterstrawberry", blurb: `${blurbs["jammonster"]["pbjammonsterstrawberry"]}`},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: `${blurbs["jammonster"]["raspberry"]}`},
{brand: "jammonster", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["jammonster"]["strawberry"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: `${blurbs["juicehead"]["blueberrylemon"]}`},
{brand: "juicehead", shelfName: "Blueberry Lemon Freeze", product: "blueberrylemonfreeze", blurb: `${blurbs["juicehead"]["blueberrylemonfreeze"]}`},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: `${blurbs["juicehead"]["peachpear"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: `${blurbs["juicehead"]["watermelonlime"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: `${blurbs["juicehead"]["watermelonlimefreeze"]}`},
{brand: "loyalty", shelfName: " ", product: "logo", blurb: " "},
{brand: "loyalty", shelfName: "Berry Cake", product: "berrycake", blurb: `${blurbs["loyalty"]["berrycake"]}`},
{brand: "loyalty", shelfName: "Double Shot", product: "doubleshot", blurb: `${blurbs["loyalty"]["doubleshot"]}`},
{brand: "loyalty", shelfName: "PomNAde Ice", product: "pomnadeice", blurb: `${blurbs["loyalty"]["pomnadeice"]}`},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: `${blurbs["naked"]["americanpatriot"]}`},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: `${blurbs["naked"]["cubanblend"]}`},
{brand: "naked", shelfName: "Euro Gold", product: "eurogold", blurb: `${blurbs["naked"]["eurogold"]}`},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: `${blurbs["naked"]["hawaiianpog"]}`},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: `${blurbs["naked"]["lavaflow"]}`},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: `${blurbs["naked"]["reallyberryveryberry"]}`},
{brand: "naked", shelfName: "Menthol Brain Freeze", product: "mentholbrainfreeze", blurb: `${blurbs["naked"]["mentholbrainfreeze"]}`},
{brand: "naked", shelfName: "Menthol Crisp Menthol", product: "mentholcrispmenthol", blurb: `${blurbs["naked"]["mentholcrispmenthol"]}`},
{brand: "naked", shelfName: "Menthol Polar Breeze", product: "mentholpolarbreeze", blurb: `${blurbs["naked"]["mentholpolarbreeze"]}`},
{brand: "naked", shelfName: "Menthol Very Cool", product: "mentholverycool", blurb: `${blurbs["naked"]["mentholverycool"]}`},
{brand: "ofe", shelfName: " ", product: "logo", blurb: " "},
{brand: "ofe", shelfName: "Classic Gold", product: "classicgold", blurb: `${blurbs["ofe"]["classicgold"]}`},
{brand: "ofe", shelfName: "Original Bold", product: "originalbold", blurb: `${blurbs["ofe"]["originalbold"]}`},
{brand: "ofe", shelfName: "Turkish Blend", product: "turkishblend", blurb: `${blurbs["ofe"]["turkishblend"]}`},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: `${blurbs["pnw"]["arcticfrost"]}`},
{brand: "pnw", shelfName: "Arctic Tobacco", product: "arctictobacco", blurb: `${blurbs["pnw"]["arctictobacco"]}`},
{brand: "pnw", shelfName: "Blueberry Muffin", product: "blueberrymuffin", blurb: `${blurbs["pnw"]["blueberrymuffin"]}`},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: `${blurbs["pnw"]["cherrylimeade"]}`},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: `${blurbs["pnw"]["cinnamoncrunch"]}`},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: `${blurbs["pnw"]["fruityos"]}`},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: `${blurbs["pnw"]["madbatter"]}`},
{brand: "pnw", shelfName: "NW", product: "nw", blurb: `${blurbs["pnw"]["nw"]}`},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: `${blurbs["pnw"]["peachfrost"]}`},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: `${blurbs["pnw"]["peaches"]}`},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: `${blurbs["pnw"]["spearmint"]}`},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: `${blurbs["pnw"]["vanillanutlatte"]}`},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Blood Orange Banana Gooseberry", product: "bloodorangebananagooseberry", blurb: `${blurbs["pachamama"]["bloodorangebananagooseberry"]}`},
{brand: "pachamama", shelfName: "Fuji Apple Strawberry Nectarine", product: "fujiapplestrawberrynectarine", blurb: `${blurbs["pachamama"]["fujiapplestrawberrynectarine"]}`},
{brand: "pachamama", shelfName: "Honeydew Berry Kiwi", product: "honeydewberrykiwi", blurb: `${blurbs["pachamama"]["honeydewberrykiwi"]}`},
{brand: "pachamama", shelfName: "Huckleberry Pear Acai", product: "huckleberrypearacai", blurb: `${blurbs["pachamama"]["huckleberrypearacai"]}`},
{brand: "pachamama", shelfName: "Mango Pitaya Pineapple", product: "mangopitayapineapple", blurb: `${blurbs["pachamama"]["mangopitayapineapple"]}`},
{brand: "pachamama", shelfName: "Strawberry Guava Jackfruit", product: "strawberryguavajackfruit", blurb: `${blurbs["pachamama"]["strawberryguavajackfruit"]}`},
{brand: "reds", shelfName: " ", product: "logo", blurb: " "},
{brand: "reds", shelfName: "Apple", product: "apple", blurb: `${blurbs["reds"]["apple"]}`},
{brand: "reds", shelfName: "Apple Iced", product: "appleiced", blurb: `${blurbs["reds"]["appleiced"]}`},
{brand: "reds", shelfName: "Berries", product: "berries", blurb: `${blurbs["reds"]["berries"]}`},
{brand: "reds", shelfName: "Berries Iced", product: "berriesiced", blurb: `${blurbs["reds"]["berriesiced"]}`},
{brand: "reds", shelfName: "Fruit Mix", product: "fruitmix", blurb: `${blurbs["reds"]["fruitmix"]}`},
{brand: "reds", shelfName: "Fruit Mix Iced", product: "fruitmixiced", blurb: `${blurbs["reds"]["fruitmixiced"]}`},
{brand: "reds", shelfName: "Grape", product: "grape", blurb: `${blurbs["reds"]["grape"]}`},
{brand: "reds", shelfName: "Grape Iced", product: "grapeiced", blurb: `${blurbs["reds"]["grapeiced"]}`},
{brand: "reds", shelfName: "Guava", product: "guava", blurb: `${blurbs["reds"]["guava"]}`},
{brand: "reds", shelfName: "Guava Iced", product: "guavaiced", blurb: `${blurbs["reds"]["guavaiced"]}`},
{brand: "reds", shelfName: "Mango", product: "mango", blurb: `${blurbs["reds"]["mango"]}`},
{brand: "reds", shelfName: "Mango Iced", product: "mangoiced", blurb: `${blurbs["reds"]["mangoiced"]}`},
{brand: "reds", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["reds"]["strawberry"]}`},
{brand: "reds", shelfName: "Strawberry Iced", product: "strawberryiced", blurb: `${blurbs["reds"]["strawberryiced"]}`},
{brand: "reds", shelfName: "Watermelon", product: "watermelon", blurb: `${blurbs["reds"]["watermelon"]}`},
{brand: "reds", shelfName: "Watermelon Iced", product: "watermeloniced", blurb: `${blurbs["reds"]["watermeloniced"]}`},
{brand: "ripevapes", shelfName: " ", product: "logo", blurb: " "},
{brand: "ripevapes", shelfName: "eLiquid VCT Strawberry", product: "eliquidvctstrawberry", blurb: `${blurbs["ripevapes"]["eliquidvctstrawberry"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: `${blurbs["riverreserve"]["bandit"]}`},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: `${blurbs["riverreserve"]["blackberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: `${blurbs["riverreserve"]["blueislandpunch"]}`},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: `${blurbs["riverreserve"]["boldtobacco"]}`},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: `${blurbs["riverreserve"]["caramelappledrifter"]}`},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: `${blurbs["riverreserve"]["caramelcove"]}`},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: `${blurbs["riverreserve"]["clearwatercreek"]}`},
{brand: "riverreserve", shelfName: "Drifter", product: "drifter", blurb: `${blurbs["riverreserve"]["drifter"]}`},
{brand: "riverreserve", shelfName: "Drifter X", product: "drifterx", blurb: `${blurbs["riverreserve"]["drifterx"]}`},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: `${blurbs["riverreserve"]["eddy"]}`},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: `${blurbs["riverreserve"]["greatwall"]}`},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: `${blurbs["riverreserve"]["islandpunch"]}`},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: `${blurbs["riverreserve"]["lemondrifter"]}`},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: `${blurbs["riverreserve"]["midorisour"]}`},
{brand: "riverreserve", shelfName: "Mild Tobacco", product: "mildtobacco", blurb: `${blurbs["riverreserve"]["mildtobacco"]}`},
{brand: "riverreserve", shelfName: "Natural Tobacco", product: "naturaltobacco", blurb: `${blurbs["riverreserve"]["naturaltobacco"]}`},
{brand: "riverreserve", shelfName: "Northwest", product: "northwest", blurb: `${blurbs["riverreserve"]["northwest"]}`},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: `${blurbs["riverreserve"]["oldwolf"]}`},
{brand: "riverreserve", shelfName: "PBG", product: "pbg", blurb: `${blurbs["riverreserve"]["pbg"]}`},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: `${blurbs["riverreserve"]["peachmangolemonade"]}`},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: `${blurbs["riverreserve"]["pineapplegrapementhol"]}`},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: `${blurbs["riverreserve"]["raspberrycrumble"]}`},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: `${blurbs["riverreserve"]["raspberrylemonitalianice"]}`},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: `${blurbs["riverreserve"]["smoothsweettobacco"]}`},
{brand: "riverreserve", shelfName: "Strawberry Bandit", product: "strawberrybandit", blurb: `${blurbs["riverreserve"]["strawberrybandit"]}`},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: `${blurbs["riverreserve"]["strawberrydrifter"]}`},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: `${blurbs["riverreserve"]["strawberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: `${blurbs["riverreserve"]["strawnanadrifter"]}`},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: `${blurbs["riverreserve"]["swampmama"]}`},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: `${blurbs["riverreserve"]["tigersblood"]}`},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: `${blurbs["riverreserve"]["vanillabandit"]}`},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: `${blurbs["riverreserve"]["vanillagraham"]}`},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: `${blurbs["riverreserve"]["vanillawafflecone"]}`},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: `${blurbs["riverreserve"]["watermelonpunchmenthol"]}`},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: `${blurbs["riverreserve"]["wiki"]}`},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Antidote On Ice", product: "antidoteonice", blurb: `${blurbs["ruthless"]["antidoteonice"]}`},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: `${blurbs["ruthless"]["ezduzit"]}`},
{brand: "ruthless", shelfName: "Ez Duz It On Ice", product: "ezduzitonice", blurb: `${blurbs["ruthless"]["ezduzitonice"]}`},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: `${blurbs["ruthless"]["grapedrank"]}`},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: `${blurbs["ruthless"]["grapedrankonice"]}`},
{brand: "ruthless", shelfName: "Jungle Fever", product: "junglefever", blurb: `${blurbs["ruthless"]["junglefever"]}`},
{brand: "ruthless", shelfName: "Paradize", product: "paradize", blurb: `${blurbs["ruthless"]["paradize"]}`},
{brand: "ruthless", shelfName: "Rage", product: "rage", blurb: `${blurbs["ruthless"]["rage"]}`},
{brand: "ruthless", shelfName: "Skir Skirr On Ice", product: "skirskirronice", blurb: `${blurbs["ruthless"]["skirskirronice"]}`},
{brand: "ruthless", shelfName: "Slurricane", product: "slurricane", blurb: `${blurbs["ruthless"]["slurricane"]}`},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: `${blurbs["ruthless"]["strizzy"]}`},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: `${blurbs["ruthless"]["swampthang"]}`},
{brand: "ruthless", shelfName: "Swamp Thang On Ice", product: "swampthangonice", blurb: `${blurbs["ruthless"]["swampthangonice"]}`},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: `${blurbs["ruthless"]["tropicthunda"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Fairground", product: "fairground", blurb: `${blurbs["svrf"]["fairground"]}`},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: `${blurbs["svrf"]["goldenticket"]}`},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: `${blurbs["svrf"]["pacificsangha"]}`},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Berrynola", product: "berrynola", blurb: `${blurbs["sadboy"]["berrynola"]}`},
{brand: "sadboy", shelfName: "Butter Cookie", product: "buttercookie", blurb: `${blurbs["sadboy"]["buttercookie"]}`},
{brand: "sadboy", shelfName: "Key Lime Cookie", product: "keylimecookie", blurb: `${blurbs["sadboy"]["keylimecookie"]}`},
{brand: "sadboy", shelfName: "Strawberry Jam Cookie", product: "strawberryjamcookie", blurb: `${blurbs["sadboy"]["strawberryjamcookie"]}`},
{brand: "sadboy", shelfName: "Strawnola", product: "strawnola", blurb: `${blurbs["sadboy"]["strawnola"]}`},
{brand: "thehypecollection", shelfName: " ", product: "logo", blurb: " "},
{brand: "thehypecollection", shelfName: "Blue Slushee", product: "blueslushee", blurb: `${blurbs["thehypecollection"]["blueslushee"]}`},
{brand: "thehypecollection", shelfName: "Cool Blue Slushee", product: "coolblueslushee", blurb: `${blurbs["thehypecollection"]["coolblueslushee"]}`},
{brand: "thehypecollection", shelfName: "Cotton Candy", product: "cottoncandy", blurb: `${blurbs["thehypecollection"]["cottoncandy"]}`},
{brand: "transistor", shelfName: " ", product: "logo", blurb: " "},
{brand: "transistor", shelfName: "Galactic Milk", product: "galacticmilk", blurb: `${blurbs["transistor"]["galacticmilk"]}`},
{brand: "vapetasia", shelfName: " ", product: "logo", blurb: " "},
{brand: "vapetasia", shelfName: "Blackberry Lemonade", product: "blackberrylemonade", blurb: `${blurbs["vapetasia"]["blackberrylemonade"]}`},
{brand: "vapetasia", shelfName: "Iced Blackberry Lemonade", product: "icedblackberrylemonade", blurb: `${blurbs["vapetasia"]["icedblackberrylemonade"]}`},
{brand: "vapetasia", shelfName: "Iced Pineapple Express", product: "icedpineappleexpress", blurb: `${blurbs["vapetasia"]["icedpineappleexpress"]}`},
{brand: "vapetasia", shelfName: "Killer Kustard", product: "killerkustard", blurb: `${blurbs["vapetasia"]["killerkustard"]}`},
{brand: "vapetasia", shelfName: "Milk of the Poppy", product: "milkofthepoppy", blurb: `${blurbs["vapetasia"]["milkofthepoppy"]}`},
{brand: "vapetasia", shelfName: "Pineapple Express", product: "pineappleexpress", blurb: `${blurbs["vapetasia"]["pineappleexpress"]}`},
{brand: "vapetasia", shelfName: "Pink Lemonade", product: "pinklemonade", blurb: `${blurbs["vapetasia"]["pinklemonade"]}`},
{brand: "vapetasia", shelfName: "Rainbow Road", product: "rainbowroad", blurb: `${blurbs["vapetasia"]["rainbowroad"]}`},
{brand: "vapetasia", shelfName: "Strawberry Killer Kustard", product: "strawberrykillerkustard", blurb: `${blurbs["vapetasia"]["strawberrykillerkustard"]}`},
];
let saltInventory = [
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "PB Grape", product: "pbgrape", blurb: `${blurbs["jammonster"]["pbgrape"]}`},
{brand: "jammonster", shelfName: "PB Strawberry", product: "pbstrawberry", blurb: `${blurbs["jammonster"]["pbstrawberry"]}`},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: `${blurbs["jammonster"]["blackberry"]}`},
{brand: "jammonster", shelfName: "Mangerine Guava", product: "mangerineguava", blurb: `${blurbs["jammonster"]["mangerineguava"]}`},
{brand: "jammonster", shelfName: "Melon Colada", product: "meloncolada", blurb: `${blurbs["jammonster"]["meloncolada"]}`},
{brand: "jammonster", shelfName: "PBJam Strawberry", product: "pbjamstrawberry", blurb: `${blurbs["jammonster"]["pbjamstrawberry"]}`},
{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: `${blurbs["airfactory"]["berryrush"]}`},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: `${blurbs["airfactory"]["bluerazz"]}`},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: `${blurbs["airfactory"]["bluerazzice"]}`},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: `${blurbs["airfactory"]["custard"]}`},
{brand: "airfactory", shelfName: "Custard Tobacco", product: "custardtobacco", blurb: `${blurbs["airfactory"]["custardtobacco"]}`},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: `${blurbs["airfactory"]["mango"]}`},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: `${blurbs["airfactory"]["mangoice"]}`},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: `${blurbs["airfactory"]["melonlush"]}`},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: `${blurbs["airfactory"]["melonlushice"]}`},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: `${blurbs["airfactory"]["menthol"]}`},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: `${blurbs["airfactory"]["mint"]}`},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: `${blurbs["airfactory"]["mixedberry"]}`},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["airfactory"]["strawberrykiwi"]}`},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: `${blurbs["airfactory"]["tropicfreeze"]}`},
{brand: "californiagrown", shelfName: " ", product: "logo", blurb: " "},
{brand: "californiagrown", shelfName: "Grizzly Apple", product: "grizzlyapple", blurb: `${blurbs["californiagrown"]["grizzlyapple"]}`},
{brand: "californiagrown", shelfName: "Grizzly Apple cool", product: "grizzlyapplecool", blurb: `${blurbs["californiagrown"]["grizzlyapplecool"]}`},
{brand: "californiagrown", shelfName: "Napa Nectar cool", product: "napanectarcool", blurb: `${blurbs["californiagrown"]["napanectarcool"]}`},
{brand: "californiagrown", shelfName: "Wavy Watermelon", product: "wavywatermelon", blurb: `${blurbs["californiagrown"]["wavywatermelon"]}`},
{brand: "californiagrown", shelfName: "Wavy Watermelon cool", product: "wavywatermeloncool", blurb: `${blurbs["californiagrown"]["wavywatermeloncool"]}`},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: `${blurbs["cloudnurdz"]["grapestrawberry"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: `${blurbs["cloudnurdz"]["peachbluerazz"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: `${blurbs["cloudnurdz"]["strawberrylemon"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: `${blurbs["cloudnurdz"]["watermelonapple"]}`},
{brand: "fruitia", shelfName: " ", product: "logo", blurb: " "},
{brand: "fruitia", shelfName: "Apple Kiwi Crush", product: "applekiwicrush", blurb: `${blurbs["fruitia"]["applekiwicrush"]}`},
{brand: "fruitia", shelfName: "Blood Orange Cactus Cooler", product: "bloodorangecactuscooler", blurb: `${blurbs["fruitia"]["bloodorangecactuscooler"]}`},
{brand: "fruitia", shelfName: "Citrus Twist", product: "citrustwist", blurb: `${blurbs["fruitia"]["citrustwist"]}`},
{brand: "fruitia", shelfName: "Passion Fruit Guava Punch", product: "passionfruitguavapunch", blurb: `${blurbs["fruitia"]["passionfruitguavapunch"]}`},
{brand: "fruitia", shelfName: "Strawberry Coconut Refreshers", product: "strawberrycoconutrefreshers", blurb: `${blurbs["fruitia"]["strawberrycoconutrefreshers"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: `${blurbs["juicehead"]["blueberrylemon"]}`},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: `${blurbs["juicehead"]["peachpear"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: `${blurbs["juicehead"]["watermelonlime"]}`},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Fuji", product: "fuji", blurb: `${blurbs["pachamama"]["fuji"]}`},
{brand: "pachamama", shelfName: "Icy Mango", product: "icymango", blurb: `${blurbs["pachamama"]["icymango"]}`},
{brand: "pachamama", shelfName: "Sorbet", product: "sorbet", blurb: `${blurbs["pachamama"]["sorbet"]}`},
{brand: "pachamama", shelfName: "Strawberry Watermelon", product: "strawberrywatermelon", blurb: `${blurbs["pachamama"]["strawberrywatermelon"]}`},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Blue Raspberry", product: "blueraspberry", blurb: `${blurbs["podjuice"]["blueraspberry"]}`},
{brand: "podjuice", shelfName: "Jewel Mint", product: "jewelmint", blurb: `${blurbs["podjuice"]["jewelmint"]}`},
{brand: "podjuice", shelfName: "Jewel Mint Diamond", product: "jewelmintdiamond", blurb: `${blurbs["podjuice"]["jewelmintdiamond"]}`},
{brand: "podjuice", shelfName: "Jewel Mint Sapphire", product: "jewelmintsapphire", blurb: `${blurbs["podjuice"]["jewelmintsapphire"]}`},
{brand: "podjuice", shelfName: "Jewel Tobacco", product: "jeweltobacco", blurb: `${blurbs["podjuice"]["jeweltobacco"]}`},
{brand: "podjuice", shelfName: "Loops", product: "loops", blurb: `${blurbs["podjuice"]["loops"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: `${blurbs["riverreserve"]["blueislandpunch"]}`},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: `${blurbs["riverreserve"]["lemondrifter"]}`},
{brand: "riverreserve", shelfName: "Saltwater Creek", product: "saltwatercreek", blurb: `${blurbs["riverreserve"]["saltwatercreek"]}`},
{brand: "riverreserve", shelfName: "Summer Berry", product: "summerberry", blurb: `${blurbs["riverreserve"]["summerberry"]}`},
{brand: "riverreserve", shelfName: "Winter Berry", product: "winterberry", blurb: `${blurbs["riverreserve"]["winterberry"]}`},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Antidote on Ice", product: "antidoteonice", blurb: `${blurbs["ruthless"]["antidoteonice"]}`},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: `${blurbs["ruthless"]["ezduzit"]}`},
{brand: "ruthless", shelfName: "Ez Duz It on Ice", product: "ezduzitonice", blurb: `${blurbs["ruthless"]["ezduzitonice"]}`},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: `${blurbs["ruthless"]["grapedrank"]}`},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: `${blurbs["ruthless"]["grapedrankonice"]}`},
{brand: "ruthless", shelfName: "Paradise", product: "paradise", blurb: `${blurbs["ruthless"]["paradise"]}`},
{brand: "ruthless", shelfName: "Skir Skirr", product: "skirskirr", blurb: `${blurbs["ruthless"]["skirskirr"]}`},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: `${blurbs["ruthless"]["swampthang"]}`},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: `${blurbs["ruthless"]["tropicthunda"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Fairgrounds", product: "fairgrounds", blurb: `${blurbs["svrf"]["fairgrounds"]}`},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: `${blurbs["svrf"]["goldenticket"]}`},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: `${blurbs["svrf"]["pacificsangha"]}`},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Butter Cookie", product: "buttercookie", blurb: `${blurbs["sadboy"]["buttercookie"]}`},
{brand: "sadboy", shelfName: "Custard Cookie", product: "custardcookie", blurb: `${blurbs["sadboy"]["custardcookie"]}`},
{brand: "sadboy", shelfName: "Key Lime Cookie", product: "keylimecookie", blurb: `${blurbs["sadboy"]["keylimecookie"]}`},
{brand: "sadboy", shelfName: "Straw Jam Cookie", product: "strawjamcookie", blurb: `${blurbs["sadboy"]["strawjamcookie"]}`},
{brand: "shijinvapor", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijinvapor", shelfName: "Dragon", product: "dragon", blurb: `${blurbs["shijinvapor"]["dragon"]}`},
{brand: "shijinvapor", shelfName: "Phoenix", product: "phoenix", blurb: `${blurbs["shijinvapor"]["phoenix"]}`},
{brand: "shijinvapor", shelfName: "Tiger", product: "tiger", blurb: `${blurbs["shijinvapor"]["tiger"]}`},
{brand: "shijinvapor", shelfName: "Tortoise", product: "tortoise", blurb: `${blurbs["shijinvapor"]["tortoise"]}`},
{brand: "shijinvapor", shelfName: "Tortoise Ice", product: "tortoiseice", blurb: `${blurbs["shijinvapor"]["tortoiseice"]}`},
{brand: "shijinvapor", shelfName: "Tortoise On Ice", product: "tortoiseonice", blurb: `${blurbs["shijinvapor"]["tortoiseonice"]}`},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Banana Dragonberry", product: "bananadragonberry", blurb: `${blurbs["solace"]["bananadragonberry"]}`},
{brand: "solace", shelfName: "Berry Bash", product: "berrybash", blurb: `${blurbs["solace"]["berrybash"]}`},
{brand: "solace", shelfName: "Blue Raspberry Lemonade Ice", product: "blueraspberrylemonadeice", blurb: `${blurbs["solace"]["blueraspberrylemonadeice"]}`},
{brand: "solace", shelfName: "Blues Lemonade", product: "blueslemonade", blurb: `${blurbs["solace"]["blueslemonade"]}`},
{brand: "solace", shelfName: "Blues Mango", product: "bluesmango", blurb: `${blurbs["solace"]["bluesmango"]}`},
{brand: "solace", shelfName: "Cool Tobacco", product: "cooltobacco", blurb: `${blurbs["solace"]["cooltobacco"]}`},
{brand: "solace", shelfName: "Dragonthol", product: "dragonthol", blurb: `${blurbs["solace"]["dragonthol"]}`},
{brand: "solace", shelfName: "Grape", product: "grape", blurb: `${blurbs["solace"]["grape"]}`},
{brand: "solace", shelfName: "Juiced Apple", product: "juicedapple", blurb: `${blurbs["solace"]["juicedapple"]}`},
{brand: "solace", shelfName: "Lemon Lime Fusion", product: "lemonlimefusion", blurb: `${blurbs["solace"]["lemonlimefusion"]}`},
{brand: "solace", shelfName: "Mint", product: "mint", blurb: `${blurbs["solace"]["mint"]}`},
{brand: "solace", shelfName: "Pineapple", product: "pineapple", blurb: `${blurbs["solace"]["pineapple"]}`},
{brand: "solace", shelfName: "Sea Salt Blueberry", product: "seasaltblueberry", blurb: `${blurbs["solace"]["seasaltblueberry"]}`},
{brand: "solace", shelfName: "Seedless Watermelon", product: "seedlesswatermelon", blurb: `${blurbs["solace"]["seedlesswatermelon"]}`},
{brand: "solace", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["solace"]["strawberry"]}`},
{brand: "solace", shelfName: "Strawberry Kiwi Ice", product: "strawberrykiwiice", blurb: `${blurbs["solace"]["strawberrykiwiice"]}`},
];


let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
