let inventory = [


{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: "Strawberry and blueberry."},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: "Blue raspberry taffy"},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: "Also available in menthol."},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: "Nutmeg, cinnamon, glaze, and pastry."},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: "Mango taffy candy"},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: "Mango taffy candy, featuring menthol."},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: "Watermelon and honeydew taffy."},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: "Watermelon and honeydew taffy featuing menthol."},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: "Probably closer to mint, but that's okay."},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: "Mintier than menthol."},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: "A pool of 'mysterious berries.'"},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: "Kiwi, strawberry, menthol."},
{brand: "aqua", shelfName: " ", product: "logo", blurb: " "},
{brand: "aqua", shelfName: "Flow", product: "flow", blurb: "Pineapple, guava, mango."},
{brand: "aqua", shelfName: "Oasis", product: "oasis", blurb: "Peach, cataloupe, papaya."},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple", product: "grapeapple", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple Iced", product: "grapeappleiced", blurb: "undefined"},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Strawberry Iced", product: "grapestrawberryiced", blurb: "undefined"},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: " "},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz Iced", product: "peachbluerazziced", blurb: "undefined"},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: " "},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon Iced", product: "strawberrylemoniced", blurb: "With menthol."},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: " "},
{brand: "cloudnurdz", shelfName: "Watermelon Apple Iced", product: "watermelonappleiced", blurb: "With menthol."},
{brand: "coastalclouds", shelfName: " ", product: "logo", blurb: " "},
{brand: "coastalclouds", shelfName: "Apple Peach Strawberry", product: "applepeachstrawberry", blurb: " "},
{brand: "coastalclouds", shelfName: "Blood Orange Mango Snow Cone", product: "bloodorangemangosnowcone", blurb: " "},
{brand: "coastalclouds", shelfName: "Blueberry Banana Muffin", product: "blueberrybananamuffin", blurb: " "},
{brand: "coastalclouds", shelfName: "Blueberry Limeade", product: "blueberrylimeade", blurb: " "},
{brand: "coastalclouds", shelfName: "Guava Punch", product: "guavapunch", blurb: "Guava fruit punch."},
{brand: "coastalclouds", shelfName: "Iced Apple Peach Strawberry", product: "icedapplepeachstrawberry", blurb: " "},
{brand: "coastalclouds", shelfName: "Iced Blood Orange Mango Snow Cone", product: "icedbloodorangemangosnowcone", blurb: " "},
{brand: "coastalclouds", shelfName: "Iced Grape Berries", product: "icedgrapeberries", blurb: "undefined"},
{brand: "coastalclouds", shelfName: "Iced Mango Berries", product: "icedmangoberries", blurb: " "},
{brand: "coastalclouds", shelfName: "Iced Melon Berries", product: "icedmelonberries", blurb: "undefined"},
{brand: "coastalclouds", shelfName: "Iced Passion Fruit Orange Guava", product: "icedpassionfruitorangeguava", blurb: " "},
{brand: "coastalclouds", shelfName: "Mango Berries", product: "mangoberries", blurb: "undefined"},
{brand: "coastalclouds", shelfName: "Maple Butter", product: "maplebutter", blurb: " "},
{brand: "coastalclouds", shelfName: "Melon Berries", product: "melonberries", blurb: " "},
{brand: "coastalclouds", shelfName: "Peach Tea", product: "peachtea", blurb: "undefined"},
{brand: "coastalclouds", shelfName: "Pink Lemonade", product: "pinklemonade", blurb: " "},
{brand: "coastalclouds", shelfName: "Sugared Nectarine", product: "sugarednectarine", blurb: " "},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: "25% Toast, 25% Butter, 50% Blackberry Jam."},
{brand: "jammonster", shelfName: "Grape", product: "grape", blurb: "25% Toast, 25% Butter, 50% Grape Jam."},
{brand: "jammonster", shelfName: "Mangerine Guava ICE", product: "mangerineguavaice", blurb: "Mango, tangerine, guava, menthol."},
{brand: "jammonster", shelfName: "Melon Colada ICE", product: "meloncoladaice", blurb: "Melon, pineapple, coconut cream, and menthol."},
{brand: "jammonster", shelfName: "PB Jam Monster Grape", product: "pbjammonstergrape", blurb: "25% Toast, 25% Peanut Butter, 50% Grape Jam."},
{brand: "jammonster", shelfName: "PB Jam Monster Strawberry", product: "pbjammonsterstrawberry", blurb: "25% Toast, 25% Peanut Butter, 50% Strawberry Jam."},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: "25% Toast, 25% Butter, 50% Raspberry Jam."},
{brand: "jammonster", shelfName: "Strawberry", product: "strawberry", blurb: "25% Toast, 25% Butter, 50% Strawberry Jam."},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon Freeze", product: "blueberrylemonfreeze", blurb: "With menthol."},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: "With menthol."},
{brand: "loyalty", shelfName: " ", product: "logo", blurb: " "},
{brand: "loyalty", shelfName: "Berry Cake", product: "berrycake", blurb: "Mixed berries and vanilla cake batter."},
{brand: "loyalty", shelfName: "Double Shot", product: "doubleshot", blurb: "undefined"},
{brand: "loyalty", shelfName: "PomNAde Ice", product: "pomnadeice", blurb: "With menthol"},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: "Bold tobacco with a hint of something sweet."},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: "Plain and natural tobacco, middle of the road."},
{brand: "naked", shelfName: "Euro Gold", product: "eurogold", blurb: "Natural tobacco with vanilla custard."},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: "Passion fruit, orange, and guava."},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: "Strawberry, pineapple, and coconut."},
{brand: "naked", shelfName: "Menthol Brain Freeze", product: "mentholbrainfreeze", blurb: "undefined"},
{brand: "naked", shelfName: "Menthol Crisp Menthol", product: "mentholcrispmenthol", blurb: "undefined"},
{brand: "naked", shelfName: "Menthol Polar Breeze", product: "mentholpolarbreeze", blurb: "undefined"},
{brand: "naked", shelfName: "Menthol Very Cool", product: "mentholverycool", blurb: "undefined"},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: "Blue raspberry with a hint of lemon."},
{brand: "ofe", shelfName: " ", product: "logo", blurb: " "},
{brand: "ofe", shelfName: "Classic Gold", product: "classicgold", blurb: "Light tobacco."},
{brand: "ofe", shelfName: "Original Bold", product: "originalbold", blurb: "Bold tobacco."},
{brand: "ofe", shelfName: "Turkish Blend", product: "turkishblend", blurb: "Light, sweet tobacco."},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: "An icy cold hit to the back of your throat."},
{brand: "pnw", shelfName: "Arctic Tobacco", product: "arctictobacco", blurb: "Bold tobacco and menthol."},
{brand: "pnw", shelfName: "Blueberry Muffin", product: "blueberrymuffin", blurb: "Blueberries and vanilla muffin."},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: " "},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: "Just like the cereal"},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: "Sweet fruity cereal and milk."},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: "Soft vanilla cake batter."},
{brand: "pnw", shelfName: "NW", product: "nw", blurb: "undefined"},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: "Peaches and menthol"},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: "Also available in menthol."},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: "Menthol and mint leaf."},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: "Soft vanilla, hazelnut and coffee."},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Blood Orange Banana Gooseberry", product: "bloodorangebananagooseberry", blurb: "Ripe gooseberries are like sour grapes."},
{brand: "pachamama", shelfName: "Fuji Apple Strawberry Nectarine", product: "fujiapplestrawberrynectarine", blurb: " "},
{brand: "pachamama", shelfName: "Honeydew Berry Kiwi", product: "honeydewberrykiwi", blurb: "Honeydew, strawberry, kiwi."},
{brand: "pachamama", shelfName: "Huckleberry Pear Acai", product: "huckleberrypearacai", blurb: " "},
{brand: "pachamama", shelfName: "Mango Pitaya Pineapple", product: "mangopitayapineapple", blurb: "undefined"},
{brand: "pachamama", shelfName: "Strawberry Guava Jackfruit", product: "strawberryguavajackfruit", blurb: "Jackfruit is often compared to mango or pineapple."},
{brand: "ripevapes", shelfName: " ", product: "logo", blurb: " "},
{brand: "ripevapes", shelfName: "VCT Strawberry", product: "vctstrawberry", blurb: "undefined"},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: "Tobacco with blackberry custard."},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: "Blackberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: "Blue raspberry fruit punch."},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: "Caramel apple custard."},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: "Caramel, hazelnut, and marshmallows."},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: "Nothin! Just VG, PG, and nicotine."},
{brand: "riverreserve", shelfName: "Drifter", product: "drifter", blurb: "Whipped cream with blueberries."},
{brand: "riverreserve", shelfName: "Drifter X", product: "drifterx", blurb: "Whipped cream with blackberries."},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: "Mango pomegranate lemonade."},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: "Graham crackers and caramel adorned with shaved almonds, Kentucky bourbon and a splash of coconut cream."},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: "Fruit punch!"},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: "Whipped cream with tart lemon."},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: "Honeydew, lemonlime, and cherry."},
{brand: "riverreserve", shelfName: "Mild Tobacco", product: "mildtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Natural Tobacco", product: "naturaltobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Northwest", product: "northwest", blurb: "Vanilla, hazelnut, tobacco."},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: "Just like those little rootbeer barrel candies."},
{brand: "riverreserve", shelfName: "PBG", product: "pbg", blurb: "Peanut butter, banana, graham cracker."},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: " "},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: " "},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: "Raspberry and lemon."},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: "Tobacco with a hint of vanilla cream."},
{brand: "riverreserve", shelfName: "Strawberry Bandit", product: "strawberrybandit", blurb: "Strawberry custard and tobacco."},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: "Whipped cream with strawberries."},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: "Strawberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: "Whipped cream with strawberry and banana."},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: "Strawberries mixed with sweet vanilla custard."},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: "Strawberry and coconut."},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: "Tobacco with vanilla custard."},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: "Vanilla graham cracker with a brown sugar dusting."},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: "A scoop of vanilla ice cream atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: "Watermelon fruit punch with menthol."},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: "Watermelon and kiwi."},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Antidote On Ice", product: "antidoteonice", blurb: "Peach, mango, blue raspberry menthol."},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: "Strawberry watermelon."},
{brand: "ruthless", shelfName: "Ez Duz It On Ice", product: "ezduzitonice", blurb: "Strawberry watermelon and menthol."},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: "Grape soda."},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: "Grape soda with menthol."},
{brand: "ruthless", shelfName: "Jungle Fever", product: "junglefever", blurb: "Pineapple, mango, citrus."},
{brand: "ruthless", shelfName: "Paradize", product: "paradize", blurb: "Passion fruit, pear, and peaches."},
{brand: "ruthless", shelfName: "Rage", product: "rage", blurb: "Apple mango."},
{brand: "ruthless", shelfName: "Skir Skirr On Ice", product: "skirskirronice", blurb: "Honeydew melon, green apple, menthol."},
{brand: "ruthless", shelfName: "Slurricane", product: "slurricane", blurb: "Peach, papaya, and guava."},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: "Raspberry, kiwi, and strawberry."},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: "Sour candy apple."},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: "Guava and mixed berries."},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Fairground", product: "fairground", blurb: "Deep fried cream cake."},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: "Chocolate milk."},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: "Strawberry milk."},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Berrynola", product: "berrynola", blurb: "undefined"},
{brand: "sadboy", shelfName: "Butter Cookie", product: "buttercookie", blurb: "undefined"},
{brand: "sadboy", shelfName: "Key Lime Cookie", product: "keylimecookie", blurb: "undefined"},
{brand: "sadboy", shelfName: "Strawberry Jam Cookie", product: "strawberryjamcookie", blurb: "undefined"},
{brand: "sadboy", shelfName: "Strawnola", product: "strawnola", blurb: "undefined"},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon Cloud", product: "dragoncloud", blurb: "Cinnamon, sugar, vanilla ice cream, all on a savory pastry."},
{brand: "shijin", shelfName: "Tigers Milk", product: "tigersmilk", blurb: "Mangoes and peaches."},
{brand: "shijin", shelfName: "Tortoise Blood", product: "tortoiseblood", blurb: "Green apple, blue raspberry."},
{brand: "shijin", shelfName: "Tortoise on Ice", product: "tortoiseonice", blurb: "Green apple, blue raspberry with menthol."},
{brand: "thehypecollection", shelfName: " ", product: "logo", blurb: " "},
{brand: "thehypecollection", shelfName: "Blue Slushee", product: "blueslushee", blurb: "Blue raspberry slushee."},
{brand: "thehypecollection", shelfName: "Cool Blue Slushee", product: "coolblueslushee", blurb: "Blue raspberry slushee, featuring menthol."},
{brand: "thehypecollection", shelfName: "Cotton Candy", product: "cottoncandy", blurb: "Pink and blue, cotton candy."},
{brand: "transistor", shelfName: " ", product: "logo", blurb: " "},
{brand: "transistor", shelfName: "Galactic Milk", product: "galacticmilk", blurb: "undefined"},
{brand: "vapetasia", shelfName: " ", product: "logo", blurb: " "},
{brand: "vapetasia", shelfName: "Blackberry Lemonade", product: "blackberrylemonade", blurb: "Sweet and tart, blackberries and lemon."},
{brand: "vapetasia", shelfName: "Iced Blackberry Lemonade", product: "icedblackberrylemonade", blurb: "undefined"},
{brand: "vapetasia", shelfName: "Iced Pineapple Express", product: "icedpineappleexpress", blurb: "undefined"},
{brand: "vapetasia", shelfName: "Killer Kustard", product: "killerkustard", blurb: "Vanilla custard."},
{brand: "vapetasia", shelfName: "Milk of the Poppy", product: "milkofthepoppy", blurb: "undefined"},
{brand: "vapetasia", shelfName: "Pineapple Express", product: "pineappleexpress", blurb: "undefined"},
{brand: "vapetasia", shelfName: "Pink Lemonade", product: "pinklemonade", blurb: "undefined"},
{brand: "vapetasia", shelfName: "Rainbow Road", product: "rainbowroad", blurb: "Mixed fruit cereal, like the little circles."},
{brand: "vapetasia", shelfName: "Strawberry Killer Kustard", product: "strawberrykillerkustard", blurb: "Strawberry custard."},



];

let saltInventory = [
	

{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: "Strawberry and blueberry."},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: "Blue raspberry taffy"},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: "Also available in menthol."},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: "Smooth vanilla custard."},
{brand: "airfactory", shelfName: "Custard Tobacco", product: "custardtobacco", blurb: "Smooth vanilla custard with tobacco."},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: "Mango taffy candy"},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: "Mango taffy candy, featuring menthol."},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: "Watermelon and honeydew taffy."},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: "Watermelon and honeydew taffy featuing menthol."},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: "Probably closer to mint, but that's okay."},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: "Mintier than menthol."},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: "A pool of 'mysterious berries.'"},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: "Kiwi, strawberry, menthol."},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: " "},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: " "},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: " "},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: " "},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: "25% Toast, 25% Butter, 50% Blackberry Jam."},
{brand: "jammonster", shelfName: "Mangerine Guava", product: "mangerineguava", blurb: "undefined"},
{brand: "jammonster", shelfName: "Melon Colada", product: "meloncolada", blurb: "Melon, pineapple, and coconut cream."},
{brand: "jammonster", shelfName: "PBJam Strawberry", product: "pbjamstrawberry", blurb: "undefined"},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Fuji", product: "fuji", blurb: "undefined"},
{brand: "pachamama", shelfName: "Icy Mango", product: "icymango", blurb: "undefined"},
{brand: "pachamama", shelfName: "Sorbet", product: "sorbet", blurb: "undefined"},
{brand: "pachamama", shelfName: "Strawberry Watermelon", product: "strawberrywatermelon", blurb: "undefined"},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Blue Raspberry", product: "blueraspberry", blurb: "undefined"},
{brand: "podjuice", shelfName: "Jewel Mint", product: "jewelmint", blurb: "Just plain mint, little to no menthol."},
{brand: "podjuice", shelfName: "Jewel Mint Diamond", product: "jewelmintdiamond", blurb: "undefined"},
{brand: "podjuice", shelfName: "Jewel Mint Sapphire", product: "jewelmintsapphire", blurb: "Mint and menthol."},
{brand: "podjuice", shelfName: "Jewel Tobacco", product: "jeweltobacco", blurb: "undefined"},
{brand: "podjuice", shelfName: "Loops", product: "loops", blurb: "undefined"},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: "Blue raspberry fruit punch."},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: "Whipped cream with tart lemon."},
{brand: "riverreserve", shelfName: "Summer Berry", product: "summerberry", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Winter Berry", product: "winterberry", blurb: "undefined"},
{brand: "riverreserve", shelfName: "water Creek", product: "watercreek", blurb: "undefined"},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: "Strawberry watermelon."},
{brand: "ruthless", shelfName: "Ez Duz It on Ice", product: "ezduzitonice", blurb: "Strawberry watermelon and menthol."},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: "Grape soda."},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: "Grape soda with menthol."},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: "Sour candy apple."},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: "Guava and mixed berries."},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Fairgrounds", product: "fairgrounds", blurb: "Deep fried cream cake."},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: "Chocolate milk."},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: "Strawberry milk."},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Butter Cookie", product: "buttercookie", blurb: "undefined"},
{brand: "sadboy", shelfName: "Custard Cookie", product: "custardcookie", blurb: "undefined"},
{brand: "sadboy", shelfName: "Key Lime Cookie", product: "keylimecookie", blurb: "undefined"},
{brand: "sadboy", shelfName: "Straw Jam Cookie", product: "strawjamcookie", blurb: "undefined"},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon", product: "dragon", blurb: "Lemon tart."},
{brand: "shijin", shelfName: "Phoenix", product: "phoenix", blurb: "Guava lychee."},
{brand: "shijin", shelfName: "Tiger", product: "tiger", blurb: "Peach mango slushy."},
{brand: "shijin", shelfName: "Tortoise", product: "tortoise", blurb: "Green apple, blue raspberry."},
{brand: "shijin", shelfName: "Tortoise Ice", product: "tortoiseice", blurb: "undefined"},
{brand: "shijin", shelfName: "Tortoise On Ice", product: "tortoiseonice", blurb: "Green apple, blue raspberry with menthol."},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Banana Dragonberry", product: "bananadragonberry", blurb: "Dragonfruit and banana."},
{brand: "solace", shelfName: "Berry Bash", product: "berrybash", blurb: "Mixed berries."},
{brand: "solace", shelfName: "Blue Raspberry Lemonade Ice", product: "blueraspberrylemonadeice", blurb: "undefined"},
{brand: "solace", shelfName: "Blues Lemonade", product: "blueslemonade", blurb: "Lemonade with a hint of blue raspberry."},
{brand: "solace", shelfName: "Blues Mango", product: "bluesmango", blurb: "Mango with a hint of... blue raspberry."},
{brand: "solace", shelfName: "Cool Tobacco", product: "cooltobacco", blurb: "Classic tobacco with a bit of menthol."},
{brand: "solace", shelfName: "Dragonthol", product: "dragonthol", blurb: "Dragonfruit and menthol."},
{brand: "solace", shelfName: "Grape", product: "grape", blurb: " "},
{brand: "solace", shelfName: "Juiced Apple", product: "juicedapple", blurb: " "},
{brand: "solace", shelfName: "Lemon Lime Fusion", product: "lemonlimefusion", blurb: " "},
{brand: "solace", shelfName: "Mint", product: "mint", blurb: "undefined"},
{brand: "solace", shelfName: "Pineapple", product: "pineapple", blurb: " "},
{brand: "solace", shelfName: "Sea Blueberry", product: "seablueberry", blurb: " "},
{brand: "solace", shelfName: "Seedless Watermelon", product: "seedlesswatermelon", blurb: "There actually are seeds, be careful."},
{brand: "solace", shelfName: "Strawberry", product: "strawberry", blurb: "Strawberry kiwi with menthol."},
{brand: "solace", shelfName: "Strawberry Kiwi Ice", product: "strawberrykiwiice", blurb: "Strawberry kiwi with menthol."},


];

let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
