let inventory = [
	

{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: " "},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: " "},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: " "},
{brand: "fivepawnsorchard", shelfName: " ", product: "logo", blurb: " "},
{brand: "fivepawnsorchard", shelfName: "Berry Limeade", product: "berrylimeade", blurb: `${blurbs["fivepawnsorchard"]["berrylimeade"]}`},
{brand: "fivepawnsorchard", shelfName: "Mango Passion", product: "mangopassion", blurb: "undefined"},
{brand: "fivepawnsorchard", shelfName: "Melon Mash", product: "melonmash", blurb: "undefined"},
{brand: "fivepawnsorchard", shelfName: "Nana Berry", product: "nanaberry", blurb: "undefined"},
{brand: "fivepawnsorchard", shelfName: "Pineapple Kiwi", product: "pineapplekiwi", blurb: "undefined"},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: "25% Toast, 25% Butter, 50% Blackberry Jam."},
{brand: "jammonster", shelfName: "Blueberry", product: "blueberry", blurb: "25% Toast, 25% Butter, 50% Blueberry Jam."},
{brand: "jammonster", shelfName: "Grape", product: "grape", blurb: "25% Toast, 25% Butter, 50% Grape Jam."},
{brand: "jammonster", shelfName: "Mangerine Guava ICE", product: "mangerineguavaice", blurb: "Mango, tangerine, guava, menthol."},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: "25% Toast, 25% Butter, 50% Raspberry Jam."},
{brand: "jammonster", shelfName: "Strawberry Custard", product: "strawberrycustard", blurb: "undefined"},
{brand: "jammonster", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: "Plain vanilla custard."},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi Freeze", product: "strawberrykiwifreeze", blurb: "undefined"},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: "With menthol."},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Banana Amber", product: "bananaamber", blurb: "Oatmeal Cookie, Banana."},
{brand: "lemontwist", shelfName: "Chilled Melon Remix", product: "chilledmelonremix", blurb: "undefined"},
{brand: "lemontwist", shelfName: "Dragonthol", product: "dragonthol", blurb: "undefined"},
{brand: "lemontwist", shelfName: "Honeydew Melon Chew", product: "honeydewmelonchew", blurb: "Watermelon and honeydew."},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: "Pink lemonade with menthol."},
{brand: "lemontwist", shelfName: "Pampaya", product: "pampaya", blurb: "undefined"},
{brand: "lemontwist", shelfName: "Pink Punch", product: "pinkpunch", blurb: "undefined"},
{brand: "lemontwist", shelfName: "Purple Grape", product: "purplegrape", blurb: "undefined"},
{brand: "lemontwist", shelfName: "Strawberry Mason", product: "strawberrymason", blurb: "undefined"},
{brand: "lemontwist", shelfName: "Wild Watermelon", product: "wildwatermelon", blurb: "undefined"},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: "Plain and natural tobacco, middle of the road."},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: "Passion fruit, orange, and guava."},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: "Strawberry, pineapple, and coconut."},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: "An icy cold hit to the back of your throat."},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: " "},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: "Just like the cereal"},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: "Sweet fruity cereal and milk."},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: "Soft vanilla cake batter."},
{brand: "pnw", shelfName: "NW", product: "nw", blurb: "undefined"},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: "Peaches and menthol"},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: "Also available in menthol."},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: "Menthol and mint leaf."},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: "Soft vanilla, hazelnut and coffee."},
{brand: "reds", shelfName: " ", product: "logo", blurb: " "},
{brand: "reds", shelfName: "Apple", product: "apple", blurb: " "},
{brand: "reds", shelfName: "Berries", product: "berries", blurb: " "},
{brand: "reds", shelfName: "Grape", product: "grape", blurb: " "},
{brand: "reds", shelfName: "Guava", product: "guava", blurb: " "},
{brand: "reds", shelfName: "Strawberry", product: "strawberry", blurb: " "},
{brand: "reds", shelfName: "Watermelon", product: "watermelon", blurb: " "},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Acid Worm", product: "acidworm", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: "Blackberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: "Blue raspberry fruit punch."},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: "Caramel, hazelnut, and marshmallows."},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: "Coconut, watermelon, and mango."},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: "Nothin! Just VG, PG, and nicotine."},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: "Mango pomegranate lemonade."},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: "Graham crackers and caramel adorned with shaved almonds, Kentucky bourbon and a splash of coconut cream."},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: "Fruit punch!"},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: "Whipped cream with tart lemon."},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: "Honeydew, lemonlime, and cherry."},
{brand: "riverreserve", shelfName: "Natural Tobacco", product: "naturaltobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: " "},
{brand: "riverreserve", shelfName: "Pebbles Cheesecake", product: "pebblescheesecake", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: "undefined"},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: "Raspberry and lemon."},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: "Pineapple coconut rum."},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: "Tobacco with a hint of vanilla cream."},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: "Whipped cream with strawberries."},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: "Strawberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: "Whipped cream with strawberry and banana."},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: "Strawberries mixed with sweet vanilla custard."},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: "Strawberry and coconut."},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: "Tobacco with vanilla custard."},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: "Vanilla graham cracker with a brown sugar dusting."},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: "A scoop of vanilla ice cream atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: "Watermelon fruit punch with menthol."},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: "Watermelon and kiwi."},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: "undefined"},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: "undefined"},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: "undefined"},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon Cloud", product: "dragoncloud", blurb: "Cinnamon, sugar, vanilla ice cream, all on a savory pastry."},
{brand: "shijin", shelfName: "Phoenix Tears", product: "phoenixtears", blurb: "Sugar cookie with vanilla custard."},
{brand: "shijin", shelfName: "Tigers Milk", product: "tigersmilk", blurb: "Mangoes and peaches."},
{brand: "shijin", shelfName: "Tortoise Blood", product: "tortoiseblood", blurb: "Green apple, blue raspberry."},
{brand: "shijin", shelfName: "Tortoise on Ice", product: "tortoiseonice", blurb: "Green apple, blue raspberry with menthol."},
{brand: "silverback", shelfName: " ", product: "logo", blurb: " "},
{brand: "silverback", shelfName: "Amy", product: "amy", blurb: "Vanilla, caramel, and peanut butter brittle."},
{brand: "silverback", shelfName: "BooBoo", product: "booboo", blurb: "Grape and blueberry."},
{brand: "silverback", shelfName: "Harambe", product: "harambe", blurb: "Cinnamon and cream liqueur."},
{brand: "silverback", shelfName: "Jenny", product: "jenny", blurb: "Strawberry, bubblegum, mint."},
{brand: "silverback", shelfName: "Lola", product: "lola", blurb: "Strawberry, banana, dragonfruit."},
{brand: "silverback", shelfName: "Sandy", product: "sandy", blurb: "Strawberry watermelon."},
{brand: "skwezed", shelfName: " ", product: "logo", blurb: " "},
{brand: "skwezed", shelfName: "Grapefruit", product: "grapefruit", blurb: " "},
{brand: "skwezed", shelfName: "Green Apple", product: "greenapple", blurb: " "},
{brand: "skwezed", shelfName: "Mango", product: "mango", blurb: " "},
{brand: "skwezed", shelfName: "Watermelon", product: "watermelon", blurb: " "},



];

let saltInventory = [
	

{brand: "fivepawnsorchard", shelfName: " ", product: "logo", blurb: " "},
{brand: "fivepawnsorchard", shelfName: "Berry Limeade", product: "berrylimeade", blurb: `asdasd`},
{brand: "fivepawnsorchard", shelfName: "Mango Passion", product: "mangopassion", blurb: "undefined"},
{brand: "fivepawnsorchard", shelfName: "Melon Mash", product: "melonmash", blurb: "undefined"},
{brand: "fivepawnsorchard", shelfName: "Nana Berry", product: "nanaberry", blurb: "undefined"},
{brand: "fivepawnsorchard", shelfName: "Pineapple Kiwi", product: "pineapplekiwi", blurb: "undefined"},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Strawberry Custard", product: "strawberrycustard", blurb: "undefined"},
{brand: "jammonster", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: "Plain vanilla custard."},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Honeydew Melon Chew", product: "honeydewmelonchew", blurb: "Watermelon and honeydew."},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: "Pink lemonade with menthol."},
{brand: "lemontwist", shelfName: "Pink Punch Lemonade", product: "pinkpunchlemonade", blurb: "Pink punch lemonade."},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: "Watermelon and lemonade."},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: "undefined"},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: "undefined"},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: "undefined"},
{brand: "shijinvapor", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijinvapor", shelfName: "Dragon", product: "dragon", blurb: "Lemon tart."},
{brand: "shijinvapor", shelfName: "Phoenix", product: "phoenix", blurb: "Guava lychee."},
{brand: "shijinvapor", shelfName: "Tiger", product: "tiger", blurb: "Peach mango slushy."},
{brand: "shijinvapor", shelfName: "Tortoise", product: "tortoise", blurb: "Green apple, blue raspberry."},
{brand: "shijinvapor", shelfName: "Tortoise Ice", product: "tortoiseice", blurb: "undefined"},
{brand: "skwezed", shelfName: " ", product: "logo", blurb: " "},
{brand: "skwezed", shelfName: "Grapefruit", product: "grapefruit", blurb: " "},
{brand: "skwezed", shelfName: "Green Apple", product: "greenapple", blurb: " "},
{brand: "skwezed", shelfName: "Lychee", product: "lychee", blurb: " "},
{brand: "skwezed", shelfName: "Mango", product: "mango", blurb: " "},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Banana Dragonberry", product: "bananadragonberry", blurb: "Dragonfruit and banana."},
{brand: "solace", shelfName: "Berry Bash", product: "berrybash", blurb: "Mixed berries."},
{brand: "solace", shelfName: "Blue Raspberry Lemonade Ice", product: "blueraspberrylemonadeice", blurb: "undefined"},
{brand: "solace", shelfName: "Blues Lemonade", product: "blueslemonade", blurb: "Lemonade with a hint of blue raspberry."},
{brand: "solace", shelfName: "Blues Mango", product: "bluesmango", blurb: "Mango with a hint of... blue raspberry."},
{brand: "solace", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: "undefined"},
{brand: "solace", shelfName: "Cool Tobacco", product: "cooltobacco", blurb: "Classic tobacco with a bit of menthol."},
{brand: "solace", shelfName: "Dragonthol", product: "dragonthol", blurb: "Dragonfruit and menthol."},
{brand: "solace", shelfName: "Grape", product: "grape", blurb: " "},
{brand: "solace", shelfName: "Mint", product: "mint", blurb: "undefined"},
{brand: "solace", shelfName: "Pineapple", product: "pineapple", blurb: " "},
{brand: "solace", shelfName: "Sea Blueberry", product: "seablueberry", blurb: " "},
{brand: "solace", shelfName: "Seedless Watermelon", product: "seedlesswatermelon", blurb: "There actually are seeds, be careful."},
{brand: "solace", shelfName: "Strawberry", product: "strawberry", blurb: "Strawberry kiwi with menthol."},
{brand: "solace", shelfName: "Strawberry Kiwi Ice", product: "strawberrykiwiice", blurb: "Strawberry kiwi with menthol."},
{brand: "solace", shelfName: "Tropic Strawberry", product: "tropicstrawberry", blurb: " "},
{brand: "twistedtongue", shelfName: " ", product: "logo", blurb: " "},
{brand: "twistedtongue", shelfName: "French Vanilla", product: "frenchvanilla", blurb: "undefined"},
{brand: "twistedtongue", shelfName: "Fruit Cereal Milk", product: "fruitcerealmilk", blurb: "undefined"},

];

let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
