
let inventory = [
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: `${blurbs["cloudnurdz"]["grapestrawberry"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: `${blurbs["cloudnurdz"]["peachbluerazz"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: `${blurbs["cloudnurdz"]["watermelonapple"]}`},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: `${blurbs["jammonster"]["blackberry"]}`},
{brand: "jammonster", shelfName: "Blueberry", product: "blueberry", blurb: `${blurbs["jammonster"]["blueberry"]}`},
{brand: "jammonster", shelfName: "Grape", product: "grape", blurb: `${blurbs["jammonster"]["grape"]}`},
{brand: "jammonster", shelfName: "Mangerine Guava ICE", product: "mangerineguavaice", blurb: `${blurbs["jammonster"]["mangerineguavaice"]}`},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: `${blurbs["jammonster"]["raspberry"]}`},
{brand: "jammonster", shelfName: "Strawberry Custard", product: "strawberrycustard", blurb: `${blurbs["jammonster"]["strawberrycustard"]}`},
{brand: "jammonster", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: `${blurbs["jammonster"]["vanillacustard"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: `${blurbs["juicehead"]["blueberrylemon"]}`},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: `${blurbs["juicehead"]["peachpear"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi Freeze", product: "strawberrykiwifreeze", blurb: `${blurbs["juicehead"]["strawberrykiwifreeze"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: `${blurbs["juicehead"]["watermelonlime"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: `${blurbs["juicehead"]["watermelonlimefreeze"]}`},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Banana Amber", product: "bananaamber", blurb: `${blurbs["lemontwist"]["bananaamber"]}`},
{brand: "lemontwist", shelfName: "Chilled Melon Remix", product: "chilledmelonremix", blurb: `${blurbs["lemontwist"]["chilledmelonremix"]}`},
{brand: "lemontwist", shelfName: "Dragonthol", product: "dragonthol", blurb: `${blurbs["lemontwist"]["dragonthol"]}`},
{brand: "lemontwist", shelfName: "Honeydew Melon Chew", product: "honeydewmelonchew", blurb: `${blurbs["lemontwist"]["honeydewmelonchew"]}`},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: `${blurbs["lemontwist"]["icedpinkpunchlemonade"]}`},
{brand: "lemontwist", shelfName: "Pampaya", product: "pampaya", blurb: `${blurbs["lemontwist"]["pampaya"]}`},
{brand: "lemontwist", shelfName: "Pink Punch", product: "pinkpunch", blurb: `${blurbs["lemontwist"]["pinkpunch"]}`},
{brand: "lemontwist", shelfName: "Purple Grape", product: "purplegrape", blurb: `${blurbs["lemontwist"]["purplegrape"]}`},
{brand: "lemontwist", shelfName: "Strawberry Mason", product: "strawberrymason", blurb: `${blurbs["lemontwist"]["strawberrymason"]}`},
{brand: "lemontwist", shelfName: "Wild Watermelon", product: "wildwatermelon", blurb: `${blurbs["lemontwist"]["wildwatermelon"]}`},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: `${blurbs["naked"]["cubanblend"]}`},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: `${blurbs["naked"]["hawaiianpog"]}`},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: `${blurbs["naked"]["lavaflow"]}`},
{brand: "northwestfinest", shelfName: " ", product: "logo", blurb: " "},
{brand: "northwestfinest", shelfName: "Rockin Seas", product: "rockinseas", blurb: `${blurbs["northwestfinest"]["rockinseas"]}`},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: `${blurbs["pnw"]["arcticfrost"]}`},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: `${blurbs["pnw"]["cherrylimeade"]}`},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: `${blurbs["pnw"]["cinnamoncrunch"]}`},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: `${blurbs["pnw"]["fruityos"]}`},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: `${blurbs["pnw"]["madbatter"]}`},
{brand: "pnw", shelfName: "NW", product: "nw", blurb: `${blurbs["pnw"]["nw"]}`},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: `${blurbs["pnw"]["peachfrost"]}`},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: `${blurbs["pnw"]["peaches"]}`},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: `${blurbs["pnw"]["spearmint"]}`},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: `${blurbs["pnw"]["vanillanutlatte"]}`},
{brand: "reds", shelfName: " ", product: "logo", blurb: " "},
{brand: "reds", shelfName: "Apple", product: "apple", blurb: `${blurbs["reds"]["apple"]}`},
{brand: "reds", shelfName: "Berries", product: "berries", blurb: `${blurbs["reds"]["berries"]}`},
{brand: "reds", shelfName: "Grape", product: "grape", blurb: `${blurbs["reds"]["grape"]}`},
{brand: "reds", shelfName: "Guava", product: "guava", blurb: `${blurbs["reds"]["guava"]}`},
{brand: "reds", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["reds"]["strawberry"]}`},
{brand: "reds", shelfName: "Watermelon", product: "watermelon", blurb: `${blurbs["reds"]["watermelon"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Acid Worm", product: "acidworm", blurb: `${blurbs["riverreserve"]["acidworm"]}`},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: `${blurbs["riverreserve"]["blackberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: `${blurbs["riverreserve"]["blueislandpunch"]}`},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: `${blurbs["riverreserve"]["boldtobacco"]}`},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: `${blurbs["riverreserve"]["caramelcove"]}`},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: `${blurbs["riverreserve"]["castaway"]}`},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: `${blurbs["riverreserve"]["clearwatercreek"]}`},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: `${blurbs["riverreserve"]["eddy"]}`},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: `${blurbs["riverreserve"]["greatwall"]}`},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: `${blurbs["riverreserve"]["islandpunch"]}`},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: `${blurbs["riverreserve"]["lemondrifter"]}`},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: `${blurbs["riverreserve"]["midorisour"]}`},
{brand: "riverreserve", shelfName: "Natural Tobacco", product: "naturaltobacco", blurb: `${blurbs["riverreserve"]["naturaltobacco"]}`},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: `${blurbs["riverreserve"]["peachmangolemonade"]}`},
{brand: "riverreserve", shelfName: "Pebbles Cheesecake", product: "pebblescheesecake", blurb: `${blurbs["riverreserve"]["pebblescheesecake"]}`},
{brand: "riverreserve", shelfName: "Raspberry Crumble", product: "raspberrycrumble", blurb: `${blurbs["riverreserve"]["raspberrycrumble"]}`},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: `${blurbs["riverreserve"]["raspberrylemonitalianice"]}`},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: `${blurbs["riverreserve"]["rivercolada"]}`},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: `${blurbs["riverreserve"]["smoothsweettobacco"]}`},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: `${blurbs["riverreserve"]["strawberrydrifter"]}`},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: `${blurbs["riverreserve"]["strawberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: `${blurbs["riverreserve"]["strawnanadrifter"]}`},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: `${blurbs["riverreserve"]["swampmama"]}`},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: `${blurbs["riverreserve"]["tigersblood"]}`},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: `${blurbs["riverreserve"]["vanillabandit"]}`},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: `${blurbs["riverreserve"]["vanillagraham"]}`},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: `${blurbs["riverreserve"]["vanillawafflecone"]}`},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: `${blurbs["riverreserve"]["watermelonpunchmenthol"]}`},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: `${blurbs["riverreserve"]["wiki"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Balanced", product: "balanced", blurb: `${blurbs["svrf"]["balanced"]}`},
{brand: "svrf", shelfName: "Refreshing", product: "refreshing", blurb: `${blurbs["svrf"]["refreshing"]}`},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: `${blurbs["svrf"]["satisfying"]}`},
{brand: "silverback", shelfName: " ", product: "logo", blurb: " "},
{brand: "silverback", shelfName: "Amy", product: "amy", blurb: `${blurbs["silverback"]["amy"]}`},
{brand: "silverback", shelfName: "BooBoo", product: "booboo", blurb: `${blurbs["silverback"]["booboo"]}`},
{brand: "silverback", shelfName: "Harambe", product: "harambe", blurb: `${blurbs["silverback"]["harambe"]}`},
{brand: "silverback", shelfName: "Jenny", product: "jenny", blurb: `${blurbs["silverback"]["jenny"]}`},
{brand: "silverback", shelfName: "Lola", product: "lola", blurb: `${blurbs["silverback"]["lola"]}`},
{brand: "silverback", shelfName: "Sandy", product: "sandy", blurb: `${blurbs["silverback"]["sandy"]}`},
{brand: "skwezed", shelfName: " ", product: "logo", blurb: " "},
{brand: "skwezed", shelfName: "Grapefruit", product: "grapefruit", blurb: `${blurbs["skwezed"]["grapefruit"]}`},
{brand: "skwezed", shelfName: "Mango", product: "mango", blurb: `${blurbs["skwezed"]["mango"]}`},
{brand: "skwezed", shelfName: "Watermelon", product: "watermelon", blurb: `${blurbs["skwezed"]["watermelon"]}`},
];
let saltInventory = [
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Strawberry Custard", product: "strawberrycustard", blurb: `${blurbs["jammonster"]["strawberrycustard"]}`},
{brand: "jammonster", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: `${blurbs["jammonster"]["vanillacustard"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: `${blurbs["juicehead"]["blueberrylemon"]}`},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: `${blurbs["juicehead"]["peachpear"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: `${blurbs["juicehead"]["watermelonlime"]}`},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Honeydew Melon Chew", product: "honeydewmelonchew", blurb: `${blurbs["lemontwist"]["honeydewmelonchew"]}`},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: `${blurbs["lemontwist"]["icedpinkpunchlemonade"]}`},
{brand: "lemontwist", shelfName: "Pink Punch Lemonade", product: "pinkpunchlemonade", blurb: `${blurbs["lemontwist"]["pinkpunchlemonade"]}`},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: `${blurbs["lemontwist"]["watermelonmadness"]}`},
{brand: "lemontwist", shelfName: "Honeydew Melon Chew", product: "honeydewmelonchew", blurb: `${blurbs["lemontwist"]["honeydewmelonchew"]}`},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: `${blurbs["lemontwist"]["watermelonmadness"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "s Balanced", product: "sbalanced", blurb: `${blurbs["svrf"]["sbalanced"]}`},
{brand: "svrf", shelfName: "s Refreshing", product: "srefreshing", blurb: `${blurbs["svrf"]["srefreshing"]}`},
{brand: "svrf", shelfName: "s Satisfying", product: "ssatisfying", blurb: `${blurbs["svrf"]["ssatisfying"]}`},
{brand: "shijinvapor", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijinvapor", shelfName: "Salt Nic Dragon", product: "saltnicdragon", blurb: `${blurbs["shijinvapor"]["saltnicdragon"]}`},
{brand: "shijinvapor", shelfName: "Salt Nic Phoenix", product: "saltnicphoenix", blurb: `${blurbs["shijinvapor"]["saltnicphoenix"]}`},
{brand: "shijinvapor", shelfName: "Salt Nic Tiger", product: "saltnictiger", blurb: `${blurbs["shijinvapor"]["saltnictiger"]}`},
{brand: "shijinvapor", shelfName: "Salt Nic Tortoise", product: "saltnictortoise", blurb: `${blurbs["shijinvapor"]["saltnictortoise"]}`},
{brand: "shijinvapor", shelfName: "Salt Nic Tortoise Ice", product: "saltnictortoiseice", blurb: `${blurbs["shijinvapor"]["saltnictortoiseice"]}`},
{brand: "skwezed", shelfName: " ", product: "logo", blurb: " "},
{brand: "skwezed", shelfName: "Grapefruit", product: "grapefruit", blurb: `${blurbs["skwezed"]["grapefruit"]}`},
{brand: "skwezed", shelfName: "Green Apple", product: "greenapple", blurb: `${blurbs["skwezed"]["greenapple"]}`},
{brand: "skwezed", shelfName: "Lychee", product: "lychee", blurb: `${blurbs["skwezed"]["lychee"]}`},
{brand: "skwezed", shelfName: "Mango", product: "mango", blurb: `${blurbs["skwezed"]["mango"]}`},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "s Banana Dragonberry", product: "sbananadragonberry", blurb: `${blurbs["solace"]["sbananadragonberry"]}`},
{brand: "solace", shelfName: "s Berry Bash", product: "sberrybash", blurb: `${blurbs["solace"]["sberrybash"]}`},
{brand: "solace", shelfName: "s Blue Raspberry Lemonade Ice", product: "sblueraspberrylemonadeice", blurb: `${blurbs["solace"]["sblueraspberrylemonadeice"]}`},
{brand: "solace", shelfName: "s Blues Lemonade", product: "sblueslemonade", blurb: `${blurbs["solace"]["sblueslemonade"]}`},
{brand: "solace", shelfName: "s Blues Mango", product: "sbluesmango", blurb: `${blurbs["solace"]["sbluesmango"]}`},
{brand: "solace", shelfName: "s Bold Tobacco", product: "sboldtobacco", blurb: `${blurbs["solace"]["sboldtobacco"]}`},
{brand: "solace", shelfName: "s Cool Tobacco", product: "scooltobacco", blurb: `${blurbs["solace"]["scooltobacco"]}`},
{brand: "solace", shelfName: "s Dragonthol", product: "sdragonthol", blurb: `${blurbs["solace"]["sdragonthol"]}`},
{brand: "solace", shelfName: "s Grape", product: "sgrape", blurb: `${blurbs["solace"]["sgrape"]}`},
{brand: "solace", shelfName: "s Mint", product: "smint", blurb: `${blurbs["solace"]["smint"]}`},
{brand: "solace", shelfName: "s Pineapple", product: "spineapple", blurb: `${blurbs["solace"]["spineapple"]}`},
{brand: "solace", shelfName: "s Sea Salt Blueberry", product: "sseasaltblueberry", blurb: `${blurbs["solace"]["sseasaltblueberry"]}`},
{brand: "solace", shelfName: "s Seedless Watermelon", product: "sseedlesswatermelon", blurb: `${blurbs["solace"]["sseedlesswatermelon"]}`},
{brand: "solace", shelfName: "s Strawberry", product: "sstrawberry", blurb: `${blurbs["solace"]["sstrawberry"]}`},
{brand: "solace", shelfName: "s Strawberry Kiwi Ice", product: "sstrawberrykiwiice", blurb: `${blurbs["solace"]["sstrawberrykiwiice"]}`},
{brand: "solace", shelfName: "s Tropic Strawberry", product: "stropicstrawberry", blurb: `${blurbs["solace"]["stropicstrawberry"]}`},
{brand: "twistedtongue", shelfName: " ", product: "logo", blurb: " "},
{brand: "twistedtongue", shelfName: "French Vanilla", product: "frenchvanilla", blurb: `${blurbs["twistedtongue"]["frenchvanilla"]}`},
{brand: "twistedtongue", shelfName: "Fruit Cereal Milk", product: "fruitcerealmilk", blurb: `${blurbs["twistedtongue"]["fruitcerealmilk"]}`},
{brand: "yogi", shelfName: " ", product: "logo", blurb: " "},
{brand: "yogi", shelfName: "Vanilla Tobacco Granola Bar", product: "vanillatobaccogranolabar", blurb: `${blurbs["yogi"]["vanillatobaccogranolabar"]}`},
];


let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
