let inventory = [
	

{brand: "aqua", shelfName: " ", product: "logo", blurb: " "},
{brand: "aqua", shelfName: "Flow", product: "flow", blurb: "Pineapple, guava, mango."},
{brand: "aqua", shelfName: "Oasis", product: "oasis", blurb: "Peach, cataloupe, papaya."},
{brand: "aqua", shelfName: "Pure", product: "pure", blurb: "Strawberry, apple, and watermelon."},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: " "},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: " "},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon Iced", product: "strawberrylemoniced", blurb: "With menthol."},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: " "},
{brand: "cloudnurdz", shelfName: "Watermelon Apple Iced", product: "watermelonappleiced", blurb: "With menthol."},
{brand: "coastalclouds", shelfName: " ", product: "logo", blurb: " "},
{brand: "coastalclouds", shelfName: "Blood Orange Mango Snow Cone", product: "bloodorangemangosnowcone", blurb: " "},
{brand: "coastalclouds", shelfName: "Blueberry Banana Muffin", product: "blueberrybananamuffin", blurb: " "},
{brand: "coastalclouds", shelfName: "Blueberry Limeade", product: "blueberrylimeade", blurb: " "},
{brand: "coastalclouds", shelfName: "Guava Punch", product: "guavapunch", blurb: "Guava fruit punch."},
{brand: "coastalclouds", shelfName: "Iced Blood Orange Mango Snow Cone", product: "icedbloodorangemangosnowcone", blurb: " "},
{brand: "coastalclouds", shelfName: "Iced Passion Fruit Orange Guava", product: "icedpassionfruitorangeguava", blurb: "With menthol."},
{brand: "coastalclouds", shelfName: "Sugared Nectarine", product: "sugarednectarine", blurb: " "},
{brand: "coastalclouds", shelfName: "The Abyss", product: "theabyss", blurb: " "},
{brand: "coastalclouds", shelfName: "The Voyage", product: "thevoyage", blurb: " "},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: "25% Toast, 25% Butter, 50% Blackberry Jam."},
{brand: "jammonster", shelfName: "Blueberry", product: "blueberry", blurb: "25% Toast, 25% Butter, 50% Blueberry Jam."},
{brand: "jammonster", shelfName: "Blueberry Raspberry Lemon", product: "blueberryraspberrylemon", blurb: " "},
{brand: "jammonster", shelfName: "Grape", product: "grape", blurb: "25% Toast, 25% Butter, 50% Grape Jam."},
{brand: "jammonster", shelfName: "Mangerine Guava ICE", product: "mangerineguavaice", blurb: "Mango, tangerine, guava, menthol."},
{brand: "jammonster", shelfName: "Mango Peach Guava", product: "mangopeachguava", blurb: " "},
{brand: "jammonster", shelfName: "Melon Colada ICE", product: "meloncoladaice", blurb: "Melon, pineapple, coconut cream, and menthol."},
{brand: "jammonster", shelfName: "Mixed Berry", product: "mixedberry", blurb: "25% Toast, 25% Butter, 50% Strawberry, Blueberry, and Raspberry Jam. How exciting."},
{brand: "jammonster", shelfName: "PB Jam Monster Grape", product: "pbjammonstergrape", blurb: "25% Toast, 25% Peanut Butter, 50% Grape Jam."},
{brand: "jammonster", shelfName: "PB Jam Monster Strawberry", product: "pbjammonsterstrawberry", blurb: "25% Toast, 25% Peanut Butter, 50% Strawberry Jam."},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: "25% Toast, 25% Butter, 50% Raspberry Jam."},
{brand: "jammonster", shelfName: "Strawberry", product: "strawberry", blurb: "25% Toast, 25% Butter, 50% Strawberry Jam."},
{brand: "jammonster", shelfName: "Strawberry Kiwi Pomegranate", product: "strawberrykiwipomegranate", blurb: " "},
{brand: "jammonster", shelfName: "Strawmelon Apple ICE", product: "strawmelonappleice", blurb: "Strawberry watermelon menthol."},
{brand: "jammonster", shelfName: "Vanilla Custard", product: "vanillacustard", blurb: "Plain vanilla custard."},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon Freeze", product: "blueberrylemonfreeze", blurb: "With menthol."},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: " "},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: "With menthol."},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Crimson No 1 Strawberry Mason", product: "crimsonno1strawberrymason", blurb: "Strawberry lemonade."},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: "Bold tobacco with a hint of something sweet."},
{brand: "naked", shelfName: "Brain Freeze", product: "brainfreeze", blurb: "Strawberry pomegranate menthol."},
{brand: "naked", shelfName: "Crisp Menthol", product: "crispmenthol", blurb: "Just plain menthol."},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: "Passion fruit, orange, and guava."},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: "Strawberry, pineapple, and coconut."},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: "Blue raspberry with a hint of lemon."},
{brand: "naked", shelfName: "Very Cool", product: "verycool", blurb: "Blue raspberry menthol."},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: "An icy cold hit to the back of your throat."},
{brand: "pnw", shelfName: "Arctic Tobacco", product: "arctictobacco", blurb: "Bold tobacco and menthol."},
{brand: "pnw", shelfName: "Blueberry Muffin", product: "blueberrymuffin", blurb: "Blueberries and vanilla muffin."},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: " "},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: "Just like the cereal"},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: "Sweet fruity cereal and milk."},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: "Soft vanilla cake batter."},
{brand: "pnw", shelfName: "NW4", product: "nw4", blurb: "Vanilla caramel tobacco."},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: "Peaches and menthol"},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: "Also available in menthol."},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: "Menthol and mint leaf."},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: "Soft vanilla, hazelnut and coffee."},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: "Tobacco with blackberry custard."},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: "Blackberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: "Blue raspberry fruit punch."},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: "Caramel, hazelnut, and marshmallows."},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: "Nothin! Just VG, PG, and nicotine."},
{brand: "riverreserve", shelfName: "Drifter", product: "drifter", blurb: "Whipped cream with blueberries."},
{brand: "riverreserve", shelfName: "Drifter X", product: "drifterx", blurb: "Whipped cream with blackberries."},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: "Mango pomegranate lemonade."},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: "Graham crackers and caramel adorned with shaved almonds, Kentucky bourbon and a splash of coconut cream."},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: "Whipped cream with tart lemon."},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: "Honeydew, lemonlime, and cherry."},
{brand: "riverreserve", shelfName: "Mild Tobacco", product: "mildtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Natural Tobacco", product: "naturaltobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Northwest", product: "northwest", blurb: "Vanilla, hazelnut, tobacco."},
{brand: "riverreserve", shelfName: "Old Wolf", product: "oldwolf", blurb: "Just like those little rootbeer barrel candies."},
{brand: "riverreserve", shelfName: "PBG", product: "pbg", blurb: "Peanut butter, banana, graham cracker."},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: " "},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: " "},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: "Pineapple coconut rum."},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: "Tobacco with a hint of vanilla cream."},
{brand: "riverreserve", shelfName: "Strawberry Bandit", product: "strawberrybandit", blurb: "Strawberry custard and tobacco."},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: "Whipped cream with strawberries."},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: "Strawberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: "Whipped cream with strawberry and banana."},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: "Strawberries mixed with sweet vanilla custard."},
{brand: "riverreserve", shelfName: "Sweet Cream Butterscotch", product: "sweetcreambutterscotch", blurb: " "},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: "Strawberry and coconut."},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: "Tobacco with vanilla custard."},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: "Vanilla graham cracker with a brown sugar dusting."},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: "A scoop of vanilla ice cream atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: "Watermelon fruit punch with menthol."},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: "Watermelon and kiwi."},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon Cloud", product: "dragoncloud", blurb: "Cinnamon, sugar, vanilla ice cream, all on a savory pastry."},
{brand: "shijin", shelfName: "Tigers Milk", product: "tigersmilk", blurb: "Peach Mango Slushy."},
{brand: "shijin", shelfName: "Tortoise Blood", product: "tortoiseblood", blurb: "Green apple, blue raspberry."},
{brand: "shijin", shelfName: "Tortoise on Ice", product: "tortoiseonice", blurb: "Green apple, blue raspberry, and menthol."},
{brand: "skwezed", shelfName: " ", product: "logo", blurb: " "},
{brand: "skwezed", shelfName: "Grapefruit", product: "grapefruit", blurb: " "},
{brand: "skwezed", shelfName: "Green Apple", product: "greenapple", blurb: " "},
{brand: "skwezed", shelfName: "Peach", product: "peach", blurb: " "},


];

let saltInventory = [
	
];

let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
}
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
