let inventory = [



{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: "Strawberry and blueberry."},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: "Blue raspberry taffy"},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: "Also available in menthol."},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: "Nutmeg, cinnamon, glaze, and pastry."},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: "Smooth vanilla custard."},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: "Mango taffy candy"},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: "Mango taffy candy, featuring menthol."},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: "Watermelon and honeydew taffy."},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: "Watermelon and honeydew taffy featuing menthol."},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: "Probably closer to mint, but that's okay."},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: "Mintier than menthol."},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: "A pool of 'mysterious berries.'"},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: "Kiwi, strawberry, menthol."},
{brand: "aqua", shelfName: " ", product: "logo", blurb: " "},
{brand: "aqua", shelfName: "Flow", product: "flow", blurb: "Pineapple, guava, mango."},
{brand: "aqua", shelfName: "Oasis", product: "oasis", blurb: "Peach, cataloupe, papaya."},
{brand: "aqua", shelfName: "Pure", product: "pure", blurb: "Strawberry, apple, and watermelon."},
{brand: "choices", shelfName: " ", product: "logo", blurb: " "},
{brand: "choices", shelfName: "Ballin", product: "ballin", blurb: "Just plain watermelon."},
{brand: "choices", shelfName: "Hood Rich", product: "hoodrich", blurb: "A cinnamon and vanilla baked treat."},
{brand: "choices", shelfName: "Racks", product: "racks", blurb: "Green apple blue raspberry hard candy."},
{brand: "choices", shelfName: "Six Figures", product: "sixfigures", blurb: "Strawberry, apple and peach."},
{brand: "choices", shelfName: "Skrilla", product: "skrilla", blurb: "Blueberry cereal."},
{brand: "choices", shelfName: "Stackin Chips", product: "stackinchips", blurb: "Iced watermelon lemonade."},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple", product: "grapeapple", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: " "},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: " "},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: " "},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon Iced", product: "strawberrylemoniced", blurb: "With menthol."},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: " "},
{brand: "cloudnurdz", shelfName: "Watermelon Apple Iced", product: "watermelonappleiced", blurb: "With menthol."},
{brand: "coastalclouds", shelfName: " ", product: "logo", blurb: " "},
{brand: "coastalclouds", shelfName: "Apple Peach Strawberry", product: "applepeachstrawberry", blurb: " "},
{brand: "coastalclouds", shelfName: "Blood Orange Mango Snow Cone", product: "bloodorangemangosnowcone", blurb: " "},
{brand: "coastalclouds", shelfName: "Blueberry Banana Muffin", product: "blueberrybananamuffin", blurb: " "},
{brand: "coastalclouds", shelfName: "Blueberry Limeade", product: "blueberrylimeade", blurb: " "},
{brand: "coastalclouds", shelfName: "Iced Apple Peach Strawberry", product: "icedapplepeachstrawberry", blurb: " "},
{brand: "coastalclouds", shelfName: "Iced Blood Orange Mango Snow Cone", product: "icedbloodorangemangosnowcone", blurb: " "},
{brand: "coastalclouds", shelfName: "Iced Mango Berries", product: "icedmangoberries", blurb: "Mango, kiwi, strawberry, menthol."},
{brand: "coastalclouds", shelfName: "Iced Passion Fruit Orange Guava", product: "icedpassionfruitorangeguava", blurb: "With menthol."},
{brand: "coastalclouds", shelfName: "Maple Butter", product: "maplebutter", blurb: " "},
{brand: "coastalclouds", shelfName: "Melon Berries", product: "melonberries", blurb: " "},
{brand: "coastalclouds", shelfName: "Passion Fruit Orange Guava", product: "passionfruitorangeguava", blurb: " "},
{brand: "coastalclouds", shelfName: "Pink Lemonade", product: "pinklemonade", blurb: " "},
{brand: "coastalclouds", shelfName: "Strawberry Daiquiri", product: "strawberrydaiquiri", blurb: " "},
{brand: "coastalclouds", shelfName: "Sugared Nectarine", product: "sugarednectarine", blurb: " "},
{brand: "fruitia", shelfName: " ", product: "logo", blurb: " "},
{brand: "fruitia", shelfName: "Apple Kiwi Crush", product: "applekiwicrush", blurb: " "},
{brand: "fruitia", shelfName: "Blood Orange Cactus Cooler", product: "bloodorangecactuscooler", blurb: " "},
{brand: "fruitia", shelfName: "Passion Fruit Guava Punch", product: "passionfruitguavapunch", blurb: " "},
{brand: "fruitia", shelfName: "Pineapple Citrus Twist", product: "pineapplecitrustwist", blurb: "Pineapple mango citrus."},
{brand: "fruitia", shelfName: "Smooth Banana Ice", product: "smoothbananaice", blurb: " "},
{brand: "fruitia", shelfName: "Strawberry Coconut Refreshers", product: "strawberrycoconutrefreshers", blurb: " "},
{brand: "hidrip", shelfName: " ", product: "logo", blurb: " "},
{brand: "hidrip", shelfName: "Dew Berry", product: "dewberry", blurb: "Honeydew and strawberry."},
{brand: "hidrip", shelfName: "Dew Berry Iced", product: "dewberryiced", blurb: "With menthol."},
{brand: "hidrip", shelfName: "Island Orange", product: "islandorange", blurb: "Blood orange and pineapple."},
{brand: "hidrip", shelfName: "Island Orange Iced", product: "islandorangeiced", blurb: "With menthol."},
{brand: "hidrip", shelfName: "Melon Patch", product: "melonpatch", blurb: "Just plain watermelon."},
{brand: "hidrip", shelfName: "Melon Patch Iced", product: "melonpatchiced", blurb: "With menthol."},
{brand: "hidrip", shelfName: "Nectarine Lychee", product: "nectarinelychee", blurb: " "},
{brand: "hidrip", shelfName: "Nectarine Lychee Ice", product: "nectarinelycheeice", blurb: "With menthol"},
{brand: "hidrip", shelfName: "Peachy Mango", product: "peachymango", blurb: " "},
{brand: "hidrip", shelfName: "Peachy Mango Iced", product: "peachymangoiced", blurb: "With menthol."},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Banana", product: "banana", blurb: "25% Toast, 25% Butter, 50% Banana."},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: "25% Toast, 25% Butter, 50% Blackberry Jam."},
{brand: "jammonster", shelfName: "Blueberry", product: "blueberry", blurb: "25% Toast, 25% Butter, 50% Blueberry Jam."},
{brand: "jammonster", shelfName: "Blueberry Raspberry Lemon", product: "blueberryraspberrylemon", blurb: " "},
{brand: "jammonster", shelfName: "Mangerine Guava ICE", product: "mangerineguavaice", blurb: "Mango, tangerine, guava, menthol."},
{brand: "jammonster", shelfName: "Mango Peach Guava", product: "mangopeachguava", blurb: " "},
{brand: "jammonster", shelfName: "Melon Colada ICE", product: "meloncoladaice", blurb: "Melon, pineapple, coconut cream, and menthol."},
{brand: "jammonster", shelfName: "PB Jam Monster Grape", product: "pbjammonstergrape", blurb: "25% Toast, 25% Peanut Butter, 50% Grape Jam."},
{brand: "jammonster", shelfName: "PB Jam Monster Strawberry", product: "pbjammonsterstrawberry", blurb: "25% Toast, 25% Peanut Butter, 50% Strawberry Jam."},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: "25% Toast, 25% Butter, 50% Raspberry Jam."},
{brand: "jammonster", shelfName: "Strawberry", product: "strawberry", blurb: "25% Toast, 25% Butter, 50% Strawberry Jam."},
{brand: "jammonster", shelfName: "Strawberry Kiwi Pomegranate", product: "strawberrykiwipomegranate", blurb: " "},
{brand: "jammonster", shelfName: "Strawmelon Apple ICE", product: "strawmelonappleice", blurb: "Strawberry watermelon menthol."},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon Freeze", product: "blueberrylemonfreeze", blurb: "With menthol."},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: " "},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: "With menthol."},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Banana Amber", product: "bananaamber", blurb: "Oatmeal Cookie, Banana."},
{brand: "lemontwist", shelfName: "Berry Amber", product: "berryamber", blurb: "Strawberry jam, honey, and graham cracker."},
{brand: "lemontwist", shelfName: "Crimson No 1 Strawberry Mason", product: "crimsonno1strawberrymason", blurb: "Strawberry lemonade."},
{brand: "lemontwist", shelfName: "Green No 1 Honeydew Melon Chew", product: "greenno1honeydewmelonchew", blurb: "Watermelon and honeydew."},
{brand: "lemontwist", shelfName: "Pink 0 Iced Pink Punch Lemonade", product: "pink0icedpinkpunchlemonade", blurb: "Pink lemonade with menthol"},
{brand: "lemontwist", shelfName: "Pink No 1 Pink Punch", product: "pinkno1pinkpunch", blurb: "Pink lemonade."},
{brand: "lemontwist", shelfName: "Purple No 1", product: "purpleno1", blurb: "Tropical mixed berry lemonade."},
{brand: "lemontwist", shelfName: "Rainbow No 1", product: "rainbowno1", blurb: "Sour skittles."},
{brand: "lemontwist", shelfName: "Space No 1", product: "spaceno1", blurb: "Strawberry and kiwi 'popping' candy."},
{brand: "lemontwist", shelfName: "White No 1", product: "whiteno1", blurb: "Pineapple candy."},
{brand: "loyalty", shelfName: " ", product: "logo", blurb: " "},
{brand: "loyalty", shelfName: "Berry Cake", product: "berrycake", blurb: "Mixed berries and vanilla cake batter."},
{brand: "loyalty", shelfName: "Ki Berry", product: "kiberry", blurb: "Kiwi strawberry."},
{brand: "loyalty", shelfName: "PomNAde", product: "pomnade", blurb: "Pomegranate lemonade."},
{brand: "loyalty", shelfName: "PomNAde Ice", product: "pomnadeice", blurb: "With menthol"},
{brand: "loyalty", shelfName: "Wata Mango", product: "watamango", blurb: "Watermelon mango."},
{brand: "magicvapor", shelfName: " ", product: "logo", blurb: " "},
{brand: "magicvapor", shelfName: "Mystic Magic", product: "mysticmagic", blurb: "Mango, tangerine, raspberry."},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: "Bold tobacco with a hint of something sweet."},
{brand: "naked", shelfName: "Brain Freeze", product: "brainfreeze", blurb: "Strawberry pomegranate menthol."},
{brand: "naked", shelfName: "Crisp Menthol", product: "crispmenthol", blurb: "Just plain menthol."},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: "Plain and natural tobacco, middle of the road."},
{brand: "naked", shelfName: "Euro Gold", product: "eurogold", blurb: "Natural tobacco with vanilla custard."},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: "Passion fruit, orange, and guava."},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: "Strawberry, pineapple, and coconut."},
{brand: "naked", shelfName: "Polar Breeze", product: "polarbreeze", blurb: "Honeydew, pineapple, and cantaloupe menthol."},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: "Blue raspberry with a hint of lemon."},
{brand: "naked", shelfName: "Very Cool", product: "verycool", blurb: "Blue raspberry menthol."},
{brand: "ofe", shelfName: " ", product: "logo", blurb: " "},
{brand: "ofe", shelfName: "Classic Gold", product: "classicgold", blurb: "Light tobacco."},
{brand: "ofe", shelfName: "Original Bold", product: "originalbold", blurb: "Bold tobacco."},
{brand: "ofe", shelfName: "Turkish Blend", product: "turkishblend", blurb: "Light, sweet tobacco."},
{brand: "oneupvapor", shelfName: " ", product: "logo", blurb: " "},
{brand: "oneupvapor", shelfName: "Orgasm", product: "orgasm", blurb: "Peach, guava, and watermelon."},
{brand: "oneupvapor", shelfName: "Orgasm Ice", product: "orgasmice", blurb: "Peach, guava, and watermelon with menthol."},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: "An icy cold hit to the back of your throat."},
{brand: "pnw", shelfName: "Arctic Tobacco", product: "arctictobacco", blurb: "Bold tobacco and menthol."},
{brand: "pnw", shelfName: "Blueberry Muffin", product: "blueberrymuffin", blurb: "Blueberries and vanilla muffin."},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: " "},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: "Just like the cereal"},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: "Sweet fruity cereal and milk."},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: "Soft vanilla cake batter."},
{brand: "pnw", shelfName: "NW4", product: "nw4", blurb: "Vanilla caramel tobacco."},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: "Peaches and menthol"},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: "Also available in menthol."},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: "Menthol and mint leaf."},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: "Soft vanilla, hazelnut and coffee."},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Blood Orange Banana Gooseberry", product: "bloodorangebananagooseberry", blurb: "Ripe gooseberries are like sour grapes."},
{brand: "pachamama", shelfName: "Fuji Apple Strawberry Nectarine", product: "fujiapplestrawberrynectarine", blurb: " "},
{brand: "pachamama", shelfName: "Honeydew Berry Kiwi", product: "honeydewberrykiwi", blurb: "Honeydew, strawberry, kiwi."},
{brand: "pachamama", shelfName: "Huckleberry Pear Acai", product: "huckleberrypearacai", blurb: " "},
{brand: "pachamama", shelfName: "Passion Fruit Raspberry Yuzu", product: "passionfruitraspberryyuzu", blurb: "Yuzu is a citrus fruit."},
{brand: "pachamama", shelfName: "Peach Papaya Coconut Cream", product: "peachpapayacoconutcream", blurb: ""},
{brand: "pachamama", shelfName: "Strawberry Guava Jackfruit", product: "strawberryguavajackfruit", blurb: "Jackfruit is often compared to mango or pineapple."},
{brand: "reds", shelfName: " ", product: "logo", blurb: " "},
{brand: "reds", shelfName: "Apple", product: "apple", blurb: " "},
{brand: "reds", shelfName: "Apple Iced", product: "appleiced", blurb: " "},
{brand: "reds", shelfName: "Berries", product: "berries", blurb: " "},
{brand: "reds", shelfName: "Berries Iced", product: "berriesiced", blurb: " "},
{brand: "reds", shelfName: "Fruit Mix", product: "fruitmix", blurb: " "},
{brand: "reds", shelfName: "Fruit Mix Iced", product: "fruitmixiced", blurb: " "},
{brand: "reds", shelfName: "Grape", product: "grape", blurb: " "},
{brand: "reds", shelfName: "Grape Iced", product: "grapeiced", blurb: " "},
{brand: "reds", shelfName: "Guava", product: "guava", blurb: " "},
{brand: "reds", shelfName: "Guava Iced", product: "guavaiced", blurb: " "},
{brand: "reds", shelfName: "Mango", product: "mango", blurb: " "},
{brand: "reds", shelfName: "Mango Iced", product: "mangoiced", blurb: " "},
{brand: "reds", shelfName: "Strawberry", product: "strawberry", blurb: " "},
{brand: "reds", shelfName: "Strawberry Iced", product: "strawberryiced", blurb: " "},
{brand: "reds", shelfName: "Watermelon", product: "watermelon", blurb: " "},
{brand: "reds", shelfName: "Watermelon Iced", product: "watermeloniced", blurb: " "},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: "Tobacco with blackberry custard."},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: "Blackberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: "Blue raspberry fruit punch."},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: "Caramel apple custard."},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: "Caramel, hazelnut, and marshmallows."},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: "Coconut, watermelon, and mango."},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: "Nothin! Just VG, PG, and nicotine."},
{brand: "riverreserve", shelfName: "Drifter X", product: "drifterx", blurb: "Whipped cream with blackberries."},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: "Mango pomegranate lemonade."},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: "Graham crackers and caramel adorned with shaved almonds, Kentucky bourbon and a splash of coconut cream."},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: "Fruit punch!"},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: "Whipped cream with tart lemon."},
{brand: "riverreserve", shelfName: "Marshmallow Custard", product: "marshmallowcustard", blurb: "Marshmallow custard."},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: "Honeydew, lemonlime, and cherry."},
{brand: "riverreserve", shelfName: "Mild Tobacco", product: "mildtobacco", blurb: " "},
{brand: "riverreserve", shelfName: "Northwest", product: "northwest", blurb: "Vanilla, hazelnut, tobacco."},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: " "},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: " "},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: "Raspberry and lemon."},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: "Pineapple coconut rum."},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: "Tobacco with a hint of vanilla cream."},
{brand: "riverreserve", shelfName: "Strawberry Bandit", product: "strawberrybandit", blurb: "Strawberry custard and tobacco."},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: "Whipped cream with strawberries."},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: "Strawberry topping on a scoop of vanilla ice cream, all atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: "Whipped cream with strawberry and banana."},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: "Strawberries mixed with sweet vanilla custard."},
{brand: "riverreserve", shelfName: "Sweet Cream Butterscotch", product: "sweetcreambutterscotch", blurb: " "},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: "Strawberry and coconut."},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: "Tobacco with vanilla custard."},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: "Vanilla graham cracker with a brown sugar dusting."},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: "A scoop of vanilla ice cream atop a vanilla waffle cone."},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: "Watermelon fruit punch with menthol."},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: "Watermelon and kiwi."},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Antidote On Ice", product: "antidoteonice", blurb: "Peach, mango, blue raspberry menthol."},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: "Strawberry watermelon."},
{brand: "ruthless", shelfName: "Ez Duz It On Ice", product: "ezduzitonice", blurb: "Strawberry watermelon and menthol."},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: "Grape soda."},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: "Grape soda with menthol."},
{brand: "ruthless", shelfName: "Jungle Fever", product: "junglefever", blurb: "Pineapple, mango, citrus."},
{brand: "ruthless", shelfName: "Paradize", product: "paradize", blurb: "Passion fruit, pear, and peaches."},
{brand: "ruthless", shelfName: "Rage", product: "rage", blurb: "Apple mango."},
{brand: "ruthless", shelfName: "Skir Skirr On Ice", product: "skirskirronice", blurb: "Honeydew melon, green apple, menthol."},
{brand: "ruthless", shelfName: "Slurricane", product: "slurricane", blurb: "Peach, papaya, and guava."},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: "Raspberry, kiwi, and strawberry."},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: "Sour candy apple."},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Fairground", product: "fairground", blurb: "Deep fried cream cake."},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: "Chocolate milk."},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: "Strawberry milk."},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon Cloud", product: "dragoncloud", blurb: "Cinnamon, sugar, vanilla ice cream, all on a savory pastry."},
{brand: "shijin", shelfName: "Phoenix Tears", product: "phoenixtears", blurb: "Sugar cookie with vanilla custard."},
{brand: "shijin", shelfName: "Tigers Milk", product: "tigersmilk", blurb: "Peach Mango Slushy."},
{brand: "shijin", shelfName: "Tortoise Blood", product: "tortoiseblood", blurb: "Green apple, blue raspberry."},
{brand: "shijin", shelfName: "Tortoise on Ice", product: "tortoiseonice", blurb: "Green apple, blue raspberry, and menthol."},
{brand: "shijin", shelfName: "Tortoise on the Rocks", product: "tortoiseontherocks", blurb: "Green apple, blue raspberry, and crushed mint."},
{brand: "silverback", shelfName: " ", product: "logo", blurb: " "},
{brand: "silverback", shelfName: "Amy", product: "amy", blurb: "Vanilla, caramel, and peanut butter brittle."},
{brand: "silverback", shelfName: "BooBoo", product: "booboo", blurb: "Grape and blueberry."},
{brand: "silverback", shelfName: "Harambe", product: "harambe", blurb: "Cinnamon and cream liqueur."},
{brand: "silverback", shelfName: "Jenny", product: "jenny", blurb: "Strawberry, bubblegum, mint."},
{brand: "silverback", shelfName: "Lola", product: "lola", blurb: "Strawberry, banana, dragonfruit."},
{brand: "silverback", shelfName: "Sandy", product: "sandy", blurb: "Strawberry watermelon."},
{brand: "thehypecollection", shelfName: " ", product: "logo", blurb: " "},
{brand: "thehypecollection", shelfName: "America", product: "america", blurb: "Red white and blue rocket pop."},
{brand: "thehypecollection", shelfName: "Blue Slushee", product: "blueslushee", blurb: "Blue raspberry slushee."},
{brand: "thehypecollection", shelfName: "Cool Blue Slushee", product: "coolblueslushee", blurb: "Blue raspberry slushee, featuring menthol."},
{brand: "thehypecollection", shelfName: "Cotton Candy", product: "cottoncandy", blurb: "Pink and blue, cotton candy."},
{brand: "transistor", shelfName: " ", product: "logo", blurb: " "},
{brand: "transistor", shelfName: "LSD", product: "lsd", blurb: "Sweet and tart lemon hard candy."},
{brand: "transistor", shelfName: "Lemn Berry", product: "lemnberry", blurb: "Exotic pink lemonade."},
{brand: "transistor", shelfName: "Nazzo", product: "nazzo", blurb: "Grapefruit"},
{brand: "transistor", shelfName: "Tango Chillin", product: "tangochillin", blurb: "Tangerine, mango, watermelon, menthol."},
{brand: "transistor", shelfName: "Tango Melon", product: "tangomelon", blurb: "Tangerine mango watermelon"},
{brand: "vapetasia", shelfName: " ", product: "logo", blurb: " "},
{brand: "vapetasia", shelfName: "Blackberry Lemonade", product: "blackberrylemonade", blurb: "Sweet and tart, blackberries and lemon."},
{brand: "vapetasia", shelfName: "Blueberry Killer Kustard", product: "blueberrykillerkustard", blurb: "Blueberry custard."},
{brand: "vapetasia", shelfName: "Killer Kustard", product: "killerkustard", blurb: "Vanilla custard."},
{brand: "vapetasia", shelfName: "Lemon Killer Kustard", product: "lemonkillerkustard", blurb: "Lemon custard."},
{brand: "vapetasia", shelfName: "Rainbow Road", product: "rainbowroad", blurb: "Berries, citrus, and cream for a fruity breakfast cereal."},
{brand: "vapetasia", shelfName: "Strawberry Killer Kustard", product: "strawberrykillerkustard", blurb: "Strawberry custard."},


];

let saltInventory = [
	


{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: "Strawberry and blueberry."},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: "Blue raspberry taffy"},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: "Also available in menthol."},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: "Nutmeg, cinnamon, glaze, and pastry."},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: "Smooth vanilla custard."},
{brand: "airfactory", shelfName: "Custard Tobacco", product: "custardtobacco", blurb: "Smooth vanilla custard with tobacco."},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: "Mango taffy candy"},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: "Mango taffy candy, featuring menthol."},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: "Watermelon and honeydew taffy."},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: "Watermelon and honeydew taffy featuing menthol."},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: "Probably closer to mint, but that's okay."},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: "Mintier than menthol."},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: "A pool of 'mysterious berries.'"},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: "Kiwi, strawberry, menthol."},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple", product: "grapeapple", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: " "},
{brand: "cloudnurdz", shelfName: "Kiwi Melon", product: "kiwimelon", blurb: " "},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: " "},
{brand: "fruitia", shelfName: " ", product: "logo", blurb: " "},
{brand: "fruitia", shelfName: "Apple Kiwi Crush", product: "applekiwicrush", blurb: " "},
{brand: "fruitia", shelfName: "Citrus Twist", product: "citrustwist", blurb: "Pineapple mango citrus."},
{brand: "fruitia", shelfName: "Passion Fruit Guava Punch", product: "passionfruitguavapunch", blurb: " "},
{brand: "fruitia", shelfName: "Strawberry Coconut Refreshers", product: "strawberrycoconutrefreshers", blurb: " "},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Banana", product: "banana", blurb: "25% Toast, 25% Butter, 50% Banana."},
{brand: "jammonster", shelfName: "Blueberry", product: "blueberry", blurb: "25% Toast, 25% Butter, 50% Blueberry Jam."},
{brand: "jammonster", shelfName: "Melon Colada", product: "meloncolada", blurb: "Melon, pineapple, and coconut cream."},
{brand: "jammonster", shelfName: "Strawberry", product: "strawberry", blurb: "25% Toast, 25% Butter, 50% Strawberry Jam."},
{brand: "jammonster", shelfName: "Strawmelon Apple", product: "strawmelonapple", blurb: "strawnerry, watermelon, and apple."},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: " "},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: " "},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: " "},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: " "},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: " "},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: " "},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Honeydew Melon Chew", product: "honeydewmelonchew", blurb: "Watermelon and honeydew."},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: "Pink lemonade with menthol."},
{brand: "lemontwist", shelfName: "Pink Punch Lemonade", product: "pinkpunchlemonade", blurb: "Pink punch lemonade."},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: "Watermelon and lemonade."},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Jewel Mint", product: "jewelmint", blurb: "Just plain mint, little to no menthol."},
{brand: "podjuice", shelfName: "Jewel Mint Sapphire", product: "jewelmintsapphire", blurb: "Mint and menthol."},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Antidote on Ice", product: "antidoteonice", blurb: "Peach, mango, blue raspberry menthol."},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: "Strawberry watermelon."},
{brand: "ruthless", shelfName: "Ez Duz It on Ice", product: "ezduzitonice", blurb: "Strawberry watermelon and menthol."},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: "Grape soda."},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: "Grape soda with menthol."},
{brand: "ruthless", shelfName: "Paradise", product: "paradise", blurb: "Passion fruit, pear, and peaches."},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: "Raspberry, kiwi, and strawberry."},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: "Sour candy apple."},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: "Guava and mixed berries."},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Fairgrounds", product: "fairgrounds", blurb: "Deep fried cream cake."},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: "Chocolate milk."},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: "Strawberry milk."},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Punch Berry Blood", product: "punchberryblood", blurb: "Sour raspberry lemonade punch."},
{brand: "sadboy", shelfName: "Punch Berry Ice", product: "punchberryice", blurb: "Sour raspberry lemonade punch, with menthol."},
{brand: "sadboy", shelfName: "Rainbow Blood", product: "rainbowblood", blurb: "Quote: 'Mixed exotic fruit.'"},
{brand: "sadboy", shelfName: "Rainbow Ice", product: "rainbowice", blurb: "Mixed exotic fruit with menthol."},
{brand: "sadboy", shelfName: "Strawberry Blood", product: "strawberryblood", blurb: "Strawberry candy."},
{brand: "sadboy", shelfName: "Strawberry Ice", product: "strawberryice", blurb: "Strawberry candy with menthol."},
{brand: "sadboy", shelfName: "Unicorn Tears", product: "unicorntears", blurb: "THE Sadboy website calls it: 'universally the perfect fit for anyone’s flavor preference.'"},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon", product: "dragon", blurb: "Lemon tart."},
{brand: "shijin", shelfName: "Phoenix", product: "phoenix", blurb: "Guava lychee."},
{brand: "shijin", shelfName: "Tiger", product: "tiger", blurb: "Peach mango slushy."},
{brand: "shijin", shelfName: "Tortoise", product: "tortoise", blurb: "Green apple, blue raspberry."},
{brand: "shijin", shelfName: "Tortoise On Ice", product: "tortoiseonice", blurb: "Green apple, blue raspberry with menthol."},
{brand: "skwezed", shelfName: " ", product: "logo", blurb: " "},
{brand: "skwezed", shelfName: "Grapefruit", product: "grapefruit", blurb: " "},
{brand: "skwezed", shelfName: "Green Apple", product: "greenapple", blurb: " "},
{brand: "skwezed", shelfName: "Lychee", product: "lychee", blurb: " "},
{brand: "skwezed", shelfName: "Mango", product: "mango", blurb: " "},
{brand: "skwezed", shelfName: "Peach", product: "peach", blurb: " "},
{brand: "skwezed", shelfName: "Watermelon", product: "watermelon", blurb: " "},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Banana Dragonberry", product: "bananadragonberry", blurb: "Dragonfruit and banana."},
{brand: "solace", shelfName: "Berry Bash", product: "berrybash", blurb: "Mixed berries."},
{brand: "solace", shelfName: "Blues Lemonade", product: "blueslemonade", blurb: "Lemonade with a hint of blue raspberry."},
{brand: "solace", shelfName: "Blues Mango", product: "bluesmango", blurb: "Mango with a hint of... blue raspberry."},
{brand: "solace", shelfName: "Cool Tobacco", product: "cooltobacco", blurb: "Classic tobacco with a bit of menthol."},
{brand: "solace", shelfName: "Dragonthol", product: "dragonthol", blurb: "Dragonfruit and menthol."},
{brand: "solace", shelfName: "Grape", product: "grape", blurb: " "},
{brand: "solace", shelfName: "Juiced Apple", product: "juicedapple", blurb: " "},
{brand: "solace", shelfName: "Lemon Lime Fusion", product: "lemonlimefusion", blurb: " "},
{brand: "solace", shelfName: "Pineapple", product: "pineapple", blurb: " "},
{brand: "solace", shelfName: "Sea Blueberry", product: "seablueberry", blurb: " "},
{brand: "solace", shelfName: "Seedless Watermelon", product: "seedlesswatermelon", blurb: "There actually are seeds, be careful."},
{brand: "solace", shelfName: "Strawberry", product: "strawberry", blurb: "Strawberry kiwi with menthol."},
{brand: "solace", shelfName: "Tropic Strawberry", product: "tropicstrawberry", blurb: " "},
{brand: "vapetasia", shelfName: " ", product: "logo", blurb: " "},
{brand: "vapetasia", shelfName: "Killer Kustard Strawberry", product: "killerkustardstrawberry", blurb: "Strawberry custard."},
{brand: "vapetasia", shelfName: "Rainbow Road", product: "rainbowroad", blurb: "Mixed fruit cereal, like the little circles."},
{brand: "vapetasia", shelfName: "Royalty II Salt", product: "royaltyiisalt", blurb: "Vanilla with mild tobacco."},


];

let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
};
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
