
let inventory = [
{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: `${blurbs["airfactory"]["berryrush"]}`},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: `${blurbs["airfactory"]["bluerazz"]}`},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: `${blurbs["airfactory"]["bluerazzice"]}`},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: `${blurbs["airfactory"]["creamycrunch"]}`},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: `${blurbs["airfactory"]["custard"]}`},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: `${blurbs["airfactory"]["mango"]}`},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: `${blurbs["airfactory"]["mangoice"]}`},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: `${blurbs["airfactory"]["melonlush"]}`},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: `${blurbs["airfactory"]["melonlushice"]}`},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: `${blurbs["airfactory"]["menthol"]}`},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: `${blurbs["airfactory"]["mint"]}`},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: `${blurbs["airfactory"]["mixedberry"]}`},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: `${blurbs["airfactory"]["tropicfreeze"]}`},
{brand: "aqua", shelfName: " ", product: "logo", blurb: " "},
{brand: "aqua", shelfName: "Flow", product: "flow", blurb: `${blurbs["aqua"]["flow"]}`},
{brand: "aqua", shelfName: "Oasis", product: "oasis", blurb: `${blurbs["aqua"]["oasis"]}`},
{brand: "aqua", shelfName: "Pure", product: "pure", blurb: `${blurbs["aqua"]["pure"]}`},
{brand: "choices", shelfName: " ", product: "logo", blurb: " "},
{brand: "choices", shelfName: "Racks", product: "racks", blurb: `${blurbs["choices"]["racks"]}`},
{brand: "choices", shelfName: "Ballin", product: "ballin", blurb: `${blurbs["choices"]["ballin"]}`},
{brand: "choices", shelfName: "Hood Rich", product: "hoodrich", blurb: `${blurbs["choices"]["hoodrich"]}`},
{brand: "choices", shelfName: "Six Figures", product: "sixfigures", blurb: `${blurbs["choices"]["sixfigures"]}`},
{brand: "choices", shelfName: "Skrilla", product: "skrilla", blurb: `${blurbs["choices"]["skrilla"]}`},
{brand: "choices", shelfName: "Stackin Chips", product: "stackinchips", blurb: `${blurbs["choices"]["stackinchips"]}`},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple", product: "grapeapple", blurb: `${blurbs["cloudnurdz"]["grapeapple"]}`},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: `${blurbs["cloudnurdz"]["grapestrawberry"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: `${blurbs["cloudnurdz"]["peachbluerazz"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: `${blurbs["cloudnurdz"]["strawberrylemon"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon Iced", product: "strawberrylemoniced", blurb: `${blurbs["cloudnurdz"]["strawberrylemoniced"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple", product: "watermelonapple", blurb: `${blurbs["cloudnurdz"]["watermelonapple"]}`},
{brand: "cloudnurdz", shelfName: "Watermelon Apple Iced", product: "watermelonappleiced", blurb: `${blurbs["cloudnurdz"]["watermelonappleiced"]}`},
{brand: "coastalclouds", shelfName: " ", product: "logo", blurb: " "},
{brand: "coastalclouds", shelfName: "Apple Peach Strawberry", product: "applepeachstrawberry", blurb: `${blurbs["coastalclouds"]["applepeachstrawberry"]}`},
{brand: "coastalclouds", shelfName: "Blood Orange Mango Snow Cone", product: "bloodorangemangosnowcone", blurb: `${blurbs["coastalclouds"]["bloodorangemangosnowcone"]}`},
{brand: "coastalclouds", shelfName: "Blueberry Banana Muffin", product: "blueberrybananamuffin", blurb: `${blurbs["coastalclouds"]["blueberrybananamuffin"]}`},
{brand: "coastalclouds", shelfName: "Blueberry Limeade", product: "blueberrylimeade", blurb: `${blurbs["coastalclouds"]["blueberrylimeade"]}`},
{brand: "coastalclouds", shelfName: "Iced Apple Peach Strawberry", product: "icedapplepeachstrawberry", blurb: `${blurbs["coastalclouds"]["icedapplepeachstrawberry"]}`},
{brand: "coastalclouds", shelfName: "Iced Blood Orange Mango Snow Cone", product: "icedbloodorangemangosnowcone", blurb: `${blurbs["coastalclouds"]["icedbloodorangemangosnowcone"]}`},
{brand: "coastalclouds", shelfName: "Iced Melon Berries", product: "icedmelonberries", blurb: `${blurbs["coastalclouds"]["icedmelonberries"]}`},
{brand: "coastalclouds", shelfName: "Iced Passion Fruit Orange Guava", product: "icedpassionfruitorangeguava", blurb: `${blurbs["coastalclouds"]["icedpassionfruitorangeguava"]}`},
{brand: "coastalclouds", shelfName: "Maple Butter", product: "maplebutter", blurb: `${blurbs["coastalclouds"]["maplebutter"]}`},
{brand: "coastalclouds", shelfName: "Melon Berries", product: "melonberries", blurb: `${blurbs["coastalclouds"]["melonberries"]}`},
{brand: "coastalclouds", shelfName: "Passion Fruit Orange Guava", product: "passionfruitorangeguava", blurb: `${blurbs["coastalclouds"]["passionfruitorangeguava"]}`},
{brand: "coastalclouds", shelfName: "Pink Lemonade", product: "pinklemonade", blurb: `${blurbs["coastalclouds"]["pinklemonade"]}`},
{brand: "coastalclouds", shelfName: "Strawberry Daiquiri", product: "strawberrydaiquiri", blurb: `${blurbs["coastalclouds"]["strawberrydaiquiri"]}`},
{brand: "coastalclouds", shelfName: "Sugared Nectarine", product: "sugarednectarine", blurb: `${blurbs["coastalclouds"]["sugarednectarine"]}`},
{brand: "fruitia", shelfName: " ", product: "logo", blurb: " "},
{brand: "fruitia", shelfName: "Apple Kiwi Crush", product: "applekiwicrush", blurb: `${blurbs["fruitia"]["applekiwicrush"]}`},
{brand: "fruitia", shelfName: "Blood Orange Cactus Cooler", product: "bloodorangecactuscooler", blurb: `${blurbs["fruitia"]["bloodorangecactuscooler"]}`},
{brand: "fruitia", shelfName: "Passion Fruit Guava Punch", product: "passionfruitguavapunch", blurb: `${blurbs["fruitia"]["passionfruitguavapunch"]}`},
{brand: "fruitia", shelfName: "Pineapple Citrus Twist", product: "pineapplecitrustwist", blurb: `${blurbs["fruitia"]["pineapplecitrustwist"]}`},
{brand: "fruitia", shelfName: "Smooth Banana Ice", product: "smoothbananaice", blurb: `${blurbs["fruitia"]["smoothbananaice"]}`},
{brand: "fruitia", shelfName: "Strawberry Coconut Refreshers", product: "strawberrycoconutrefreshers", blurb: `${blurbs["fruitia"]["strawberrycoconutrefreshers"]}`},
{brand: "hidrip", shelfName: " ", product: "logo", blurb: " "},
{brand: "hidrip", shelfName: "Dew Berry", product: "dewberry", blurb: `${blurbs["hidrip"]["dewberry"]}`},
{brand: "hidrip", shelfName: "Dew Berry Iced", product: "dewberryiced", blurb: `${blurbs["hidrip"]["dewberryiced"]}`},
{brand: "hidrip", shelfName: "Island Orange", product: "islandorange", blurb: `${blurbs["hidrip"]["islandorange"]}`},
{brand: "hidrip", shelfName: "Island Orange Iced", product: "islandorangeiced", blurb: `${blurbs["hidrip"]["islandorangeiced"]}`},
{brand: "hidrip", shelfName: "Melon Patch", product: "melonpatch", blurb: `${blurbs["hidrip"]["melonpatch"]}`},
{brand: "hidrip", shelfName: "Melon Patch Iced", product: "melonpatchiced", blurb: `${blurbs["hidrip"]["melonpatchiced"]}`},
{brand: "hidrip", shelfName: "Nectarine Lychee", product: "nectarinelychee", blurb: `${blurbs["hidrip"]["nectarinelychee"]}`},
{brand: "hidrip", shelfName: "Nectarine Lychee Ice", product: "nectarinelycheeice", blurb: `${blurbs["hidrip"]["nectarinelycheeice"]}`},
{brand: "hidrip", shelfName: "Peachy Mango", product: "peachymango", blurb: `${blurbs["hidrip"]["peachymango"]}`},
{brand: "hidrip", shelfName: "Peachy Mango Iced", product: "peachymangoiced", blurb: `${blurbs["hidrip"]["peachymangoiced"]}`},
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "Banana", product: "banana", blurb: `${blurbs["jammonster"]["banana"]}`},
{brand: "jammonster", shelfName: "Blackberry", product: "blackberry", blurb: `${blurbs["jammonster"]["blackberry"]}`},
{brand: "jammonster", shelfName: "Blueberry", product: "blueberry", blurb: `${blurbs["jammonster"]["blueberry"]}`},
{brand: "jammonster", shelfName: "Blueberry Raspberry Lemon", product: "blueberryraspberrylemon", blurb: `${blurbs["jammonster"]["blueberryraspberrylemon"]}`},
{brand: "jammonster", shelfName: "Mangerine Guava ICE", product: "mangerineguavaice", blurb: `${blurbs["jammonster"]["mangerineguavaice"]}`},
{brand: "jammonster", shelfName: "Mango Peach Guava", product: "mangopeachguava", blurb: `${blurbs["jammonster"]["mangopeachguava"]}`},
{brand: "jammonster", shelfName: "Melon Colada ICE", product: "meloncoladaice", blurb: `${blurbs["jammonster"]["meloncoladaice"]}`},
{brand: "jammonster", shelfName: "PB Jam Monster Grape", product: "pbjammonstergrape", blurb: `${blurbs["jammonster"]["pbjammonstergrape"]}`},
{brand: "jammonster", shelfName: "PB Jam Monster Strawberry", product: "pbjammonsterstrawberry", blurb: `${blurbs["jammonster"]["pbjammonsterstrawberry"]}`},
{brand: "jammonster", shelfName: "Raspberry", product: "raspberry", blurb: `${blurbs["jammonster"]["raspberry"]}`},
{brand: "jammonster", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["jammonster"]["strawberry"]}`},
{brand: "jammonster", shelfName: "Strawberry Kiwi Pomegranate", product: "strawberrykiwipomegranate", blurb: `${blurbs["jammonster"]["strawberrykiwipomegranate"]}`},
{brand: "jammonster", shelfName: "Strawmelon Apple ICE", product: "strawmelonappleice", blurb: `${blurbs["jammonster"]["strawmelonappleice"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: `${blurbs["juicehead"]["blueberrylemon"]}`},
{brand: "juicehead", shelfName: "Blueberry Lemon Freeze", product: "blueberrylemonfreeze", blurb: `${blurbs["juicehead"]["blueberrylemonfreeze"]}`},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: `${blurbs["juicehead"]["guavapeach"]}`},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: `${blurbs["juicehead"]["peachpear"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: `${blurbs["juicehead"]["watermelonlime"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime Freeze", product: "watermelonlimefreeze", blurb: `${blurbs["juicehead"]["watermelonlimefreeze"]}`},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Banana Amber", product: "bananaamber", blurb: `${blurbs["lemontwist"]["bananaamber"]}`},
{brand: "lemontwist", shelfName: "Berry Amber", product: "berryamber", blurb: `${blurbs["lemontwist"]["berryamber"]}`},
{brand: "lemontwist", shelfName: "Crimson No Strawberry Mason", product: "crimsonnostrawberrymason", blurb: `${blurbs["lemontwist"]["crimsonnostrawberrymason"]}`},
{brand: "lemontwist", shelfName: "Green No Honeydew Melon Chew", product: "greennohoneydewmelonchew", blurb: `${blurbs["lemontwist"]["greennohoneydewmelonchew"]}`},
{brand: "lemontwist", shelfName: "Pink Iced Pink Punch Lemonade", product: "pinkicedpinkpunchlemonade", blurb: `${blurbs["lemontwist"]["pinkicedpinkpunchlemonade"]}`},
{brand: "lemontwist", shelfName: "Pink No Pink Punch", product: "pinknopinkpunch", blurb: `${blurbs["lemontwist"]["pinknopinkpunch"]}`},
{brand: "lemontwist", shelfName: "Purple No", product: "purpleno", blurb: `${blurbs["lemontwist"]["purpleno"]}`},
{brand: "lemontwist", shelfName: "Rainbow No", product: "rainbowno", blurb: `${blurbs["lemontwist"]["rainbowno"]}`},
{brand: "lemontwist", shelfName: "Space No", product: "spaceno", blurb: `${blurbs["lemontwist"]["spaceno"]}`},
{brand: "lemontwist", shelfName: "White No", product: "whiteno", blurb: `${blurbs["lemontwist"]["whiteno"]}`},
{brand: "loyalty", shelfName: " ", product: "logo", blurb: " "},
{brand: "loyalty", shelfName: "Berry Cake", product: "berrycake", blurb: `${blurbs["loyalty"]["berrycake"]}`},
{brand: "loyalty", shelfName: "Ki Berry", product: "kiberry", blurb: `${blurbs["loyalty"]["kiberry"]}`},
{brand: "loyalty", shelfName: "PomNAde", product: "pomnade", blurb: `${blurbs["loyalty"]["pomnade"]}`},
{brand: "loyalty", shelfName: "PomNAde Ice", product: "pomnadeice", blurb: `${blurbs["loyalty"]["pomnadeice"]}`},
{brand: "loyalty", shelfName: "Wata Mango", product: "watamango", blurb: `${blurbs["loyalty"]["watamango"]}`},
{brand: "magicvapor", shelfName: " ", product: "logo", blurb: " "},
{brand: "magicvapor", shelfName: "Mystic Magic", product: "mysticmagic", blurb: `${blurbs["magicvapor"]["mysticmagic"]}`},
{brand: "naked", shelfName: " ", product: "logo", blurb: " "},
{brand: "naked", shelfName: "American Patriot", product: "americanpatriot", blurb: `${blurbs["naked"]["americanpatriot"]}`},
{brand: "naked", shelfName: "Cuban Blend", product: "cubanblend", blurb: `${blurbs["naked"]["cubanblend"]}`},
{brand: "naked", shelfName: "Euro Gold", product: "eurogold", blurb: `${blurbs["naked"]["eurogold"]}`},
{brand: "naked", shelfName: "Hawaiian POG", product: "hawaiianpog", blurb: `${blurbs["naked"]["hawaiianpog"]}`},
{brand: "naked", shelfName: "Lava Flow", product: "lavaflow", blurb: `${blurbs["naked"]["lavaflow"]}`},
{brand: "naked", shelfName: "Really Berry Very Berry", product: "reallyberryveryberry", blurb: `${blurbs["naked"]["reallyberryveryberry"]}`},
{brand: "naked", shelfName: "Menthol Brain Freeze", product: "brainfreeze", blurb: `${blurbs["naked"]["brainfreeze"]}`},
{brand: "naked", shelfName: "Menthol Crisp Menthol", product: "crispmenthol", blurb: `${blurbs["naked"]["crispmenthol"]}`},
{brand: "naked", shelfName: "Menthol Polar Breeze", product: "polarbreeze", blurb: `${blurbs["naked"]["polarbreeze"]}`},
{brand: "naked", shelfName: "Menthol Very Cool", product: "verycool", blurb: `${blurbs["naked"]["verycool"]}`},
{brand: "ofe", shelfName: " ", product: "logo", blurb: " "},
{brand: "ofe", shelfName: "Classic Gold", product: "classicgold", blurb: `${blurbs["ofe"]["classicgold"]}`},
{brand: "ofe", shelfName: "Original Bold", product: "originalbold", blurb: `${blurbs["ofe"]["originalbold"]}`},
{brand: "ofe", shelfName: "Turkish Blend", product: "turkishblend", blurb: `${blurbs["ofe"]["turkishblend"]}`},
{brand: "oneup", shelfName: " ", product: "logo", blurb: " "},
{brand: "oneup", shelfName: "Orgasm", product: "orgasm", blurb: `${blurbs["oneup"]["orgasm"]}`},
{brand: "oneup", shelfName: "Orgasm Ice", product: "orgasmice", blurb: `${blurbs["oneup"]["orgasmice"]}`},
{brand: "pnw", shelfName: " ", product: "logo", blurb: " "},
{brand: "pnw", shelfName: "Arctic Frost", product: "arcticfrost", blurb: `${blurbs["pnw"]["arcticfrost"]}`},
{brand: "pnw", shelfName: "Arctic Tobacco", product: "arctictobacco", blurb: `${blurbs["pnw"]["arctictobacco"]}`},
{brand: "pnw", shelfName: "Blueberry Muffin", product: "blueberrymuffin", blurb: `${blurbs["pnw"]["blueberrymuffin"]}`},
{brand: "pnw", shelfName: "Cherry Limeade", product: "cherrylimeade", blurb: `${blurbs["pnw"]["cherrylimeade"]}`},
{brand: "pnw", shelfName: "Cinnamon Crunch", product: "cinnamoncrunch", blurb: `${blurbs["pnw"]["cinnamoncrunch"]}`},
{brand: "pnw", shelfName: "Fruity Os", product: "fruityos", blurb: `${blurbs["pnw"]["fruityos"]}`},
{brand: "pnw", shelfName: "Mad Batter", product: "madbatter", blurb: `${blurbs["pnw"]["madbatter"]}`},
{brand: "pnw", shelfName: "NW", product: "nw", blurb: `${blurbs["pnw"]["nw"]}`},
{brand: "pnw", shelfName: "Peach Frost", product: "peachfrost", blurb: `${blurbs["pnw"]["peachfrost"]}`},
{brand: "pnw", shelfName: "Peaches", product: "peaches", blurb: `${blurbs["pnw"]["peaches"]}`},
{brand: "pnw", shelfName: "Spearmint", product: "spearmint", blurb: `${blurbs["pnw"]["spearmint"]}`},
{brand: "pnw", shelfName: "Vanilla Nut Latte", product: "vanillanutlatte", blurb: `${blurbs["pnw"]["vanillanutlatte"]}`},
{brand: "pachamama", shelfName: " ", product: "logo", blurb: " "},
{brand: "pachamama", shelfName: "Blood Orange Banana Gooseberry", product: "bloodorangebananagooseberry", blurb: `${blurbs["pachamama"]["bloodorangebananagooseberry"]}`},
{brand: "pachamama", shelfName: "Fuji Apple Strawberry Nectarine", product: "fujiapplestrawberrynectarine", blurb: `${blurbs["pachamama"]["fujiapplestrawberrynectarine"]}`},
{brand: "pachamama", shelfName: "Honeydew Berry Kiwi", product: "honeydewberrykiwi", blurb: `${blurbs["pachamama"]["honeydewberrykiwi"]}`},
{brand: "pachamama", shelfName: "Huckleberry Pear Acai", product: "huckleberrypearacai", blurb: `${blurbs["pachamama"]["huckleberrypearacai"]}`},
{brand: "pachamama", shelfName: "Passion Fruit Raspberry Yuzu", product: "passionfruitraspberryyuzu", blurb: `${blurbs["pachamama"]["passionfruitraspberryyuzu"]}`},
{brand: "pachamama", shelfName: "Peach Papaya Coconut Cream", product: "peachpapayacoconutcream", blurb: `${blurbs["pachamama"]["peachpapayacoconutcream"]}`},
{brand: "pachamama", shelfName: "Strawberry Guava Jackfruit", product: "strawberryguavajackfruit", blurb: `${blurbs["pachamama"]["strawberryguavajackfruit"]}`},
{brand: "reds", shelfName: " ", product: "logo", blurb: " "},
{brand: "reds", shelfName: "Apple", product: "apple", blurb: `${blurbs["reds"]["apple"]}`},
{brand: "reds", shelfName: "Apple Iced", product: "appleiced", blurb: `${blurbs["reds"]["appleiced"]}`},
{brand: "reds", shelfName: "Berries", product: "berries", blurb: `${blurbs["reds"]["berries"]}`},
{brand: "reds", shelfName: "Berries Iced", product: "berriesiced", blurb: `${blurbs["reds"]["berriesiced"]}`},
{brand: "reds", shelfName: "Fruit Mix", product: "fruitmix", blurb: `${blurbs["reds"]["fruitmix"]}`},
{brand: "reds", shelfName: "Fruit Mix Iced", product: "fruitmixiced", blurb: `${blurbs["reds"]["fruitmixiced"]}`},
{brand: "reds", shelfName: "Grape", product: "grape", blurb: `${blurbs["reds"]["grape"]}`},
{brand: "reds", shelfName: "Grape Iced", product: "grapeiced", blurb: `${blurbs["reds"]["grapeiced"]}`},
{brand: "reds", shelfName: "Guava", product: "guava", blurb: `${blurbs["reds"]["guava"]}`},
{brand: "reds", shelfName: "Guava Iced", product: "guavaiced", blurb: `${blurbs["reds"]["guavaiced"]}`},
{brand: "reds", shelfName: "Mango", product: "mango", blurb: `${blurbs["reds"]["mango"]}`},
{brand: "reds", shelfName: "Mango Iced", product: "mangoiced", blurb: `${blurbs["reds"]["mangoiced"]}`},
{brand: "reds", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["reds"]["strawberry"]}`},
{brand: "reds", shelfName: "Strawberry Iced", product: "strawberryiced", blurb: `${blurbs["reds"]["strawberryiced"]}`},
{brand: "reds", shelfName: "Watermelon", product: "watermelon", blurb: `${blurbs["reds"]["watermelon"]}`},
{brand: "reds", shelfName: "Watermelon Iced", product: "watermeloniced", blurb: `${blurbs["reds"]["watermeloniced"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Bandit", product: "bandit", blurb: `${blurbs["riverreserve"]["bandit"]}`},
{brand: "riverreserve", shelfName: "Blackberry Waffle Cone", product: "blackberrywafflecone", blurb: `${blurbs["riverreserve"]["blackberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: `${blurbs["riverreserve"]["blueislandpunch"]}`},
{brand: "riverreserve", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: `${blurbs["riverreserve"]["boldtobacco"]}`},
{brand: "riverreserve", shelfName: "Caramel Apple Drifter", product: "caramelappledrifter", blurb: `${blurbs["riverreserve"]["caramelappledrifter"]}`},
{brand: "riverreserve", shelfName: "Caramel Cove", product: "caramelcove", blurb: `${blurbs["riverreserve"]["caramelcove"]}`},
{brand: "riverreserve", shelfName: "Castaway", product: "castaway", blurb: `${blurbs["riverreserve"]["castaway"]}`},
{brand: "riverreserve", shelfName: "Clearwater Creek", product: "clearwatercreek", blurb: `${blurbs["riverreserve"]["clearwatercreek"]}`},
{brand: "riverreserve", shelfName: "Drifter X", product: "drifterx", blurb: `${blurbs["riverreserve"]["drifterx"]}`},
{brand: "riverreserve", shelfName: "Eddy", product: "eddy", blurb: `${blurbs["riverreserve"]["eddy"]}`},
{brand: "riverreserve", shelfName: "Great Wall", product: "greatwall", blurb: `${blurbs["riverreserve"]["greatwall"]}`},
{brand: "riverreserve", shelfName: "Island Punch", product: "islandpunch", blurb: `${blurbs["riverreserve"]["islandpunch"]}`},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: `${blurbs["riverreserve"]["lemondrifter"]}`},
{brand: "riverreserve", shelfName: "Marshmallow Custard", product: "marshmallowcustard", blurb: `${blurbs["riverreserve"]["marshmallowcustard"]}`},
{brand: "riverreserve", shelfName: "Midori Sour", product: "midorisour", blurb: `${blurbs["riverreserve"]["midorisour"]}`},
{brand: "riverreserve", shelfName: "Mild Tobacco", product: "mildtobacco", blurb: `${blurbs["riverreserve"]["mildtobacco"]}`},
{brand: "riverreserve", shelfName: "Northwest", product: "northwest", blurb: `${blurbs["riverreserve"]["northwest"]}`},
{brand: "riverreserve", shelfName: "Peach Mango Lemonade", product: "peachmangolemonade", blurb: `${blurbs["riverreserve"]["peachmangolemonade"]}`},
{brand: "riverreserve", shelfName: "Pineapple Grape Menthol", product: "pineapplegrapementhol", blurb: `${blurbs["riverreserve"]["pineapplegrapementhol"]}`},
{brand: "riverreserve", shelfName: "Raspberry Lemon Italian Ice", product: "raspberrylemonitalianice", blurb: `${blurbs["riverreserve"]["raspberrylemonitalianice"]}`},
{brand: "riverreserve", shelfName: "River Colada", product: "rivercolada", blurb: `${blurbs["riverreserve"]["rivercolada"]}`},
{brand: "riverreserve", shelfName: "Smooth Sweet Tobacco", product: "smoothsweettobacco", blurb: `${blurbs["riverreserve"]["smoothsweettobacco"]}`},
{brand: "riverreserve", shelfName: "Strawberry Bandit", product: "strawberrybandit", blurb: `${blurbs["riverreserve"]["strawberrybandit"]}`},
{brand: "riverreserve", shelfName: "Strawberry Drifter", product: "strawberrydrifter", blurb: `${blurbs["riverreserve"]["strawberrydrifter"]}`},
{brand: "riverreserve", shelfName: "Strawberry Waffle Cone", product: "strawberrywafflecone", blurb: `${blurbs["riverreserve"]["strawberrywafflecone"]}`},
{brand: "riverreserve", shelfName: "Strawnana Drifter", product: "strawnanadrifter", blurb: `${blurbs["riverreserve"]["strawnanadrifter"]}`},
{brand: "riverreserve", shelfName: "Swamp Mama", product: "swampmama", blurb: `${blurbs["riverreserve"]["swampmama"]}`},
{brand: "riverreserve", shelfName: "Sweet Cream Butterscotch", product: "sweetcreambutterscotch", blurb: `${blurbs["riverreserve"]["sweetcreambutterscotch"]}`},
{brand: "riverreserve", shelfName: "Tigers Blood", product: "tigersblood", blurb: `${blurbs["riverreserve"]["tigersblood"]}`},
{brand: "riverreserve", shelfName: "Vanilla Bandit", product: "vanillabandit", blurb: `${blurbs["riverreserve"]["vanillabandit"]}`},
{brand: "riverreserve", shelfName: "Vanilla Graham", product: "vanillagraham", blurb: `${blurbs["riverreserve"]["vanillagraham"]}`},
{brand: "riverreserve", shelfName: "Vanilla Waffle Cone", product: "vanillawafflecone", blurb: `${blurbs["riverreserve"]["vanillawafflecone"]}`},
{brand: "riverreserve", shelfName: "Watermelon Punch Menthol", product: "watermelonpunchmenthol", blurb: `${blurbs["riverreserve"]["watermelonpunchmenthol"]}`},
{brand: "riverreserve", shelfName: "Wiki", product: "wiki", blurb: `${blurbs["riverreserve"]["wiki"]}`},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Antidote On Ice", product: "antidoteonice", blurb: `${blurbs["ruthless"]["antidoteonice"]}`},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: `${blurbs["ruthless"]["ezduzit"]}`},
{brand: "ruthless", shelfName: "Ez Duz It On Ice", product: "ezduzitonice", blurb: `${blurbs["ruthless"]["ezduzitonice"]}`},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: `${blurbs["ruthless"]["grapedrank"]}`},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: `${blurbs["ruthless"]["grapedrankonice"]}`},
{brand: "ruthless", shelfName: "Jungle Fever", product: "junglefever", blurb: `${blurbs["ruthless"]["junglefever"]}`},
{brand: "ruthless", shelfName: "Paradize", product: "paradize", blurb: `${blurbs["ruthless"]["paradize"]}`},
{brand: "ruthless", shelfName: "Rage", product: "rage", blurb: `${blurbs["ruthless"]["rage"]}`},
{brand: "ruthless", shelfName: "Skir Skirr On Ice", product: "skirskirronice", blurb: `${blurbs["ruthless"]["skirskirronice"]}`},
{brand: "ruthless", shelfName: "Slurricane", product: "slurricane", blurb: `${blurbs["ruthless"]["slurricane"]}`},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: `${blurbs["ruthless"]["strizzy"]}`},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: `${blurbs["ruthless"]["swampthang"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Fairground", product: "fairground", blurb: `${blurbs["svrf"]["fairground"]}`},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: `${blurbs["svrf"]["goldenticket"]}`},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: `${blurbs["svrf"]["pacificsangha"]}`},
{brand: "svrf", shelfName: "Boba Dewwy", product: "bobadewwy", blurb: `${blurbs["svrf"]["bobadewwy"]}`},
{brand: "svrf", shelfName: "Boba Jazzy", product: "bobajazzy", blurb: `${blurbs["svrf"]["bobajazzy"]}`},
{brand: "svrf", shelfName: "Boba Manggo", product: "bobamanggo", blurb: `${blurbs["svrf"]["bobamanggo"]}`},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon Cloud", product: "dragoncloud", blurb: `${blurbs["shijin"]["dragoncloud"]}`},
{brand: "shijin", shelfName: "Phoenix Tears", product: "phoenixtears", blurb: `${blurbs["shijin"]["phoenixtears"]}`},
{brand: "shijin", shelfName: "Tigers Milk", product: "tigersmilk", blurb: `${blurbs["shijin"]["tigersmilk"]}`},
{brand: "shijin", shelfName: "Tortoise Blood", product: "tortoiseblood", blurb: `${blurbs["shijin"]["tortoiseblood"]}`},
{brand: "shijin", shelfName: "Tortoise on Ice", product: "tortoiseonice", blurb: `${blurbs["shijin"]["tortoiseonice"]}`},
{brand: "shijin", shelfName: "Tortoise on the Rocks", product: "tortoiseontherocks", blurb: `${blurbs["shijin"]["tortoiseontherocks"]}`},
{brand: "silverback", shelfName: " ", product: "logo", blurb: " "},
{brand: "silverback", shelfName: "Amy", product: "amy", blurb: `${blurbs["silverback"]["amy"]}`},
{brand: "silverback", shelfName: "BooBoo", product: "booboo", blurb: `${blurbs["silverback"]["booboo"]}`},
{brand: "silverback", shelfName: "Harambe", product: "harambe", blurb: `${blurbs["silverback"]["harambe"]}`},
{brand: "silverback", shelfName: "Jenny", product: "jenny", blurb: `${blurbs["silverback"]["jenny"]}`},
{brand: "silverback", shelfName: "Lola", product: "lola", blurb: `${blurbs["silverback"]["lola"]}`},
{brand: "silverback", shelfName: "Sandy", product: "sandy", blurb: `${blurbs["silverback"]["sandy"]}`},
{brand: "thehypecollection", shelfName: " ", product: "logo", blurb: " "},
{brand: "thehypecollection", shelfName: "America", product: "america", blurb: `${blurbs["thehypecollection"]["america"]}`},
{brand: "thehypecollection", shelfName: "Blue Slushee", product: "blueslushee", blurb: `${blurbs["thehypecollection"]["blueslushee"]}`},
{brand: "thehypecollection", shelfName: "Cool Blue Slushee", product: "coolblueslushee", blurb: `${blurbs["thehypecollection"]["coolblueslushee"]}`},
{brand: "thehypecollection", shelfName: "Cotton Candy", product: "cottoncandy", blurb: `${blurbs["thehypecollection"]["cottoncandy"]}`},
{brand: "transistor", shelfName: " ", product: "logo", blurb: " "},
{brand: "transistor", shelfName: "LSD", product: "lsd", blurb: `${blurbs["transistor"]["lsd"]}`},
{brand: "transistor", shelfName: "Lemn Berry", product: "lemnberry", blurb: `${blurbs["transistor"]["lemnberry"]}`},
{brand: "transistor", shelfName: "Nazzo", product: "nazzo", blurb: `${blurbs["transistor"]["nazzo"]}`},
{brand: "transistor", shelfName: "Tango Chillin", product: "tangochillin", blurb: `${blurbs["transistor"]["tangochillin"]}`},
{brand: "vapetasia", shelfName: " ", product: "logo", blurb: " "},
{brand: "vapetasia", shelfName: "Blackberry Lemonade", product: "blackberrylemonade", blurb: `${blurbs["vapetasia"]["blackberrylemonade"]}`},
{brand: "vapetasia", shelfName: "Blueberry Killer Kustard", product: "blueberrykillerkustard", blurb: `${blurbs["vapetasia"]["blueberrykillerkustard"]}`},
{brand: "vapetasia", shelfName: "Killer Kustard", product: "killerkustard", blurb: `${blurbs["vapetasia"]["killerkustard"]}`},
{brand: "vapetasia", shelfName: "Lemon Killer Kustard", product: "lemonkillerkustard", blurb: `${blurbs["vapetasia"]["lemonkillerkustard"]}`},
{brand: "vapetasia", shelfName: "Rainbow Road", product: "rainbowroad", blurb: `${blurbs["vapetasia"]["rainbowroad"]}`},
{brand: "vapetasia", shelfName: "Strawberry Killer Kustard", product: "strawberrykillerkustard", blurb: `${blurbs["vapetasia"]["strawberrykillerkustard"]}`},
];
let saltInventory = [
{brand: "jammonster", shelfName: " ", product: "logo", blurb: " "},
{brand: "jammonster", shelfName: "PB Grape", product: "pbgrape", blurb: `${blurbs["jammonster"]["pbgrape"]}`},
{brand: "jammonster", shelfName: "PB Strawberry", product: "pbstrawberry", blurb: `${blurbs["jammonster"]["pbstrawberry"]}`},
{brand: "jammonster", shelfName: "Banana", product: "banana", blurb: `${blurbs["jammonster"]["banana"]}`},
{brand: "jammonster", shelfName: "Blueberry", product: "blueberry", blurb: `${blurbs["jammonster"]["blueberry"]}`},
{brand: "jammonster", shelfName: "Mangerine Guava", product: "mangerineguava", blurb: `${blurbs["jammonster"]["mangerineguava"]}`},
{brand: "jammonster", shelfName: "Melon Colada", product: "meloncolada", blurb: `${blurbs["jammonster"]["meloncolada"]}`},
{brand: "jammonster", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["jammonster"]["strawberry"]}`},
{brand: "jammonster", shelfName: "Strawmelon Apple", product: "strawmelonapple", blurb: `${blurbs["jammonster"]["strawmelonapple"]}`},
{brand: "airfactory", shelfName: " ", product: "logo", blurb: " "},
{brand: "airfactory", shelfName: "Berry Rush", product: "berryrush", blurb: `${blurbs["airfactory"]["berryrush"]}`},
{brand: "airfactory", shelfName: "Blue Razz", product: "bluerazz", blurb: `${blurbs["airfactory"]["bluerazz"]}`},
{brand: "airfactory", shelfName: "Blue Razz Ice", product: "bluerazzice", blurb: `${blurbs["airfactory"]["bluerazzice"]}`},
{brand: "airfactory", shelfName: "Creamy Crunch", product: "creamycrunch", blurb: `${blurbs["airfactory"]["creamycrunch"]}`},
{brand: "airfactory", shelfName: "Custard", product: "custard", blurb: `${blurbs["airfactory"]["custard"]}`},
{brand: "airfactory", shelfName: "Custard Tobacco", product: "custardtobacco", blurb: `${blurbs["airfactory"]["custardtobacco"]}`},
{brand: "airfactory", shelfName: "Mango", product: "mango", blurb: `${blurbs["airfactory"]["mango"]}`},
{brand: "airfactory", shelfName: "Mango Ice", product: "mangoice", blurb: `${blurbs["airfactory"]["mangoice"]}`},
{brand: "airfactory", shelfName: "Melon Lush", product: "melonlush", blurb: `${blurbs["airfactory"]["melonlush"]}`},
{brand: "airfactory", shelfName: "Melon Lush Ice", product: "melonlushice", blurb: `${blurbs["airfactory"]["melonlushice"]}`},
{brand: "airfactory", shelfName: "Menthol", product: "menthol", blurb: `${blurbs["airfactory"]["menthol"]}`},
{brand: "airfactory", shelfName: "Mint", product: "mint", blurb: `${blurbs["airfactory"]["mint"]}`},
{brand: "airfactory", shelfName: "Mixed Berry", product: "mixedberry", blurb: `${blurbs["airfactory"]["mixedberry"]}`},
{brand: "airfactory", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["airfactory"]["strawberrykiwi"]}`},
{brand: "airfactory", shelfName: "Tropic Freeze", product: "tropicfreeze", blurb: `${blurbs["airfactory"]["tropicfreeze"]}`},
{brand: "cloudnurdz", shelfName: " ", product: "logo", blurb: " "},
{brand: "cloudnurdz", shelfName: "Grape Apple", product: "grapeapple", blurb: `${blurbs["cloudnurdz"]["grapeapple"]}`},
{brand: "cloudnurdz", shelfName: "Grape Strawberry", product: "grapestrawberry", blurb: `${blurbs["cloudnurdz"]["grapestrawberry"]}`},
{brand: "cloudnurdz", shelfName: "Kiwi Melon", product: "kiwimelon", blurb: `${blurbs["cloudnurdz"]["kiwimelon"]}`},
{brand: "cloudnurdz", shelfName: "Peach Blue Razz", product: "peachbluerazz", blurb: `${blurbs["cloudnurdz"]["peachbluerazz"]}`},
{brand: "cloudnurdz", shelfName: "Strawberry Lemon", product: "strawberrylemon", blurb: `${blurbs["cloudnurdz"]["strawberrylemon"]}`},
{brand: "fruitia", shelfName: " ", product: "logo", blurb: " "},
{brand: "fruitia", shelfName: "Apple Kiwi Crush", product: "applekiwicrush", blurb: `${blurbs["fruitia"]["applekiwicrush"]}`},
{brand: "fruitia", shelfName: "Blood Orange Cactus Cooler", product: "bloodorangecactuscooler", blurb: `${blurbs["fruitia"]["bloodorangecactuscooler"]}`},
{brand: "fruitia", shelfName: "Citrus Twist", product: "citrustwist", blurb: `${blurbs["fruitia"]["citrustwist"]}`},
{brand: "fruitia", shelfName: "Passion Fruit Guava Punch", product: "passionfruitguavapunch", blurb: `${blurbs["fruitia"]["passionfruitguavapunch"]}`},
{brand: "fruitia", shelfName: "Strawberry Coconut Refreshers", product: "strawberrycoconutrefreshers", blurb: `${blurbs["fruitia"]["strawberrycoconutrefreshers"]}`},
{brand: "juicehead", shelfName: " ", product: "logo", blurb: " "},
{brand: "juicehead", shelfName: "Blueberry Lemon", product: "blueberrylemon", blurb: `${blurbs["juicehead"]["blueberrylemon"]}`},
{brand: "juicehead", shelfName: "Guava Peach", product: "guavapeach", blurb: `${blurbs["juicehead"]["guavapeach"]}`},
{brand: "juicehead", shelfName: "Peach Pear", product: "peachpear", blurb: `${blurbs["juicehead"]["peachpear"]}`},
{brand: "juicehead", shelfName: "Pineapple Grapefruit", product: "pineapplegrapefruit", blurb: `${blurbs["juicehead"]["pineapplegrapefruit"]}`},
{brand: "juicehead", shelfName: "Strawberry Kiwi", product: "strawberrykiwi", blurb: `${blurbs["juicehead"]["strawberrykiwi"]}`},
{brand: "juicehead", shelfName: "Watermelon Lime", product: "watermelonlime", blurb: `${blurbs["juicehead"]["watermelonlime"]}`},
{brand: "lemontwist", shelfName: " ", product: "logo", blurb: " "},
{brand: "lemontwist", shelfName: "Honeydew Melon Chew", product: "honeydewmelonchew", blurb: `${blurbs["lemontwist"]["honeydewmelonchew"]}`},
{brand: "lemontwist", shelfName: "Iced Pink Punch Lemonade", product: "icedpinkpunchlemonade", blurb: `${blurbs["lemontwist"]["icedpinkpunchlemonade"]}`},
{brand: "lemontwist", shelfName: "Pink Punch Lemonade", product: "pinkpunchlemonade", blurb: `${blurbs["lemontwist"]["pinkpunchlemonade"]}`},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: `${blurbs["lemontwist"]["watermelonmadness"]}`},
{brand: "lemontwist", shelfName: "Honeydew Melon Chew", product: "honeydewmelonchew", blurb: `${blurbs["lemontwist"]["honeydewmelonchew"]}`},
{brand: "lemontwist", shelfName: "Watermelon Madness", product: "watermelonmadness", blurb: `${blurbs["lemontwist"]["watermelonmadness"]}`},
{brand: "oneup", shelfName: " ", product: "logo", blurb: " "},
{brand: "oneup", shelfName: "Apple Melon", product: "applemelon", blurb: `${blurbs["oneup"]["applemelon"]}`},
{brand: "oneup", shelfName: "Mango Ice", product: "mangoice", blurb: `${blurbs["oneup"]["mangoice"]}`},
{brand: "oneup", shelfName: "Orgasm", product: "orgasm", blurb: `${blurbs["oneup"]["orgasm"]}`},
{brand: "oneup", shelfName: "Orgasm Ice", product: "orgasmice", blurb: `${blurbs["oneup"]["orgasmice"]}`},
{brand: "oneup", shelfName: "Reign Berry", product: "reignberry", blurb: `${blurbs["oneup"]["reignberry"]}`},
{brand: "oneup", shelfName: "Strawberry Cheesecake", product: "strawberrycheesecake", blurb: `${blurbs["oneup"]["strawberrycheesecake"]}`},
{brand: "oneup", shelfName: "Strawberry Gummy", product: "strawberrygummy", blurb: `${blurbs["oneup"]["strawberrygummy"]}`},
{brand: "oneup", shelfName: "Sweet Tobacco", product: "sweettobacco", blurb: `${blurbs["oneup"]["sweettobacco"]}`},
{brand: "podjuice", shelfName: " ", product: "logo", blurb: " "},
{brand: "podjuice", shelfName: "Jewel Mint", product: "jewelmint", blurb: `${blurbs["podjuice"]["jewelmint"]}`},
{brand: "podjuice", shelfName: "Jewel Mint Sapphire", product: "jewelmintsapphire", blurb: `${blurbs["podjuice"]["jewelmintsapphire"]}`},
{brand: "riverreserve", shelfName: " ", product: "logo", blurb: " "},
{brand: "riverreserve", shelfName: "Blue Island Punch", product: "blueislandpunch", blurb: `${blurbs["riverreserve"]["blueislandpunch"]}`},
{brand: "riverreserve", shelfName: "Lemon Drifter", product: "lemondrifter", blurb: `${blurbs["riverreserve"]["lemondrifter"]}`},
{brand: "riverreserve", shelfName: "Royal Tobacco", product: "royaltobacco", blurb: `${blurbs["riverreserve"]["royaltobacco"]}`},
{brand: "riverreserve", shelfName: "Saltwater Creek", product: "saltwatercreek", blurb: `${blurbs["riverreserve"]["saltwatercreek"]}`},
{brand: "riverreserve", shelfName: "Tangie", product: "tangie", blurb: `${blurbs["riverreserve"]["tangie"]}`},
{brand: "riverreserve", shelfName: "Winter Berry", product: "winterberry", blurb: `${blurbs["riverreserve"]["winterberry"]}`},
{brand: "ruthless", shelfName: " ", product: "logo", blurb: " "},
{brand: "ruthless", shelfName: "Antidote on Ice", product: "antidoteonice", blurb: `${blurbs["ruthless"]["antidoteonice"]}`},
{brand: "ruthless", shelfName: "Ez Duz It", product: "ezduzit", blurb: `${blurbs["ruthless"]["ezduzit"]}`},
{brand: "ruthless", shelfName: "Ez Duz It on Ice", product: "ezduzitonice", blurb: `${blurbs["ruthless"]["ezduzitonice"]}`},
{brand: "ruthless", shelfName: "Grape Drank", product: "grapedrank", blurb: `${blurbs["ruthless"]["grapedrank"]}`},
{brand: "ruthless", shelfName: "Grape Drank on Ice", product: "grapedrankonice", blurb: `${blurbs["ruthless"]["grapedrankonice"]}`},
{brand: "ruthless", shelfName: "Paradise", product: "paradise", blurb: `${blurbs["ruthless"]["paradise"]}`},
{brand: "ruthless", shelfName: "Strizzy", product: "strizzy", blurb: `${blurbs["ruthless"]["strizzy"]}`},
{brand: "ruthless", shelfName: "Swamp Thang", product: "swampthang", blurb: `${blurbs["ruthless"]["swampthang"]}`},
{brand: "ruthless", shelfName: "Tropic Thunda", product: "tropicthunda", blurb: `${blurbs["ruthless"]["tropicthunda"]}`},
{brand: "svrf", shelfName: " ", product: "logo", blurb: " "},
{brand: "svrf", shelfName: "Fairgrounds", product: "fairgrounds", blurb: `${blurbs["svrf"]["fairgrounds"]}`},
{brand: "svrf", shelfName: "Golden Ticket", product: "goldenticket", blurb: `${blurbs["svrf"]["goldenticket"]}`},
{brand: "svrf", shelfName: "Pacific Sangha", product: "pacificsangha", blurb: `${blurbs["svrf"]["pacificsangha"]}`},
{brand: "svrf", shelfName: "Satisfying", product: "satisfying", blurb: `${blurbs["svrf"]["satisfying"]}`},
{brand: "sadboy", shelfName: " ", product: "logo", blurb: " "},
{brand: "sadboy", shelfName: "Punch Berry Blood", product: "punchberryblood", blurb: `${blurbs["sadboy"]["punchberryblood"]}`},
{brand: "sadboy", shelfName: "Punch Berry Ice", product: "punchberryice", blurb: `${blurbs["sadboy"]["punchberryice"]}`},
{brand: "sadboy", shelfName: "Rainbow Blood", product: "rainbowblood", blurb: `${blurbs["sadboy"]["rainbowblood"]}`},
{brand: "sadboy", shelfName: "Rainbow Ice", product: "rainbowice", blurb: `${blurbs["sadboy"]["rainbowice"]}`},
{brand: "sadboy", shelfName: "Strawberry Blood", product: "strawberryblood", blurb: `${blurbs["sadboy"]["strawberryblood"]}`},
{brand: "sadboy", shelfName: "Strawberry Ice", product: "strawberryice", blurb: `${blurbs["sadboy"]["strawberryice"]}`},
{brand: "sadboy", shelfName: "Unicorn Tears", product: "unicorntears", blurb: `${blurbs["sadboy"]["unicorntears"]}`},
{brand: "shijin", shelfName: " ", product: "logo", blurb: " "},
{brand: "shijin", shelfName: "Dragon", product: "dragon", blurb: `${blurbs["shijin"]["dragon"]}`},
{brand: "shijin", shelfName: "Phoenix", product: "phoenix", blurb: `${blurbs["shijin"]["phoenix"]}`},
{brand: "shijin", shelfName: "Tiger", product: "tiger", blurb: `${blurbs["shijin"]["tiger"]}`},
{brand: "shijin", shelfName: "Tortoise", product: "tortoise", blurb: `${blurbs["shijin"]["tortoise"]}`},
{brand: "shijin", shelfName: "Tortoise On Ice", product: "tortoiseonice", blurb: `${blurbs["shijin"]["tortoiseonice"]}`},
{brand: "skwezed", shelfName: " ", product: "logo", blurb: " "},
{brand: "skwezed", shelfName: "Grapefruit", product: "grapefruit", blurb: `${blurbs["skwezed"]["grapefruit"]}`},
{brand: "skwezed", shelfName: "Green Apple", product: "greenapple", blurb: `${blurbs["skwezed"]["greenapple"]}`},
{brand: "skwezed", shelfName: "Lychee", product: "lychee", blurb: `${blurbs["skwezed"]["lychee"]}`},
{brand: "skwezed", shelfName: "Mango", product: "mango", blurb: `${blurbs["skwezed"]["mango"]}`},
{brand: "skwezed", shelfName: "Peach", product: "peach", blurb: `${blurbs["skwezed"]["peach"]}`},
{brand: "skwezed", shelfName: "Watermelon", product: "watermelon", blurb: `${blurbs["skwezed"]["watermelon"]}`},
{brand: "solace", shelfName: " ", product: "logo", blurb: " "},
{brand: "solace", shelfName: "Banana Dragonberry", product: "bananadragonberry", blurb: `${blurbs["solace"]["bananadragonberry"]}`},
{brand: "solace", shelfName: "Berry Bash", product: "berrybash", blurb: `${blurbs["solace"]["berrybash"]}`},
{brand: "solace", shelfName: "Blue Raspberry Lemonade Ice", product: "blueraspberrylemonadeice", blurb: `${blurbs["solace"]["blueraspberrylemonadeice"]}`},
{brand: "solace", shelfName: "Blues Lemonade", product: "blueslemonade", blurb: `${blurbs["solace"]["blueslemonade"]}`},
{brand: "solace", shelfName: "Blues Mango", product: "bluesmango", blurb: `${blurbs["solace"]["bluesmango"]}`},
{brand: "solace", shelfName: "Bold Tobacco", product: "boldtobacco", blurb: `${blurbs["solace"]["boldtobacco"]}`},
{brand: "solace", shelfName: "Cool Tobacco", product: "cooltobacco", blurb: `${blurbs["solace"]["cooltobacco"]}`},
{brand: "solace", shelfName: "Dragonthol", product: "dragonthol", blurb: `${blurbs["solace"]["dragonthol"]}`},
{brand: "solace", shelfName: "Grape", product: "grape", blurb: `${blurbs["solace"]["grape"]}`},
{brand: "solace", shelfName: "Juiced Apple", product: "juicedapple", blurb: `${blurbs["solace"]["juicedapple"]}`},
{brand: "solace", shelfName: "Lemon Lime Fusion", product: "lemonlimefusion", blurb: `${blurbs["solace"]["lemonlimefusion"]}`},
{brand: "solace", shelfName: "Mint", product: "mint", blurb: `${blurbs["solace"]["mint"]}`},
{brand: "solace", shelfName: "Pineapple", product: "pineapple", blurb: `${blurbs["solace"]["pineapple"]}`},
{brand: "solace", shelfName: "Sea Salt Blueberry", product: "seasaltblueberry", blurb: `${blurbs["solace"]["seasaltblueberry"]}`},
{brand: "solace", shelfName: "Seedless Watermelon", product: "seedlesswatermelon", blurb: `${blurbs["solace"]["seedlesswatermelon"]}`},
{brand: "solace", shelfName: "Strawberry", product: "strawberry", blurb: `${blurbs["solace"]["strawberry"]}`},
{brand: "solace", shelfName: "Strawberry Kiwi Ice", product: "strawberrykiwiice", blurb: `${blurbs["solace"]["strawberrykiwiice"]}`},
{brand: "solace", shelfName: "Tropic Strawberry", product: "tropicstrawberry", blurb: `${blurbs["solace"]["tropicstrawberry"]}`},
{brand: "vapetasia", shelfName: " ", product: "logo", blurb: " "},
{brand: "vapetasia", shelfName: "Killer Kustard Strawberry", product: "killerkustardstrawberry", blurb: `${blurbs["vapetasia"]["killerkustardstrawberry"]}`},
{brand: "vapetasia", shelfName: "Rainbow Road", product: "rainbowroad", blurb: `${blurbs["vapetasia"]["rainbowroad"]}`},
{brand: "vapetasia", shelfName: "Royalty II Salt", product: "royaltyiisalt", blurb: `${blurbs["vapetasia"]["royaltyiisalt"]}`},
];



let combInv = inventory.concat(saltInventory);
let logos = combInv.filter(a => {
	return(a.product.includes("logo"));
});
let productNum = (inventory.length + saltInventory.length) - logos.length;
let makers = [];
for(b = 0; b < combInv.length; b++){
	if(makers.includes(combInv[b].brand) != true){
		makers.push(combInv[b].brand);
	}
};
let host = document.getElementById("hosting");
if(host != null){
	host.innerHTML = `Hosting definitions for <span class="fatboysRed">${productNum}+</span> flavors across <span class="fatboysRed">${makers.length}</span> manufacturers. <br> Ver. 2.0.1`;
}
